---
permalink: iscsi-config-esxi/index.html 
sidebar: sidebar 
keywords: iscsi, service, storage, virtual, machine, svm, provision, lun, esx, host, computer 
summary: 使用ONTAP 經典的支援功能（ONTAP 例如、VMware ESXi 9.7及更早版本）、您可以在儲存虛擬機器（SVM）上快速設定iSCSI服務、配置LUN、並使用ESXi主機電腦上的iSCSI啟動器來提供LUN。 
---
= 使用VSC的ESXi iSCSI組態總覽
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用ONTAP 經典的支援功能（ONTAP 例如、VMware ESXi 9.7及更早版本）、您可以在儲存虛擬機器（SVM）上快速設定iSCSI服務、配置LUN、並使用ESXi主機電腦上的iSCSI啟動器來提供LUN。

如果發生下列情況、請使用此程序：

* 您正在ESXi 5.x上使用原生ESXi iSCSI軟體啟動器
* 您並未使用CHAP驗證來進行iSCSI。
* 您正在使用VMware vSphere（VSC）支援版本的虛擬儲存主控台、為ESX主機設定儲存設定。
+
** 從VSC 7.0開始、VSC就是的一部分 https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/index.html["VMware vSphere適用的VMware工具ONTAP"^] 虛擬應用裝置、包括VSC、適用於儲存感知（VASA）供應商的vStorage API、以及適用於VMware vSphere功能的儲存複寫介面卡（SRA）。
** 請務必檢查 https://imt.netapp.com/matrix/["NetApp 互通性對照表工具"^] 以確認您目前ONTAP 的更新版本與VSC版本之間的相容性。


* 您的網路使用的是IPv4定址。
* 您想要使用下列任一方法、將位址指派給邏輯介面：
+
** 自動從您定義的子網路中執行
** 手動使用從現有子網路選取的位址
** 手動使用將新增至現有子網路的位址


* 叢集中的每個節點至少有兩個高速乙太網路連接埠（至少1 GbE、建議10 GbE）可用。
+
車載 UTA2 （也稱為 `CNA`）連接埠是可設定的。您可以在ONTAP 支援的CLI中設定這些連接埠、但他的程序並未涵蓋該程序。

+
請參閱 link:https://docs.netapp.com/us-en/ontap/networking/index.html["網路管理"^] 用於使用CLI設定乙太網路連接埠流量控制。

* 您未設定iSCSI SAN開機。
* 您是透過ESXi Hypervisor為VM提供儲存設備、而非在VM內執行iSCSI啟動器。


如需詳細資訊、請參閱 https://docs.netapp.com/us-en/netapp-solutions/virtualization/vsphere_ontap_ontap_for_vsphere.html["TR-4597：VMware vSphere ONTAP for VMware"^] 以及VSC版本的文件。
