---
permalink: online-help-96-97/concept_storage_pools.html 
sidebar: sidebar 
keywords: system, manager, storage, pools, ssd, flash, pool, aggregates, online, help, create, 
summary: 您可以使用System Manager建立儲存資源池、讓多個Flash Pool Aggregate共用SSD。 
---
= 使用System Manager管理儲存資源池- ONTAP 更新版本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用ONTAP 經典版的經典版《支援功能》ONTAP （適用於支援功能更新版本的版本）來建立儲存資源池、讓多個Flash Pool Aggregate能夠共享SSD。



== 建立儲存資源池

儲存資源池是SSD（快取磁碟）的集合。您可以使用System Manager結合SSD來建立儲存資源池、讓您在HA配對之間共用SSD和SSD備援磁碟、以便同時分配給兩個以上的Flash Pool Aggregate。

.開始之前
* HA配對的兩個節點都必須啟動並執行、才能透過儲存資源池來配置SSD和SSD備援磁碟機。
* 儲存資源池至少必須有3個SSD。
* 儲存資源池中的所有SSD都必須由同一個HA配對擁有。


.關於這項工作
當您使用SSD將磁碟新增至儲存資源池時、System Manager會強制執行SSD RAID群組的熱備援規則。例如、如果 SSD RAID 群組和選項中有 10 個 SSD `raid.min_spare_count` 設為 `1` 在節點層級、 System Manager 將 1 個 SSD 保留為熱備援磁碟、並使用其他 9 個 SSD 進行 SSD 相關作業。

使用System Manager建立儲存資源池時、您無法使用已分割的SSD。

.步驟
. 按一下「*儲存設備*>*集合體與磁碟*>*儲存資源池*」。
. 在* Storage Pools*（儲存集區*）視窗中、按一下*「Create*」。
. 在「*建立儲存資源池*」對話方塊中、指定儲存資源池的名稱、磁碟大小及磁碟數目。
. 按一下「 * 建立 * 」。




== 將磁碟新增至儲存資源池

您可以使用System Manager將SSD新增至現有的儲存資源池、並增加其快取大小。

.開始之前
HA配對的兩個節點都必須啟動並執行、才能透過儲存資源池來配置SSD和SSD備援磁碟機。

.關於這項工作
* 您新增至儲存資源池的SSD、會使用儲存資源池快取、按比例分散到集合體中、並分配到儲存資源池的可用空間中。
* 當您使用SSD將磁碟新增至儲存資源池時、System Manager會強制執行SSD RAID群組的熱備援規則。
+
例如、如果 SSD RAID 群組和選項中有 10 個 SSD `raid.min_spare_count` 設為 `1` 在節點層級、 System Manager 將 1 個 SSD 保留為熱備援磁碟、並使用其他 9 個 SSD 進行 SSD 相關作業。

* 使用System Manager將磁碟新增至儲存資源池時、您無法使用已分割的SSD。


.步驟
. 按一下「*儲存設備*>*集合體與磁碟*>*儲存資源池*」。
. 在* Storage Pools*（儲存集區*）視窗中、選取儲存集區、然後按一下* Add Disks*（新增磁碟*）。
. 在「*新增磁碟*」對話方塊中、指定您要新增的磁碟數目。
. 單擊 * 下一步 * 。
. 在* Summary（摘要）*對話方塊中、檢閱快取在各種集合體之間的分散方式、以及儲存資源池的可用空間。
. 按一下「 * 新增 * 」。




== 刪除儲存資源池

當儲存資源池的快取不是最佳狀態、或是任何Aggregate或Flash Pool Aggregate不再使用時、您可能會想要刪除儲存資源池。您可以使用System Manager中的刪除儲存池對話方塊來刪除儲存池。

.開始之前
任何Aggregate均不得使用儲存資源池。

.步驟
. 按一下「*儲存設備*>*集合體與磁碟*>*儲存資源池*」。
. 在* Storage Pools*（儲存集區*）視窗中、選取您要刪除的儲存集區、然後按一下*刪除*。
. 在*刪除儲存池*對話方塊中、按一下*刪除*。




== 使用SSD儲存資源池

若要讓多個Flash Pool Aggregate共用SSD、您可以將SSD新增至_storage Pool_。將SSD新增至儲存資源池後、您將無法再將SSD管理為獨立實體。您必須使用儲存資源池來指派或配置SSD所提供的儲存設備。

您可以為特定的高可用度（HA）配對建立儲存資源池。然後、您可以將該儲存資源池的配置單元新增至同一HA配對擁有的一或多個Flash資源池集合體。就像磁碟必須由擁有Aggregate的同一個節點擁有、才能將磁碟分配給該節點一樣、儲存資源池只能為擁有儲存資源池的其中一個節點所擁有的Flash資源池集合體提供儲存設備。

如果您必須增加系統上的Flash Pool快取數量、可以將更多SSD新增至儲存資源池、最多可新增至使用儲存資源池之Flash Pool快取的RAID類型RAID群組大小上限。當您將SSD新增至現有儲存資源池時、會增加儲存資源池的配置單位大小、包括已分配給Flash資源池集合體的任何配置單位。

儲存資源池只能使用一個備用SSD、因此如果該儲存資源池中的SSD無法使用、ONTAP 則可使用備用SSD重建故障SSD的分割區。您不需要保留任何配置單位作為備用容量；ONTAP 在儲存資源池中、只能使用完整且未分割的SSD作為SSD的備用磁碟機。

將SSD新增至儲存資源池之後、您就無法移除SSD、因為您無法從集合體移除磁碟。如果您想要再次將儲存資源池中的SSD當成獨立磁碟機使用、則必須銷毀儲存資源池分配單元已分配到的所有Flash資源池集合體、然後銷毀儲存資源池。



== 使用SSD儲存資源池的需求與最佳實務做法

部分技術無法與使用SSD儲存資源池的Flash Pool Aggregate結合使用。

下列技術無法搭配使用SSD儲存資源池的Flash Pool Aggregate用於快取儲存設備：

* MetroCluster
* 功能SyncMirror
+
鏡射Aggregate可與使用儲存資源池的Flash Pool Aggregate共存；不過、Flash Pool Aggregate無法鏡射。

* 實體SSD
+
Flash Pool Aggregate可以使用SSD儲存資源池或實體SSD、但不能同時使用兩者。



SSD儲存資源池必須符合下列規則：

* SSD儲存資源池只能包含SSD；HDD無法新增至SSD儲存資源池。
* SSD儲存資源池中的所有SSD都必須由相同的高可用度（HA）配對擁有。
* 您無法在儲存資源池中使用已分割為根資料分割的SSD。


如果您將單一儲存資源池的儲存設備提供給兩個不同RAID類型的快取、而且您將儲存資源池的大小擴充至超過RAID4的最大RAID群組大小、則RAID4配置單元中的額外分割區將不再使用。因此、最佳實務做法是讓儲存資源池的快取RAID類型保持一致。

您無法變更從儲存資源池配置的快取RAID群組RAID類型。您可以在新增第一個配置單元之前、先設定快取的RAID類型、之後就無法變更RAID類型。

當您建立儲存資源池或將SSD新增至現有儲存資源池時、必須使用相同大小的SSD。如果發生故障且沒有正確大小的備用SSD、ONTAP 則可以使用較大的SSD來更換故障的SSD。不過、較大的SSD大小適合儲存資源池中其他SSD的大小、導致SSD容量遺失。

儲存資源池只能使用一個備用SSD。如果儲存資源池為HA配對中兩個節點所擁有的Flash資源池集合體提供配置單元、則備用SSD可由任一節點擁有。不過、如果儲存資源池僅提供分配單元給HA配對中某個節點所擁有的Flash資源池集合體、則該SSD備援磁碟機必須由該節點擁有。



== 使用SSD儲存資源池的考量

SSD儲存資源池提供許多優點、但也會引進一些限制、您在決定使用SSD儲存資源池或專用SSD時應注意。

SSD儲存資源池只有在提供快取給兩個或多個Flash資源池集合體時才有意義。SSD儲存資源池提供下列優點：

* 提高Flash Pool Aggregate中使用SSD的儲存使用率
+
SSD儲存資源池可讓您在兩個或多個Flash Pool Aggregate之間共用同位元SSD、藉此降低同位元檢查所需的SSD整體百分比。

* 能夠在HA合作夥伴之間共用備援磁碟機
+
由於儲存資源池實際上是由HA配對擁有、因此其中一家HA合作夥伴擁有一部備援磁碟機、可在需要時作為整個SSD儲存資源池的備用磁碟機。

* 更妥善運用SSD效能
+
SSD提供的高效能可支援HA配對中的兩個控制器存取。



這些優勢必須與使用SSD儲存資源池的成本進行比較、包括下列項目：

* 減少故障隔離
+
單一SSD的遺失會影響所有包含其中一個分割區的RAID群組。在這種情況下、每個從SSD儲存池配置快取的Flash Pool Aggregate、若包含受影響的SSD、則會有一或多個RAID群組進行重建。

* 降低效能隔離
+
如果Flash Pool快取的大小不正確、則共享快取的Flash Pool Aggregate之間可能會發生快取爭用。適當的快取大小調整和QoS控制、可降低此風險。

* 降低管理彈性
+
當您將儲存設備新增至儲存資源池時、會增加所有Flash資源池快取的大小、這些快閃資源池快取包含來自該儲存資源池的一或多個配置單元；您無法判斷額外容量的分散方式。





== 將SSD新增至現有儲存資源池的考量、而非建立新的儲存資源池

您可以透過兩種方式來增加SSD快取的大小：將SSD新增至現有的SSD儲存資源池、或建立新的SSD儲存資源池。您的最佳方法取決於組態和儲存方案。

在建立新的儲存資源池和新增儲存容量至現有儲存資源池之間、選擇的方式類似於決定要建立新的RAID群組、或是將儲存設備新增至現有的RAID群組：

* 如果您要新增大量SSD、建立新的儲存資源池可提供更大的靈活度、因為新的儲存資源池的配置方式與現有的儲存資源池不同。
* 如果您只要新增幾個SSD、而增加現有Flash Pool快取的RAID群組大小並不是問題、那麼在現有儲存資源池中新增SSD可降低備用和同位元檢查成本、並自動配置新的儲存設備。


如果您的儲存資源池提供分配單元給快閃資源池集合體、而快取具有不同RAID類型、而且您將儲存資源池的大小擴充至超過RAID4 RAID群組大小上限、則不會使用RAID4配置單元中新增的分割區。



== 為何要將磁碟新增至儲存資源池

您可以將SSD新增至現有的儲存資源池、並增加其快取大小。當您將SSD新增至已分配給Flash Pool Aggregate之分配單元的儲存資源池時、會增加每個集合體的快取大小、以及儲存資源池的總快取。

如果尚未配置儲存資源池的配置單元、將SSD新增至該儲存資源池並不會影響SSD快取大小。

將SSD新增至現有儲存資源池時、SSD必須由儲存資源池中現有SSD的一個節點或同一個HA配對的另一個節點擁有。您可以新增HA配對任一節點所擁有的SSD。



== 儲存資源池的運作方式

_storage Pool_是SSD的集合。您可以結合SSD來建立儲存資源池、讓您同時在多個Flash Pool Aggregate之間共用SSD和SSD備援磁碟機。

儲存資源池由分配單元組成、可用來提供SSD和SSD備援磁碟機來集合體或增加現有的SSD大小。

將SSD新增至儲存資源池之後、您就無法再將SSD當作個別磁碟使用。您必須使用儲存資源池來指派或配置SSD所提供的儲存設備。



== 儲存資源池視窗

您可以使用「儲存資源池」視窗來建立、顯示及管理SSD的專屬快取、也稱為_storage Pools_。這些儲存資源池可與非根Aggregate建立關聯、以提供SSD快取和Flash Pool Aggregate來增加其大小。

此頁面不適用於包含具有All Flash Optimized特性設定之節點的叢集。



=== 命令按鈕

* *建立*
+
開啟「建立儲存資源池」對話方塊、您可以使用此對話方塊來建立儲存資源池。

* *新增磁碟*
+
開啟「新增磁碟」對話方塊、可讓您將快取磁碟新增至儲存資源池。

* *刪除*
+
刪除選取的儲存資源池。

* *重新整理*
+
更新視窗中的資訊。





=== 儲存資源池清單

* *名稱*
+
顯示儲存資源池的名稱。

* *總快取*
+
顯示儲存資源池的總快取大小。

* *備用快取*
+
顯示儲存資源池的可用備用快取大小。

* *已用快取（%）*
+
顯示儲存資源池已使用快取大小的百分比。

* *分配單位*
+
顯示總快取大小的最小分配單位、可用來增加儲存資源池的大小。

* *擁有者*
+
顯示HA配對的名稱、或儲存資源池所關聯的節點名稱。

* *州*
+
顯示儲存資源池的狀態、可以是「正常」、「降級」、「建立」、「刪除」、「重新指派」、 或成長。

* *健康*
+
顯示儲存資源池是否健全。





=== 詳細資料索引標籤

顯示所選儲存池的詳細資訊、例如名稱、健全狀況、儲存類型、磁碟數、總快取、 備用快取、已使用的快取大小（以百分比表示）和分配單元。索引標籤也會顯示儲存資源池所配置之集合體的名稱。



=== 磁碟索引標籤

顯示所選儲存池中磁碟的詳細資訊、例如名稱、磁碟類型、可用大小和總大小。

*相關資訊*

xref:task_provisioning_storage_by_creating_flash_pool_aggregate_manually.adoc[手動建立Flash Pool Aggregate來配置儲存設備]

xref:task_provisioning_cache_by_adding_disks.adoc[新增SSD來配置快取]

https://docs.netapp.com/us-en/ontap/disks-aggregates/index.html["磁碟與Aggregate管理"]
