---
permalink: online-help-96-97/concept_service_processors.html 
sidebar: sidebar 
keywords: service, processors, monitor, manage, storage, system, manager, temperature, voltage, current, fan, speed, online, help, isolate, management, network, traffic, sp, bmc, e0m, interface, subnet, performance, routing, ip, address, edit 
summary: 您可以使用服務處理器、透過System Manager監控及管理儲存系統參數、例如溫度、電壓、電流及風扇速度。 
---
= 搭配使用Service處理器搭配System Manager ONTAP -支援更新版本的更新版本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用支援ONTAP 經典版《支援服務處理器》（ONTAP 適用於更新版本的版本）來監控和管理儲存系統參數、例如溫度、電壓、電流和風扇速度。



== 隔離管理網路流量

最佳實務做法是在專供管理流量使用的子網路上設定SP/BMC和e0M管理介面。透過管理網路執行資料流量可能會導致效能降低和路由問題。

大多數儲存控制器上的管理乙太網路連接埠（以機箱背面的扳手圖示表示）會連接至內部乙太網路交換器。內部交換器可連線至SP/BMC和e0M管理介面、您可以使用這些介面透過TCP/IP通訊協定（例如：Telnet、SSH和SNMP）來存取儲存系統。

如果您打算同時使用遠端管理裝置和e0M、則必須在相同的IP子網路上設定。由於這些是低頻寬介面、因此最佳做法是在專供管理流量使用的子網路上設定SP/BMC和e0M。

如果您無法隔離管理流量、或您的專屬管理網路異常龐大、您應該盡量將網路流量保持在最低。過多的入站廣播或多點傳送流量可能會降低SP/BMC效能。

[NOTE]
====
有些儲存控制器AFF （例如、ESIEA800）有兩個外部連接埠、一個用於BMC、另一個用於e0M。對於這些控制器、不需要在相同的IP子網路上設定BMC和e0M。

====


== 指派IP位址給服務處理器

您可以使用System Manager同時將IP位址指派給所有服務處理器、並使用這些服務處理器來監控及管理儲存系統的各種系統參數。

.步驟
. 按一下*組態*>*叢集*>*組態更新*。
. 在*服務處理器*視窗中、按一下*全域設定*。
. 在*全域設定*對話方塊中、選擇指派IP位址的來源：
+
|===
| 如果您想要... | 然後... 


 a| 
自動從DHCP伺服器指派IP位址
 a| 
選擇* DHcp*。



 a| 
從子網路指派IP位址
 a| 
選擇*子網路*。



 a| 
手動提供IP位址
 a| 
選擇*手動指派*。

|===
. 按一下「 * 儲存 * 」。




== 編輯服務處理器設定

您可以使用System Manager修改服務處理器屬性、例如IP位址、網路遮罩或字首長度、以及閘道位址。您也可以將IP位址分配給未指派任何IP位址的服務處理器。

.關於這項工作
* 您可以編輯手動指派IP位址的服務處理器設定。
* 您無法編輯透過DHCP伺服器或子網路指派IP位址的服務處理器設定。


.步驟
. 按一下*組態*>*叢集*>*服務處理器*。
. 在*服務處理器*視窗中、選取您要修改的服務處理器、然後按一下*編輯*。
. 在「*編輯服務處理器*」對話方塊中、進行必要的變更、然後按一下「*儲存並關閉*」。




== 瞭解服務處理器

服務處理器是儲存系統中與系統無關的資源、可協助您監控及管理儲存系統參數、例如溫度、電壓、電流及風扇速度。

當服務處理器偵測到任何儲存系統參數中有異常狀況時、服務處理器會記錄事件、通知ONTAP 有關問題的資訊、並AutoSupport 透過電子郵件或SNMP設陷產生不完整訊息。

服務處理器會ONTAP 透過監控機制監控資料不均、有助於快速容錯移轉至合作夥伴節點。服務處理器也會追蹤許多系統事件、並將事件儲存在記錄檔中。這些事件包括開機進度、現場可更換單元（FRU）變更、ONTAP 由故障所產生的事件、以及使用者交易記錄。

服務處理器可遠端登入及管理儲存系統、無論儲存系統的狀態為何、都能診斷、關機、關機後再開機或重新開機。此外、服務處理器也提供遠端診斷功能。

服務處理器的監控與管理功能組合、可讓您在發生問題時評估儲存系統、然後立即執行有效的服務行動。



== 服務處理器視窗

您可以使用「服務處理器」視窗來檢視及修改服務處理器屬性、例如IP位址、網路遮罩（IPv4）或字首長度（IPv6）和閘道、以及設定服務處理器的IP來源。



=== 命令按鈕

* *編輯*
+
開啟「編輯服務處理器」對話方塊、可讓您修改服務處理器的IP位址、網路遮罩（IPv4）或字首長度（IPv6）及閘道資訊。

* *全域設定*
+
開啟「全域設定」對話方塊、可讓您將所有服務處理器的IP位址來源設定為下列其中一項：DHCP、子網路或手動。

* *重新整理*
+
更新視窗中的資訊。





=== 服務處理器清單

* *節點*
+
指定服務處理器所在的節點。

* * IP位址*
+
指定服務處理器的IP位址。

* *狀態*
+
指定服務處理器的狀態、可以是線上、離線、監控程式離線、節點離線、降級、 重新開機、或不明。

* * MAC 位址 *
+
指定服務處理器的MAC位址。





=== 詳細資料區域

服務處理器清單下方的區域會顯示服務處理器的詳細資訊、包括網路詳細資料、例如IP位址、網路遮罩（IPv4）或字首長度（IPv6）、閘道、IP來源、 和MAC位址、以及一般詳細資料、例如韌體版本、以及是否啟用自動更新韌體。

*相關資訊*

xref:task_setting_up_network_when_ip_address_range_is_disabled.adoc[停用IP位址範圍時設定網路]
