---
permalink: online-help-96-97/concept_iscsi_protocol.html 
sidebar: sidebar 
keywords: iscsi, protocol, system, manager, configure, block, data, host, tcp, ip, online, help, initiate, disable, enable, dialog, box, security, authentication, default 
summary: 您可以使用System Manager來設定iSCSI傳輸協定、以便透過TCP/IP使用SCSI傳輸協定將區塊資料傳輸至主機。 
---
= 使用System Manager（ONTAP 系統管理程式）設定iSCSI傳輸協定-支援更新版本的更新版本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用ONTAP 經典版的《支援靜態系統管理程式》ONTAP （僅適用於支援更新版本的版本）來設定iSCSI傳輸協定、以便透過TCP/IP使用SCSI傳輸協定將區塊資料傳輸至主機。



== 建立iSCSI別名

iSCSI別名是您指派給iSCSI目標裝置（在此案例中為儲存系統）的使用者友好識別碼、可讓您更輕鬆地在使用者介面中識別目標裝置。您可以使用System Manager建立iSCSI別名。

.關於這項工作
iSCSI別名是1到128個可列印字元的字串。iSCSI別名不得包含空格。

.步驟
. 按一下「*儲存設備*>* SVMS*」。
. 選取SVM、然後按一下* SVM設定*。
. 在「*傳輸協定*」窗格中、按一下「* iSCSI *」。
. 在「* iSCSI *」視窗的「*服務*」索引標籤中、按一下「*編輯*」。
. 在「*編輯iSCSI服務組態*」對話方塊的「*目標別名*」欄位中輸入iSCSI別名、然後按一下「*確定*」。




== 在儲存系統介面上啟用或停用iSCSI服務

您可以啟用或停用介面、使用System Manager來控制哪些網路介面用於iSCSI通訊。啟用iSCSI服務時、iSCSI連線和要求會透過啟用iSCSI的網路介面接受、但不會透過停用的介面接受。

.開始之前
您必須終止目前使用介面的任何未完成iSCSI連線和工作階段。依預設、iSCSI服務會在您啟用iSCSI授權之後、於所有乙太網路介面上啟用。

.步驟
. 按一下「*儲存設備*>* SVMS*」。
. 選取SVM、然後按一下* SVM設定*。
. 在「*傳輸協定*」窗格中、按一下「* iSCSI *」。
. 在「* iSCSI Interfaces *」區域中、選取您要啟用或停用iSCSI服務的介面。
. 視需要按一下「*啟用*」或「*停用*」。




== 新增iSCSI啟動器的安全性方法

您可以使用System Manager新增啟動器、並指定用於驗證啟動器的安全性方法。

.步驟
. 按一下「*儲存設備*>* SVMS*」。
. 選取SVM、然後按一下* SVM設定*。
. 在「*傳輸協定*」窗格中、按一下「* iSCSI *」。
. 在「* iSCSI *」視窗中、按一下「*啟動器安全性*」索引標籤。
. 在*啟動器安全性*區域中按一下*新增*。
. 指定啟動器名稱及驗證啟動器的安全性方法。
+
對於CHAP驗證、您必須提供使用者名稱和密碼、然後確認輸入設定的密碼。對於傳出設定、此登入資訊為選用項目。

. 按一下「*確定*」。




== 編輯預設安全性設定

您可以使用System Manager中的Edit Default Security（編輯預設安全性）對話方塊、編輯連接至儲存系統之iSCSI啟動器的預設安全性設定。

.步驟
. 按一下「*儲存設備*>* SVMS*」。
. 選取SVM、然後按一下* SVM設定*。
. 在「*傳輸協定*」窗格中、按一下「* iSCSI *」。
. 在「*啟動器安全性*」標籤的「*預設安全性*」區域中、按一下「*編輯*」。
. 在*編輯預設安全性*對話方塊中、變更安全性類型。
+
對於CHAP驗證、您必須提供使用者名稱和密碼、然後確認輸入設定的密碼。對於傳出設定、此登入資訊為選用項目。

. 按一下「*確定*」。




== 變更預設的iSCSI啟動器驗證方法

您可以使用System Manager變更預設iSCSI驗證方法、這是未設定特定驗證方法的任何啟動器所使用的驗證方法。

.步驟
. 按一下「*儲存設備*>* SVMS*」。
. 選取SVM、然後按一下* SVM設定*。
. 在「*傳輸協定*」窗格中、按一下「* iSCSI *」。
. 在「*啟動器安全性*」標籤中、按一下「*預設安全性*」區域中的「*編輯*」。
. 變更安全性類型。
+
對於CHAP驗證、您必須提供使用者名稱和密碼、然後確認輸入設定的密碼。對於傳出設定、此登入資訊為選用項目。

. 按一下「*確定*」。




== 設定iSCSI啟動器的預設安全性

您可以使用System Manager移除啟動器的驗證設定、並使用預設的安全性方法來驗證啟動器。

.步驟
. 按一下「*儲存設備*>* SVMS*」。
. 選取SVM、然後按一下* SVM設定*。
. 在「*傳輸協定*」窗格中、按一下「* iSCSI *」。
. 在「*啟動器安全性*」標籤中、選取您要變更其安全性設定的啟動器。
. 在「*啟動器安全性*」區域中按一下「*設定預設*」、然後在確認對話方塊中按一下「*設定預設*」。




== 啟動或停止iSCSI服務

您可以使用System Manager來啟動或停止儲存系統上的iSCSI服務。

.步驟
. 按一下「*儲存設備*>* SVMS*」。
. 選取SVM、然後按一下* SVM設定*。
. 在「*傳輸協定*」窗格中、按一下「* iSCSI *」。
. 視需要按一下* Start*或* Stop *。




== 檢視啟動器安全性資訊

您可以使用System Manager來檢視預設驗證資訊和所有啟動器專屬的驗證資訊。

.步驟
. 按一下「*儲存設備*>* SVMS*」。
. 選取SVM、然後按一下* SVM設定*。
. 在「*傳輸協定*」窗格中、按一下「* iSCSI *」。
. 在「* iSCSI *」視窗的「*啟動器安全性*」索引標籤中、檢閱詳細資料。




== iSCSI視窗

您可以使用iSCSI視窗來啟動或停止iSCSI服務、變更儲存系統iSCSI節點名稱、以及建立或變更儲存系統的iSCSI別名。您也可以新增或變更連接至儲存系統之iSCSI啟動器的啟動器安全性設定。



=== 索引標籤

* *服務*
+
您可以使用*服務*索引標籤來啟動或停止iSCSI服務、變更儲存系統iSCSI節點名稱、以及建立或變更儲存系統的iSCSI別名。

* *啟動器安全性*
+
您可以使用「*啟動器安全性*」索引標籤來新增或變更連接至儲存系統之iSCSI啟動器的啟動器安全性設定。





=== 命令按鈕

* *編輯*
+
開啟「編輯iSCSI服務組態」對話方塊、可讓您變更儲存系統的iSCSI節點名稱和iSCSI別名。

* *開始*
+
啟動iSCSI服務。

* *停止*
+
停止iSCSI服務。

* *重新整理*
+
更新視窗中的資訊。





=== 詳細資料區域

詳細資料區域會顯示有關iSCSI服務狀態、iSCSI目標節點名稱及iSCSI目標別名的資訊。您可以使用此區域來啟用或停用網路介面上的iSCSI服務。

*相關資訊*

https://docs.netapp.com/us-en/ontap/san-admin/index.html["SAN管理"^]
