---
permalink: online-help-96-97/concept_ethernet_ports.html 
sidebar: sidebar 
keywords: system, manager, manager, ethernet, port, create, online, help, create, interface, group, lacp, vlan, settings, duplex, mode, speed, mtu, size,  port, nodes, fcp, 
summary: 您可以使用System Manager來建立及管理乙太網路連接埠。 
---
= 使用System Manager（ONTAP 系統管理程式）管理乙太網路連接埠-更新版本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用ONTAP 經典版的《經典版》（ONTAP 可在更新版本的更新版本中使用）來建立及管理乙太網路連接埠。



== 建立介面群組

您可以使用System Manager建立介面群組（單一模式、靜態多重模式或動態多重模式（LACP））、藉由結合彙總網路連接埠的功能、將單一介面呈現給用戶端。

.開始之前
可用連接埠必須不屬於任何廣播網域或介面群組、或是裝載VLAN。

.步驟
. 按一下「*網路*>*乙太網路連接埠*」。
. 按一下「*建立介面群組*」。
. 在「*建立介面群組*」對話方塊中、指定下列設定：
+
** 介面群組名稱
** 節點
** 您要納入介面群組的連接埠
** 連接埠的使用模式：單一模式、靜態多重模式或動態多重模式（LACP）
** 網路負載分配：IP型、MAC位址型、連續型或連接埠
** 必要時、介面群組的廣播網域


. 按一下「 * 建立 * 」。




== 建立VLAN介面

您可以使用System Manager建立VLAN、以維護同一個網路網域內的個別廣播網域。

.步驟
. 按一下「*網路*>*乙太網路連接埠*」。
. 單擊* Create vlan-*。
. 在「*建立VLAN*」對話方塊中、選取節點、實體介面和廣播網域（若有需要）。
+
實體介面清單僅包含乙太網路連接埠和介面群組。此清單不會顯示其他介面群組或現有VLAN中的介面。

. 輸入VLAN標記、然後按一下*「Add*（新增*）」。
+
您必須新增唯一的VLAN標記。

. 按一下「 * 建立 * 」。




== 編輯乙太網路連接埠設定

您可以使用System Manager編輯乙太網路連接埠設定、例如雙工模式和速度設定。

.步驟
. 按一下「*網路*>*乙太網路連接埠*」。
. 選取實體連接埠、然後按一下*編輯*。
. 在 * 編輯乙太網路連接埠 * 對話方塊中、將雙工模式和速度設定修改為其中之一 `manual` 或 `automatic`。
. 按一下 * 編輯 * 。




== 編輯介面群組設定

您可以使用System Manager將連接埠新增至介面群組、從介面群組移除連接埠、以及修改介面群組中連接埠的使用模式和負載分配模式。

.關於這項工作
您無法修改指派給廣播網域之介面群組的MTU設定。

.步驟
. 按一下「*網路*>*乙太網路連接埠*」。
. 選取介面群組、然後按一下*編輯*。
. 視需要修改介面群組設定、然後按一下*儲存並關閉*。




== 修改VLAN的MTU大小

如果您想要修改不屬於廣播網域的VLAN介面MTU大小、可以使用System Manager來變更大小。

.關於這項工作
您不得修改管理連接埠e0M的MTU大小。

.步驟
. 按一下「*網路*>*乙太網路連接埠*」。
. 選取您要修改的VLAN、然後按一下*編輯*。
. 在「*編輯VLAN*」對話方塊中、視需要修改MTU大小、然後按一下「*儲存*」。




== 刪除VLAN

您可以使用System Manager刪除網路連接埠上設定的VLAN。從插槽中移除NIC之前、您可能必須先刪除VLAN。刪除VLAN時、VLAN會自動從所有使用VLAN的容錯移轉規則和群組中移除。

.開始之前
任何生命都不需要與VLAN相關聯。

.步驟
. 按一下「*網路*>*乙太網路連接埠*」。
. 選取您要刪除的VLAN、然後按一下*刪除*。
. 選取確認核取方塊、然後按一下*刪除*。




== 連接埠與介面卡

連接埠會群組在節點下、節點會根據所選的傳輸協定類別顯示。例如、如果使用FC傳輸協定來處理資料、則只會顯示具有FCP介面卡的節點。託管介面數可協助您選擇負載較少的連接埠。

*相關資訊*

https://docs.netapp.com/us-en/ontap/networking/index.html["網路管理"]

https://docs.netapp.com/us-en/ontap/concepts/index.html["概念ONTAP"]

xref:reference_network_window.adoc[網路視窗]
