---
permalink: online-help-96-97/concept_what_nvme_subsystem_is.html 
sidebar: sidebar 
keywords: nvme, subsystem, fc, rdma, transport, port, vserver, online, help, controller, cluster, table, settings, manage 
summary: NVMe子系統包含一個或多個控制器、一個或多個命名空間、一個或多個非揮發性記憶體（NVM）子系統連接埠（FC-NVMe或RDMA傳輸連接埠）、NVM儲存媒體、以及控制器與NVM儲存媒體之間的介面。對於控制器對應和管理、NVM子系統會對應ONTAP 至位於整個過程的Vserver。 
---
= 使用System Manager（ONTAP 系統管理程式）管理NVMe子系統-支援更新版本9.7
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用ONTAP 經典版的《經典版》（ONTAP 僅適用於《支援》9.7及更早版本）來建立及管理NVMe子系統。您可以將NVMe子系統與Vserver中的不同主機和命名空間建立關聯。此外、每個Vserver也可支援多個NVMe子系統。不過、您無法將NVMe子系統設定為在多個Vserver上使用。



== 建立NVMe子系統

您可以使用System Manager建立NVMe子系統。

.步驟
. 按一下「* NVMe SubSystems*」視窗中的「* Create *」（建立*）。
. 在「* NVMe子系統：cre產生*」視窗中提供下列欄位的項目：
+
** * SVM*
+
從下拉式功能表中、選取您要在其中建立子系統的SVM。

** *名稱*
+
輸入子系統的名稱。SVM中無法存在子系統名稱。名稱區分大小寫、最多96個字元。允許使用特殊字元。

** *主機作業系統*
+
從下拉式功能表中、選取子系統的主機作業系統類型。

** * 主機 NQN*
+
輸入連接至控制器的主機NQN。您可以輸入多個主機NQN、方法是以逗號分隔。



. 按一下「 * 儲存 * 」。
+
隨即建立NVMe子系統、並顯示NVMe SubsystemsWindow。





== 編輯NVMe子系統詳細資料

您可以使用System Manager編輯NVMe子系統的詳細資料。

.步驟
. 在* NVMe Subsystem*視窗中尋找您要編輯的NVMe子系統。
. 核取您要編輯之子系統名稱左側的方塊。
. 按一下 * 編輯 * 。
+
NVMe子系統的目前詳細資料會顯示在NVMe子系統：編輯視窗中。

. 您只能修改*主機NQN*欄位中的資訊。
+
** * 主機 NQN*
+
修改附加至控制器的主機NQN。您可以輸入多個主機NQN、方法是以逗號分隔。



+
「主機NQN」欄位下方會顯示*相關的NVMe命名空間*表格。對於每個命名空間、該表會列出命名空間路徑和命名空間ID。

. 按一下「 * 儲存 * 」。
+
NVMe子系統詳細資料隨即更新、並顯示NVMe子系統視窗。





== 刪除NVMe子系統

您可以使用System Manager從叢集刪除NVMe子系統。

.關於這項工作
刪除NVMe子系統時會發生下列動作：

* 如果NVMe子系統已設定主機、則會移除對應的主機。
* 如果NVMe子系統已對應命名空間、則會取消對應。


.步驟
. 在* NVMe Subsystem*視窗中尋找您要刪除的NVMe子系統。
. 核取您要刪除之子系統名稱左側的方塊。
. 按一下*刪除*。
+
此時會顯示一則警告訊息。

. 按一下「*刪除NVMe Subsystem*」核取方塊以確認刪除、然後按一下「*是*」。
+
NVMe子系統會從叢集中刪除、並顯示NVMe子系統視窗。





== NVMe子系統視窗

NVMe子系統視窗預設會顯示叢集中NVMe子系統的詳細目錄清單。您可以篩選清單、只顯示SVM專屬的子系統。此視窗也可讓您建立、編輯或刪除NVMe子系統。您可以選取*儲存設備*>* NVMe *>*子系統*來存取此視窗。

* <<NVMe子系統表>>
* <<工具列>>




=== NVMe子系統表

NVMe子系統表列出叢集中NVMe子系統的詳細目錄。您可以使用「* SVM*」欄位中的下拉式功能表來精簡清單、以選取SVM、僅顯示與該SVM相關的NVMe子系統。「*搜尋*」欄位和「*篩選*」下拉式功能表可讓您進一步自訂清單。

NVMe子系統表包含下列欄位：

* *（核取方塊）*
+
可讓您指定要執行動作的子系統。

+
按一下核取方塊以選取子系統、然後按一下您要執行之工具列中的動作。

* *名稱*
+
顯示子系統的名稱。

+
您可以在*搜尋*欄位中輸入子系統名稱、以搜尋子系統。

* *主機作業系統*
+
顯示與子系統相關聯的主機作業系統名稱。

* * 主機 NQN*
+
顯示連接至控制器的NVMe合格名稱（NQN）。如果顯示多個NQN、則會以逗號分隔。

* *相關的NVMe命名空間*
+
顯示與子系統相關聯的NVM命名空間數目。您可以將游標暫留在數字上、以顯示相關聯的命名空間路徑。按一下路徑以顯示「命名空間詳細資料」視窗。





=== 工具列

工具列位於欄標題上方。您可以使用工具列中的欄位和按鈕來執行各種動作。

* *搜尋*
+
可讓您搜尋在*名稱*欄中可能找到的值。

* *篩選*
+
可讓您從下拉式功能表中選取、其中會列出各種篩選清單的方法。

* *建立*
+
開啟「Create NVMe Subsystem（建立NVMe子系統）」對話方塊、可讓您建立NVMe子系統。

* *編輯*
+
開啟「編輯NVMe子系統」對話方塊、可讓您編輯現有的NVMe子系統。

* *刪除*
+
開啟「刪除NVMe子系統」確認對話方塊、可讓您刪除現有的NVMe子系統。


