---
permalink: online-help-96-97/concept_aggregates.html 
sidebar: sidebar 
keywords: aggregates, system, manager, security, backup, performance, data, sharing, classic, online, help, window 
summary: 您可以使用System Manager建立Aggregate、以支援使用者不同的安全性、備份、效能和資料共用需求。 
---
= 使用System Manager管理集合體- ONTAP 更新版本
:allow-uri-read: 


您可以使用ONTAP 經典版的《支援功能》（ONTAP 適用於支援功能更新版本的版本）來建立Aggregate、以支援使用者不同的安全性、備份、效能和資料共享需求。



== Aggregate視窗

您可以使用Aggregate視窗來建立、顯示及管理有關Aggregate的資訊。



=== 命令按鈕

* *建立*
+
開啟「建立Aggregate」對話方塊、可讓您建立Aggregate。

* *編輯*
+
開啟「編輯Aggregate」對話方塊、可讓您變更要為Aggregate提供的Aggregate名稱或RAID保護層級。

* *刪除*
+
刪除選取的Aggregate。

+
[NOTE]
====
根Aggregate會停用此按鈕。

====
* *更多行動*
+
提供下列選項：

* *將狀態變更為*
+
將所選Aggregate的狀態變更為下列其中一種狀態：

+
** 線上
+
允許對此Aggregate中包含的磁碟區進行讀寫存取。

** 離線
+
不允許讀寫存取。

** 限制
+
允許執行某些作業、例如同位元檢查重建、但不允許存取資料。



* *新增容量*
+
可讓您將容量（HDD或SSD）新增至現有的集合體。

* *新增快取*
+
可讓您將快取磁碟（SSD）新增至現有的HDD集合體或Flash Pool Aggregate。

+
此按鈕不適用於包含具有All Flash Optimized特性設定之節點的叢集。

* *鏡射*
+
可讓您鏡射集合體。

* * Volume mov移動*
+
可讓您移動FlexVol 一個聲音量。

* *附加雲端層*
+
可讓您將雲端層附加至Aggregate。

* *重新整理*
+
更新視窗中的資訊。





=== Aggregate清單

顯示每個Aggregate的名稱和空間使用資訊。

* *狀態*
+
顯示Aggregate的狀態。

* *名稱*
+
顯示Aggregate的名稱。

* *節點*
+
顯示指派集合體磁碟的節點名稱。

+
此欄位僅適用於叢集層級。

* *類型*
+
顯示集合體的類型。

+
此欄位不會針對包含節點的叢集顯示、且其特性設定為All Flash Optimized（最佳化所有Flash）。

* *已用（%）*
+
顯示集合體中使用的空間百分比。

* *可用空間*
+
顯示集合體中的可用空間。

* *已用空間*
+
顯示用於集合體中資料的空間量。

* *總空間*
+
顯示集合體的總空間。

* *《*》FabricPool
+
顯示所選的Aggregate是否附加至雲端層。

* *雲端層*
+
如果選取的Aggregate附加至雲端層、則會顯示雲端層的名稱。

* * Volume Count*
+
顯示與Aggregate相關聯的磁碟區數目。

* *磁碟數*
+
顯示用於建立集合體的磁碟數目。

* * Flash Pool *
+
顯示Flash Pool Aggregate的總快取大小。值NA表示該Aggregate不是Flash Pool Aggregate。

+
此欄位不會針對包含節點的叢集顯示、且其特性設定為All Flash Optimized（最佳化所有Flash）。

* *鏡射*
+
顯示是否鏡射Aggregate。

* *《類型*》SnapLock
+
顯示SnapLock Aggregate的邊型。





=== 詳細資料區域

選取Aggregate以檢視所選Aggregate的相關資訊。您可以按一下「顯示更多詳細資料」來檢視所選Aggregate的詳細資訊。

* *總覽選項卡*
+
顯示所選Aggregate的詳細資訊、並顯示集合體空間分配、集合體空間節約量、以及集合體IOPS效能和資料傳輸總數的圖示。

* *磁碟資訊索引標籤*
+
顯示磁碟配置資訊、例如磁碟名稱、磁碟類型、實體大小、可用大小、磁碟位置、 磁碟狀態、叢集名稱、叢集狀態、RAID群組、RAID類型、 和儲存資源池（如果有）。也會顯示與磁碟主要路徑相關聯的磁碟連接埠、以及具有多重路徑組態之磁碟次要路徑的磁碟名稱。

* * Volume索引標籤*
+
顯示有關集合體上磁碟區總數、總集合體空間和已認可至集合體空間的詳細資料。

* *效能索引標籤*
+
顯示圖表、顯示集合體的效能指標、包括處理量和IOPS。系統會針對處理量和IOPS顯示讀取、寫入和總傳輸量的效能指標資料、SSD和HDD的資料則會分別記錄。

+
變更用戶端時區或叢集時區會影響效能度量圖。您應該重新整理瀏覽器以檢視更新的圖表。



*相關資訊*

xref:task_provisioning_storage_through_aggregates.adoc[透過Aggregate配置儲存設備]

xref:task_deleting_aggregates.adoc[刪除Aggregate]

xref:task_editing_aggregates.adoc[編輯Aggregate]
