---
permalink: online-help-96-97/concept_kerberos_interface_services.html 
sidebar: sidebar 
keywords: kerberos, interface, service, system, manager, manage, online, help, edit, configuration, buttons, command, window 
summary: 您可以使用System Manager來管理Kerberos介面服務。 
---
= 使用System Manager管理Kerberos介面服務- ONTAP 支援更新版本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用ONTAP 經典版的《支援支援經典的功能》（ONTAP 僅適用於支援更新版本的版本）來管理Kerberos介面服務。



== 編輯Kerberos組態

您可以使用System Manager來啟用Kerberos、並編輯與儲存虛擬機器（SVM）相關聯的Kerberos組態、讓SVM能夠使用適用於NFS的Kerberos安全服務。

.開始之前
* 您必須至少在SVM層級設定一個Kerberos領域。
* SVM上至少必須有兩個資料生命期。
+
服務主要名稱（SPN-）使用一個資料LIF來處理UNIX和CIFS相關的Kerberos流量。其他資料LIF用於存取非Kerberos流量。

+
[NOTE]
====
基本NFS Kerberos存取不需要CIFS伺服器。若要進行多重傳輸協定存取、或是將Active Directory當作LDAP伺服器來進行名稱對應、則需要CIFS伺服器。

====


.關於這項工作
如果您使用Microsoft Active Directory Kerberos、則網域中使用的任何SPN前15個字元必須是唯一的。Microsoft Active Directory最多可限制15個字元的SPN、而且不允許重複的SPN。

.步驟
. 按一下「*儲存設備*>* SVMS*」。
. 選取SVM、然後按一下* SVM設定*。
. 在*服務*窗格中、按一下* Kerberos介面*。
. 在「* Kerberos介面*」視窗中、選取介面、然後按一下「*編輯*」。
. 在「*編輯Kerberos組態*」對話方塊中、進行必要的變更、然後按一下「*確定*」。




== Kerberos介面視窗

您可以使用Kerberos介面視窗來啟用Kerberos、以及編輯儲存虛擬機器（SVM）的Kerberos組態。



=== 命令按鈕

* *編輯*
+
開啟「編輯Kerberos組態」對話方塊、您可以使用此對話方塊來啟用Kerberos並編輯與SVM相關的Kerberos組態。

* *重新整理*
+
更新視窗中的資訊。





=== Kerberos介面清單

提供Kerberos組態的詳細資料。

* *介面名稱*
+
指定與SVM的Kerberos組態相關聯的邏輯介面。

* *服務主要名稱*
+
指定符合Kerberos組態的服務主要名稱（SPN-）。

* *領域*
+
指定與Kerberos組態相關聯的Kerberos領域名稱。

* * Kerberos狀態*
+
指定是否啟用Kerberos。



*相關資訊*

link:https://www.netapp.com/pdf.html?item=/media/10720-tr-4067.pdf["NetApp技術報告4067：NetApp ONTAP 的NFS功能"^]

link:https://www.netapp.com/pdf.html?item=/media/19384-tr-4616.pdf["NetApp技術報告4616：ONTAP NFS Kerberos in Some with Microsoft Active Directory"^]

link:https://www.netapp.com/pdf.html?item=/media/19423-tr-4835.pdf["NetApp技術報告4835：如何在ONTAP 功能方面設定LDAP"^]
