---
permalink: online-help-96-97/concept_efficiency_policies.html 
sidebar: sidebar 
keywords: efficiency, policy, system, manager, create, edit, delete, online, help, flexvol, window 
summary: 您可以使用System Manager來建立、編輯及刪除效率原則。 
---
= 利用System Manager管理效率政策- ONTAP 不含更新版本的更新版本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用ONTAP 經典版的《經典版》（ONTAP 僅適用於更新版本的版本）來建立、編輯及刪除效率原則。



== 新增效率原則

您可以使用System Manager新增效率原則、以便在指定排程的磁碟區上執行重複資料刪除作業、或是當磁碟區資料變更達到指定臨界值時執行重複資料刪除作業。

.步驟
. 按一下「*儲存設備*>* SVMS*」。
. 選取SVM、然後按一下* SVM設定*。
. 在「*原則*」窗格中、按一下「*效率原則*」。
. 按一下「*新增*」、然後指定原則名稱。
. 指定應如何執行儲存效率原則：
+
** 選取*排程*、然後指定排程名稱和排程詳細資料。
+
如有需要、您可以指定效率原則的最長執行時間長度。

** 選取*變更記錄臨界值*、然後指定磁碟區資料變更的臨界值（以百分比表示）。


. *選用：*選取*將QoS原則設為背景*核取方塊、以降低對用戶端作業的效能影響。
. 按一下「 * 新增 * 」。




== 編輯效率原則

您可以使用System Manager來修改效率原則的屬性、例如原則名稱、排程名稱和最大執行時間。

.步驟
. 按一下「*儲存設備*>* SVMS*」。
. 選取SVM、然後按一下* SVM設定*。
. 在「*原則*」窗格中、按一下「*效率原則*」。
. 在*效率原則*視窗中、選取您要編輯的原則、然後按一下*編輯*。
. 在「*編輯效率原則*」對話方塊中、進行必要的變更。
. 按一下「 * 儲存 * 」。




== 刪除效率原則

您可以使用System Managerto刪除不再需要的效率原則。

.開始之前
必須停用效率原則。

.步驟
. 按一下「*儲存設備*>* SVMS*」。
. 選取SVM、然後按一下* SVM設定*。
. 在「*原則*」窗格中、按一下「*效率原則*」。
. 選取您要刪除的效率原則、然後按一下*刪除*。
. 選取確認核取方塊、然後按一下*刪除*。




== 啟用或停用效率原則

您可以使用System Manager來啟用或停用效率原則。

.步驟
. 按一下「*儲存設備*>* SVMS*」。
. 選取SVM、然後按一下* SVM設定*。
. 在「*原則*」窗格中、按一下「*效率原則*」。
. 選取一或多個您要啟用或停用的效率原則。
. 視需要按一下*狀態*>*啟用*或*狀態*>*停用*。
. 如果您要停用效率原則、請選取確認核取方塊、然後按一下*確定*。




== 什麼是效率原則

效率原則是FlexVol 指在一個穩定磁碟區上執行重複資料刪除作業的工作排程。

您可以FlexVol 排程在特定時間開始執行重複資料刪除、或是指定在超過臨界值百分比時觸發作業。您可以建立包含在效率原則中的工作排程、來排程重複資料刪除作業。Volume效率原則僅支援cron類型的工作排程。或者、您也可以指定臨界值百分比。當新資料超過指定的百分比時、重複資料刪除作業就會啟動。



== 瞭解預先定義的效率原則

您可以使用效率原則設定磁碟區、以達到額外的空間節約效益。您可以將磁碟區設定為執行即時壓縮、而無需在磁碟區上設定排程或手動啟動背景效率作業。

當您建立SVM時、系統會自動建立下列效率原則、而且無法刪除：

* 預設
+
您可以使用效率原則設定磁碟區、以便在磁碟區上執行排程的重複資料刪除作業。

* 純內嵌
+
您可以使用純內嵌效率原則來設定磁碟區、並啟用即時壓縮功能、在磁碟區上執行即時壓縮、而不需執行任何排程或手動啟動的背景效率作業。



如需有關純內嵌和預設效率原則的詳細資訊、請參閱手冊頁。



== 效率原則視窗

您可以使用效率原則視窗來建立、顯示及管理效率原則的相關資訊。



=== 命令按鈕

* *新增*
+
開啟「Add Effency Policy（新增效率原則）」對話方塊、可讓您在磁碟區上執行重複資料刪除作業、持續一段指定的時間（根據排程）、或是當磁碟區資料的變更達到指定的臨界值（以臨界值為基礎）時執行重複資料刪除作業。

* *編輯*
+
開啟「編輯效率原則」對話方塊、可讓您修改重複資料刪除作業的排程、臨界值、QoS類型及最長執行時間。

* *刪除*
+
開啟「刪除效率原則」對話方塊、可讓您刪除所選的效率原則。

* *狀態*
+
開啟下拉式功能表、提供啟用或停用所選效率原則的選項。

* *重新整理*
+
更新視窗中的資訊。





=== 效率原則清單

* *自動*
+
指定在背景中持續執行重複資料刪除。此原則適用於所有新建立的磁碟區、以及尚未手動設定為背景重複資料刪除的所有升級磁碟區。如果您將原則變更為「預設」或任何其他原則、「自動」原則就會停用。

+
如果磁碟區從非AFF系統移至AFF 某個支援系統、預設會在目的地節點上啟用「自動」原則。如果磁碟區從AFF 一個支援節點移至非AFF節點、則目的地節點上的「自動」原則預設會被「僅限內嵌」原則取代。

* *政策*
+
指定效率原則的名稱。

* *狀態*
+
指定效率原則的狀態。狀態可以是下列其中一項：

+
** 已啟用
+
指定可將效率原則指派給重複資料刪除作業。

** 已停用
+
指定效率原則已停用。您可以使用狀態下拉式功能表來啟用原則、稍後再指派給重複資料刪除作業。



* *執行者*
+
指定是根據排程執行儲存效率原則、還是根據臨界值（變更記錄臨界值）執行。

* * QoS原則*
+
指定儲存效率原則的QoS類型。QoS類型可以是下列其中一種：

+
** 背景
+
指定QoS原則在背景執行、如此可降低對用戶端作業的潛在效能影響。

** 盡最大努力
+
指定QoS原則是以最佳方式執行、可讓您將系統資源的使用率最大化。



* *最大執行時間*
+
指定效率原則的最長執行時間長度。如果未指定此值、則會執行效率原則、直到作業完成為止。





=== 詳細資料區域

效率原則清單下方的區域會顯示所選效率原則的其他資訊、包括排程原則的排程名稱和排程詳細資料、以及臨界值型原則的臨界值。
