---
permalink: online-help-96-97/concept_svm_user_accounts.html 
sidebar: sidebar 
keywords: system, manager, create, manage, online, help, storage, virtual, machine, svm, user, account, password, change, lock, unlock , command, button 
summary: 您可以使用System Manager來建立及管理儲存虛擬機器（SVM）使用者帳戶。 
---
= 使用System Manager（ONTAP 系統管理程式）建立及管理SVM使用者帳戶-更新版本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用ONTAP 經典版的《經典版》（ONTAP 僅適用於更新版本的版本）來建立及管理儲存虛擬機器（SVM）使用者帳戶。



== 新增SVM使用者帳戶

您可以使用System Manager新增儲存虛擬機器（SVM）使用者帳戶、並指定使用者登入方法來存取儲存系統。

.步驟
. 按一下「*儲存設備*>* SVMS*」。
. 選取SVM、然後按一下* SVM設定*。
. 在「* SVM使用者詳細資料*」窗格中、按一下「*使用者*」。
. 按一下「 * 新增 * 」。
. 指定用於連線至儲存系統的使用者名稱和密碼、並確認密碼。
. 新增一或多種使用者登入方法、然後按一下*「Add*（新增*）」。
+
新vsadmin帳戶的登入方法會自動包含在內、使用HTTP做為應用程式、並以憑證進行驗證。





== 變更SVM使用者帳戶的密碼

您可以使用System Manager重設儲存虛擬機器（SVM）使用者帳戶的密碼。

.步驟
. 按一下「*儲存設備*>* SVMS*」。
. 選取SVM、然後按一下* SVM設定*。
. 在「* SVM使用者詳細資料*」窗格中、按一下「*使用者*」。
. 選取您要修改密碼的使用者帳戶、然後按一下*重設密碼*。
. 在*重設密碼*對話方塊中、輸入新密碼、確認新密碼、然後按一下*變更*。




== 編輯SVM使用者帳戶

您可以使用System Manager修改存取儲存系統的使用者登入方法、以編輯儲存虛擬機器（SVM）使用者帳戶。

.步驟
. 按一下「*儲存設備*>* SVMS*」。
. 選取SVM、然後按一下* SVM設定*。
. 在「* SVM使用者詳細資料*」窗格中、按一下「*使用者*」。
. 選取您要編輯的使用者帳戶、然後按一下*編輯*。
. 修改一或多個使用者登入方法、然後按一下*修改*。




== 鎖定或解除鎖定SVM使用者帳戶

您可以使用System Manager鎖定或解除鎖定儲存虛擬機器（SVM）使用者帳戶。

.步驟
. 按一下「*儲存設備*>* SVMS*」。
. 選取SVM、然後按一下* SVM設定*。
. 在「* SVM使用者詳細資料*」窗格中、按一下「*使用者*」。
. 在「*使用者*」視窗中、選取您要修改其帳戶狀態的使用者帳戶、然後視需要按一下「*鎖定*」或「*解除鎖定*」。




== 使用者視窗

您可以使用「使用者」視窗來管理使用者帳戶、重設使用者密碼、以及檢視所有使用者帳戶的相關資訊。



=== 命令按鈕

* *新增*
+
開啟「新增使用者」對話方塊、可讓您新增使用者帳戶。

* *編輯*
+
開啟「修改使用者」對話方塊、可讓您修改使用者登入方法。

+
[NOTE]
====
最佳做法是針對使用者帳戶的所有存取和驗證方法、使用單一角色。

====
* *刪除*
+
可讓您刪除選取的使用者帳戶。

* *變更密碼*
+
開啟變更密碼對話方塊、可讓您重設選取的使用者密碼。

* *鎖定*
+
鎖定使用者帳戶。

* *重新整理*
+
更新視窗中的資訊。





=== 使用者清單

使用者清單下方的區域會顯示所選使用者的詳細資訊。

* *使用者*
+
顯示使用者帳戶的名稱。

* *帳戶已鎖定*
+
顯示使用者帳戶是否已鎖定。





=== 使用者登入方法區域

* *應用*
+
顯示使用者可用來存取儲存系統的存取方法。支援的存取方法包括：

+
** 系統主控台（主控台）
** HTTP（S）（http）
** API（ontapi）ONTAP
** 服務處理器（服務處理器）
** SSH（ssh）


* *驗證*
+
顯示預設支援的驗證方法、即「密碼」。

* *角色*
+
顯示所選使用者的角色。


