---
permalink: online-help-96-97/concept_system_alerts.html 
sidebar: sidebar 
keywords: system, manager, monitor, cluster, health, alerts, delete, 
summary: 您可以使用System Manager來監控叢集的不同部分。 
---
= 使用ONTAP System Manager（系統管理程式）管理系統警示- NetApp 9.7及更早版本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用ONTAP 經典版的《經典版》（ONTAP 僅適用於更新版本的版本）來監控叢集的不同部分。



== 確認系統健全狀況警示

您可以使用System Manager來確認及回應子系統的系統健全狀況警示。您可以使用顯示的資訊來採取建議的行動、並修正警示所回報的問題。

.步驟
. 按一下*事件與工作*>*系統警示*。
. 在*系統警示*視窗中、按一下子系統名稱旁的箭頭圖示。
. 選取您要確認的警示、然後按一下*「Acknowledge」（確認）*。
. 輸入您的姓名、然後按一下*「Acknowledge」（確認）。




== 抑制系統健全狀況警示

您可以使用System Manager來抑制不需要您介入的系統健全狀況警示。

.步驟
. 按一下*事件與工作*>*系統警示*。
. 在*系統警示*視窗中、按一下子系統名稱旁的箭頭圖示。
. 選取您要隱藏的警示、然後按一下* Suppress*。
. 輸入您的名稱、然後按一下* Sup抑制*。




== 刪除系統健全狀況警示

您可以使用System Manager刪除已回應的系統健全狀況警示。

.步驟
. 按一下*事件與工作*>*系統警示*。
. 在*系統警示*視窗中、按一下子系統名稱旁的箭頭圖示。
. 選取您要刪除的警示、然後按一下*刪除*。
. 按一下「*確定*」。




== 可用的叢集健全狀況監視器

有多個健全狀況監視器可監控叢集的不同部分。健全狀況監視器可ONTAP 偵測事件、傳送警示給您、並在清除事件時刪除事件、協助您從錯誤中恢復。

[cols="1a,1a,1a"]
|===
| 健全狀況監視器名稱（識別碼） | 子系統名稱（識別碼） | 目的 


 a| 
叢集交換器（叢集交換器）
 a| 
交換器（交換器健全狀況）
 a| 
監控叢集網路交換器和管理網路交換器的溫度、使用率、介面組態、備援（僅限叢集網路交換器）、以及風扇和電源供應器作業。叢集交換器健全狀況監視器透過SNMP與交換器通訊。預設設定為：SNMPv2c。

[NOTE]
====
從ONTAP 功能表9.2開始、此監視器可偵測並報告叢集交換器自上次輪詢期間後重新開機的時間。

====


 a| 
支援的架構MetroCluster
 a| 
交換器
 a| 
監控MetroCluster 支援此功能的後端架構拓撲、並偵測錯誤的組態、例如不正確的佈線和分區、以及ISL故障。



 a| 
系統健全狀況MetroCluster
 a| 
互連、RAID和儲存設備
 a| 
監控FC-VI介面卡、FC啟動器介面卡、左後集合體和磁碟、以及叢集間連接埠



 a| 
節點連線（節點連線）
 a| 
CIFS不中斷營運（CIF-NDO）
 a| 
監控SMB連線、以確保不中斷營運至Hyper-V應用程式。



 a| 
儲存設備（SAS連線）
 a| 
在節點層級監控磁碟櫃、磁碟和介面卡、以取得適當的路徑和連線。



 a| 
系統
 a| 
不適用
 a| 
彙總來自其他健全狀況監視器的資訊。



 a| 
系統連線（系統連線）
 a| 
儲存設備（SAS連線）
 a| 
監控叢集層級的磁碟櫃、以取得通往兩個HA叢集節點的適當路徑。

|===


== 回應系統健全狀況警示的方法

當系統健全狀況警示發生時、您可以確認該警示、深入瞭解該警示、修復基礎狀況、並防止其再次發生。

當健全狀況監視器發出警示時、您可以使用下列任一方式回應：

* 取得警示的相關資訊、包括受影響的資源、警示嚴重性、可能原因、可能影響及修正行動。
* 取得警示的詳細資訊、例如警示發出時間、以及是否有其他人已確認警示。
* 取得受影響資源或子系統狀態的相關健全狀況資訊、例如特定機櫃或磁碟。
* 確認警示、指出有人正在處理此問題、並將自己識別為「Acknowledger」。
* 請採取警示中提供的修正行動來解決問題、例如修正纜線以解決連線問題。
* 如果系統未自動清除警示、請刪除警示。
* 隱藏警示、以防止其影響子系統的健全狀況狀態。
+
當您瞭解問題時、隱藏功能非常實用。隱藏警示之後、仍可能發生、但當發生抑制警示時、子系統健全狀況會顯示為「ok、with -suppressed」（「ok、with -suppressed」）。





== 系統警示視窗

您可以使用「系統警示」視窗來深入瞭解系統健全狀況警示。您也可以從視窗中確認、刪除及隱藏警示。



=== 命令按鈕

* *認知*
+
可讓您確認選取的警示、指出問題正在解決、並將按下按鈕的人員識別為「「Acknowledger」（感謝）。

* *抑制*
+
可讓您隱藏選取的警示、以防止系統再次通知您相同的警示、並將您識別為「保護程式」。

* *刪除*
+
刪除選取的警示。

* *重新整理*
+
更新視窗中的資訊。





=== 警示清單

* *子系統（編號警示）*
+
顯示子系統的名稱、例如產生MetroCluster 警示的SAS連線、交換器健全狀況、CIFS n或Sname。

* *警示ID*
+
顯示警示ID。

* *節點*
+
顯示產生警示的節點名稱。

* *嚴重性*
+
顯示警示的嚴重性為「未知」、「其他」、「資訊」、「降級」、「次要」、 重大、重大或致命。

* *資源*
+
顯示產生警示的資源、例如特定機櫃或磁碟。

* *時間*
+
顯示產生警示的時間。





=== 詳細資料區域

詳細資料區域會顯示警示的詳細資訊、例如警示產生時間、以及警示是否已被確認。此區域也包含警示所產生條件的可能原因和可能影響、以及修正警示所報告問題的建議行動。

*相關資訊*

https://docs.netapp.com/us-en/ontap/system-admin/index.html["系統管理"]
