---
permalink: online-help-96-97/concept_array_luns.html 
sidebar: sidebar 
keywords: system, manager, array, lun, aggregate, assign, online, help, classic 
summary: 您可以使用System Manager將陣列LUN指派給現有的Aggregate、並管理陣列LUN。 
---
= 使用System Manager（ONTAP 系統管理程式）來管理陣列LUN -更新版本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用ONTAP 經典版的《經典版》（ONTAP 適用於更新版本的版本）來指派陣列LUN給現有的Aggregate、並管理陣列LUN。



== 指派陣列LUN

您可以使用System Manager將未指派的陣列LUN指派給現有的Aggregate、以增加Aggregate的大小。

.關於這項工作
* 如果符合下列條件、您可以指派陣列LUN：
+
** 所選陣列LUN的容器類型必須為「'未 指派'」。
** 磁碟必須連接至HA配對中的節點。
** 節點必須能夠看到磁碟。


* 對於零件組態、您無法使用System Manager將陣列LUN指派為備用磁碟。MetroCluster
+
您必須改用命令列介面。



.步驟
. 按一下「*儲存設備*>*集合體與磁碟*>*陣列LUN*」。
. 選取陣列LUN、然後按一下*指派*。
. 在「*指派陣列LUN*」對話方塊中、選取您要指派陣列LUN的節點。
. 按一下*指派*。




== 將備用陣列LUN重新指派給節點

您可以使用System Manager將備用陣列LUN的擁有權從一個節點重新指派給另一個節點、以增加集合體的容量。

.關於這項工作
* 如果滿足下列條件、您可以重新指派陣列LUN：
+
** 所選陣列LUN的容器類型必須是「pare」。
** 磁碟必須連接至HA配對中的節點。
** 節點必須能夠看到磁碟。


* 對於零件組態、您無法使用System Manager將陣列LUN重新指派為備用磁碟。MetroCluster
+
您必須改用命令列介面。



.步驟
. 按一下「*儲存設備*>*集合體與磁碟*>*陣列LUN*」。
. 選取您要重新指派的備用陣列LUN、然後按一下*指派*。
. 在*警告*對話方塊中、按一下*繼續*。
. 在「*指派陣列LUN*」對話方塊中、選取您要重新指派備用陣列LUN的節點。
. 按一下*指派*。




== 將備用陣列LUN歸零

您可以使用System Manager清除所有資料、並將零寫入陣列LUN、以格式化備用陣列LUN。這些陣列LUN隨後可用於新的集合體。

.關於這項工作
當您將備用陣列LUN歸零時、叢集中的所有備援磁碟（包括磁碟）都會歸零。您可以將特定節點或整個叢集的備用陣列LUN歸零。

.步驟
. 按一下「*儲存設備*>*集合體與磁碟*>*陣列LUN*」。
. 按一下「*零備援*」。
. 在「*零備用磁碟*」對話方塊中、選取要歸零陣列LUN的節點或「所有節點」。
. 選取「將所有非零零備援*歸零」核取方塊、以確認零位作業。
. 按一下「*零備援*」。




== 關於磁碟和陣列LUN

磁碟是儲存系統的基本儲存單元、這些儲存系統使用ONTAP NetApp軟體來存取原生磁碟櫃。陣列LUN是第三方儲存陣列提供給執行ONTAP 此軟體的儲存系統的基本儲存單元。

利用支援的支援、您可以為磁碟和陣列LUN指派擁有權、並將其新增至集合體。ONTAP此外、支援支援各種方法來管理磁碟、包括移除磁碟、更換磁碟、以及消毒磁碟。ONTAP由於陣列LUN由協力廠商儲存陣列提供、因此您可以使用協力廠商儲存陣列來執行陣列LUN的所有其他管理工作。

您可以使用磁碟或陣列LUN來建立Aggregate。建立Aggregate之後、無論ONTAP 是從磁碟或陣列LUN建立、您都可以使用完全相同的方式來管理它。



== Array LUN（陣列LUN）窗口

Array LUN（陣列LUN）視窗可讓您將擁有權指派給陣列LUN、並將其新增至集合體。

僅當有任何備用陣列LUN、或安裝了V_StorageAttach授權時、左側導覽窗格中的Array LUN連結才會顯示。



=== 命令按鈕

* *指派*
+
可讓您將陣列LUN的擁有權指派或重新指派給節點。

* *零備援*
+
清除所有資料、並格式化備用陣列LUN和磁碟。

* *重新整理*
+
更新視窗中的資訊。





=== Array LUN清單

顯示每個陣列LUN的名稱、狀態和廠商等資訊。

* *名稱*
+
指定陣列LUN的名稱。

* *州*
+
指定陣列LUN的狀態。

* *廠商*
+
指定廠商名稱。

* *已用空間*
+
指定陣列LUN使用的空間。

* *總大小*
+
指定陣列LUN的大小。

* * Container *
+
指定陣列LUN所屬的Aggregate。

* *節點名稱*
+
指定陣列LUN所屬的節點名稱。

* *擁有者*
+
顯示指派陣列LUN的主節點名稱。

* *目前擁有者*
+
顯示目前擁有陣列LUN的節點名稱。

* *陣列名稱*
+
指定陣列名稱。

* *資源池*
+
顯示已指派所選陣列LUN的集區名稱。





=== 詳細資料區域

Array LUN清單下方的區域會顯示所選陣列LUN的詳細資訊。

*相關資訊*

https://docs.netapp.com/ontap-9/topic/com.netapp.doc.vs-irrg/home.html["介紹虛擬化安裝需求與參考資料FlexArray"]
