---
permalink: online-help-96-97/concept_cluster_peers.html 
sidebar: sidebar 
keywords: cluster, peer, data, replication, snapmirror, snapvault, flexcache, syncmirror, configuration, system, manager, modify, passphrase, lif, configure, remote, change, encryption, status, online, help 
summary: 使用SnapMirror技術和SnapVault SnapMirror技術進行資料複寫時、需要使用對等叢集、FlexCache 而使用支援SyncMirror 各種功能的支援功能、則MetroCluster 需要使用支援各種功能的支援功能來進行資料複寫。您可以使用System Manager來對等兩個叢集、以便對等叢集之間協調及共用資源。 
---
= 叢集對等端點搭配System Manager - ONTAP 更新版本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用ONTAP 經典版的經典版（ONTAP 適用於支援的版本號為2 9.7或更早版本）對等兩個叢集、讓連接的叢集能夠在它們之間協調及共用資源。使用SnapMirror技術和SnapVault SnapMirror技術進行資料複寫時、需要使用對等叢集、FlexCache 而使用支援SyncMirror 各種功能的支援功能、則MetroCluster 需要使用支援各種功能的支援功能來進行資料複寫。



== 產生對等通關密碼

從System Manager 9.6開始、您可以為本機叢集IPspace產生通關密碼、並在建立對等關係時、在遠端叢集中使用相同的通關密碼。

.步驟
. 按一下*組態*>*叢集對等端點*。
. 按一下*產生對等關係密碼*。
+
此時會顯示「產生對等關係密碼」對話方塊視窗。

. 填寫下列欄位：
+
** * IPspace*：從下拉式功能表中選取IPspace。
** *通關密碼有效性*：從下拉式功能表中選取您要通關密碼有效的持續時間。
** * SVM權限*：選取下列其中一項：
+
*** *所有SVMS*表示允許所有SVM存取叢集。
*** *選取的SVMS*表示允許存取叢集的特定SVM。在您要指定的欄位中反白顯示SVM名稱。




. *選用：*如果遠端叢集的有效叢集版本早於ONTAP BIOS 9.6、請選取核取方塊。否則、叢集對等關係就無法產生。
. 按一下「*產生*」以產生通關密碼。
+
為了成功產生、會顯示一則訊息、指出您的通關密碼。

. 如果您要以電子郵件傳送或複製通關密碼、請執行下列其中一項動作：
+
** 按一下*電子郵件通關密碼詳細資料*。
** 按一下*複製通關密碼*。






== 修改叢集對等通關密碼

您可以修改叢集對等點建立期間提供的通關密碼。

.步驟
. [[step1]] 按一下 * 組態 * > * 叢集對等端點 * 。
. 選取連接的叢集、然後按一下*編輯*
+
隨即顯示下拉式功能表。

. 按一下*本機叢集密碼*。
+
此時將顯示Edit local Cluster Passphrase（編輯本機叢集密碼）對話

. [[step4]] 在 * 輸入通行密碼 * 欄位中、輸入新的通行密碼、然後按一下 * 套用 * 。
+
[NOTE]
====
通關密碼長度下限為8個字元。

====
+
密碼會立即修改。不過、可能會有延遲、才顯示正確的驗證狀態。

. 登入遠端叢集、然後執行步驟 link:#step1["1."] 透過 link:#step4["4."] 可修改遠端叢集中的通關密碼。
+
本機叢集的驗證狀態會顯示為 `ok_and_offer` 直到您修改遠端叢集中的複雜密碼。





== 修改為遠端叢集設定的LIF

您可以使用System Manager修改為遠端叢集設定的IPspace和叢集間邏輯介面（lifs）。您可以新增叢集間的IP位址、或移除現有的IP位址。

.開始之前
您必須至少有一個叢集間IP位址、才能建立叢集對等關係。

.步驟
. 按一下*組態*>*叢集*>*組態更新*。
. 選取連接的叢集、然後按一下*編輯*
+
隨即顯示下拉式功能表。

. 按一下*對等叢集網路參數*。
+
隨即顯示「編輯對等網路參數」對話方塊視窗。

. 如有必要、請修改下列欄位：
+
** * IPspace*：從下拉式功能表中選取IPspace。
** *叢集間Lif*：新增或移除叢集間IP位址。您可以使用逗號分隔多個IP位址、以新增多個IP位址。


. 按一下*修改*。
. 驗證您在*叢集對等端點*視窗中所做的變更。




== 變更對等加密狀態

您可以使用System Manager變更所選叢集的對等加密狀態。

.關於這項工作
加密狀態可以啟用或停用。您可以選取*變更加密*、將狀態從「已啟用」變更為「已停用」、或從「已停用」變更為「已啟用」。

.步驟
. 按一下*組態*>*叢集對等端點*。
. 選取連接的叢集、然後按一下*編輯*
+
隨即顯示下拉式功能表。

. 按一下*變更加密*。
+
如果加密狀態為「N/A」、則無法使用此動作。

+
此時會顯示變更加密對話方塊視窗。切換按鈕會指出目前的加密狀態。

. 按下切換按鈕以變更對等加密狀態、然後繼續。
+
** 如果目前的加密狀態為「none"（無）、您可以按下切換按鈕將狀態變更為「'TLs_PSK'」來啟用加密。
** 如果目前的加密狀態為「TLS _PSK"、您可以按下切換按鈕將狀態變更為「無」、以停用加密。


. 啟用或停用對等加密之後、您可以產生新的通關密碼、並在對等叢集上提供密碼、也可以套用已在對等叢集上產生的現有通關密碼。
+
[NOTE]
====
如果本機站台上使用的通關密碼與遠端站台上使用的通關密碼不符、叢集對等關係將無法正常運作。

====
+
選取下列其中一項：

+
** * 產生複雜密碼 * ：繼續 link:#step6["步驟 6"]。
** * 已有通行密碼 * ：請繼續 link:#step9["步驟 9"]。


. [[step6]] 如果您選擇 * 產生複雜密碼 * 、請填寫必要欄位：
+
** * IPspace*：從下拉式功能表中選取IPspace。
** *通關密碼有效性*：從下拉式功能表中選取您要通關密碼有效的持續時間。
** * SVM權限*：選取下列其中一項：
+
*** *所有SVMS*、表示所有SVM均可存取叢集。
*** *選取的SVMS*表示允許存取叢集的特定SVM。在您要指定的欄位中反白顯示SVM名稱。




. *選用：*如果遠端叢集的有效叢集版本早於ONTAP BIOS 9.6、請選取核取方塊。否則、複雜密碼無法產生。
. 按一下「 * 套用 * 」。
+
系統會針對關係產生複雜密碼並加以顯示。您可以複製通關密碼或以電子郵件寄送。

+
本機叢集的驗證狀態會顯示為 `ok_and_offer` 在您在遠端叢集提供複雜密碼之前、請在所選的複雜密碼有效期間內使用。

. [[step9]] 如果您已在遠端叢集中產生新的複雜密碼、請執行下列子步驟：
+
.. 按一下*已有通關密碼*。
.. 在「* Passphrase *（密碼密碼*）」欄位中輸入遠端叢集所產生的密碼。
.. 按一下「 * 套用 * 」。






== 刪除叢集對等關係

如果不再需要關聯、您可以使用System Manager刪除叢集對等關係。您必須從對等關係中的每個叢集刪除叢集對等關係。

.步驟
. [[step1]] 按一下 * 組態 * > * 叢集對等端點 * 。
. 選取您要刪除關聯的叢集對等端點、然後按一下*刪除*。
. [[step3]] 選取確認核取方塊、然後按一下 * 刪除 * 。
. 登入遠端叢集、然後執行步驟 link:#step1["1."] 透過 link:#step3["3."] 刪除本機叢集與遠端叢集之間的對等關係。
+
對等關係的狀態會顯示為「不健全」、直到關係從本機叢集和遠端叢集刪除為止。





== 叢集對等端點視窗

您可以使用叢集對等視窗來管理對等叢集關係、以便將資料從一個叢集移至另一個叢集。



=== 命令按鈕

* *建立*
+
開啟「建立叢集對等」對話方塊、可讓您建立與遠端叢集的關係。

* *編輯*
+
顯示包含下列選項的下拉式功能表：

+
** *本機叢集密碼*
+
開啟「編輯本機叢集密碼」對話方塊、可讓您輸入新的密碼來驗證本機叢集。

** *對等叢集網路參數*
+
開啟「編輯對等叢集網路參數」對話方塊、可讓您修改IPspace並新增或移除叢集間LIF IP位址。

+
您可以新增多個IP位址、並以逗號分隔。

** *變更加密*
+
開啟所選對等叢集的變更加密對話方塊。在變更對等關係的加密時、您可以產生新的通關密碼或提供已在遠端對等叢集產生的通關密碼。

+
如果加密狀態為「N/A」、則無法使用此動作。



* *刪除*
+
開啟「刪除叢集對等關係」對話方塊、可讓您刪除選取的對等叢集關係。

* *重新整理*
+
更新視窗中的資訊。

* *管理SVM權限*
+
讓SVM自動接受SVM對等處理要求。

* *產生對等複雜密碼*
+
可讓您為本機叢集IPspace產生通關密碼、方法是指定IPspace、設定通關密碼有效期、以及指定授予哪些SVM權限。

+
您可以在遠端叢集中使用相同的通關密碼進行對等處理。





=== 對等叢集清單

* *對等叢集*
+
指定關聯中對等叢集的名稱。

* *可用度*
+
指定對等叢集是否可供通訊。

* *驗證狀態*
+
指定對等叢集是否已驗證。

* *本機叢集IPspace*
+
顯示與本機叢集對等關係相關的IPspace。

* *對等叢集叢集間IP位址*
+
顯示與叢集間對等關係相關的IP位址。

* *上次更新時間*
+
顯示上次修改對等叢集的時間。

* *加密*
+
顯示對等關係加密的狀態。

+
[NOTE]
====
從System Manager 9.6開始、當您在兩個叢集之間建立對等關係時、對等功能預設會加密

====
+
** *不適用*：加密不適用於此關係。
** *無*：對等關係未加密。
** * TLs_PSK*：對等關係已加密。



