---
permalink: online-help-96-97/concept_protection_policies.html 
sidebar: sidebar 
keywords: online, help, protection, policy, system, manager, create, edit, delete 
summary: 您可以使用System Manager來建立、編輯及刪除保護原則。 
---
= 使用System Manager管理保護政策- ONTAP 更新版本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用ONTAP 經典版的《經典版》（ONTAP 僅適用於更新版本的版本）來建立、編輯及刪除保護原則。



== 建立保護原則

您可以使用System Manager來建立叢集層級的非同步鏡射原則、保存原則、或鏡射和保存原則、並將這些原則套用至叢集層級的資料保護關係。

.步驟
. 按一下「*保護*」>「*保護原則*」。
. 按一下「 * 建立 * 」。
. 在「*建立原則*」對話方塊中、選取您要建立的原則類型。
. 指定原則名稱和傳輸優先順序。
+
「低」表示傳輸的優先順序最低。低優先順序傳輸通常排定在一般優先順序傳輸之後。依預設、傳輸優先順序設為「正常」。

. *選用：*選取「*啟用網路壓縮*」核取方塊、以壓縮資料傳輸期間傳輸的資料。
. *選用：*對於非同步鏡像原則、請選取*傳輸所有來源Snapshot Copies（傳輸所有來源Snapshot複本）*核取方塊、將「'all_source_snapshots（所有來源快照）」規則納入鏡射原則、此原則會從來源磁碟區備份所有Snapshot複本。
. *可選：*單擊*添加註釋*以添加該策略的其他註釋。
. 針對資料保存原則或鏡射資料保存原則、請指定SnapMirror標籤和目的地保留計數。
. 按一下「 * 建立 * 」。




== 保護原則視窗

您可以使用「保護原則」視窗來建立、管理及顯示有關鏡射、保存庫及鏡射保存原則的資訊。



=== 命令按鈕

* *建立*
+
開啟「建立原則」對話方塊、可讓您建立鏡射、資料保險箱或鏡射資料保險箱原則。

* *編輯*
+
開啟「編輯原則」對話方塊、可讓您編輯原則。

* *刪除*
+
開啟「刪除原則」對話方塊、可讓您刪除原則。

* *重新整理*
+
更新視窗中的資訊。





=== 保護原則清單

* *名稱*
+
顯示保護原則的名稱。

* *類型*
+
顯示原則類型、可以是Vault、Mirror Vault或非同步鏡射。

* *意見*
+
顯示為原則指定的說明。

* *傳輸優先順序*
+
顯示資料傳輸優先順序、例如「正常」或「低」。





=== 詳細資料區域

* *原則詳細資料索引標籤*
+
顯示保護原則的詳細資料、例如建立原則的使用者、規則數目、保留計數和網路壓縮狀態。

* *原則規則索引標籤*
+
顯示套用至原則的規則詳細資料。只有選取的原則包含規則時、才會顯示原則規則索引標籤。


