---
permalink: online-help-96-97/concept_shares.html 
sidebar: sidebar 
keywords: online, help, share, system, manager, qtress, cifs, create, edit, manage, share, access, stop, home, directory, configure, smb 
summary: 您可以使用System Manager來建立、編輯及管理共用。 
---
= 使用System Manager管理共享資源- ONTAP 更新版本
:allow-uri-read: 


您可以使用ONTAP 經典版的《經典版》（ONTAP 僅適用於更新版本的版本）來建立、編輯及管理共享區。



== 建立CIFS共用區

您可以使用System Manager建立CIFS共用區、以便指定CIFS使用者可以存取的資料夾、qtree或Volume。

.開始之前
您必須先安裝CIFS授權、才能設定及啟動CIFS。

.步驟
. 按一下「*儲存設備*>*共享區*」。
. 從* SVM*欄位的下拉式功能表中、選取您要在其中建立CIFS共用的SVM。
. 按一下「 * 建立共用 * 」。
. 在「*建立共用*」視窗中、按一下「*瀏覽*」、然後選取應共用的資料夾、qtree或Volume。
. 指定新CIFS共用的名稱。
. *選用：*選取*「啟用Hyper-V和SQL*的持續可用度」核取方塊、允許支援SMB 3.0及更新版本的用戶端在不中斷營運期間持續開啟檔案。
+
使用此選項開啟的檔案、可防止發生中斷事件、例如容錯移轉、還原及LIF移轉。

+
從System Manager 9.6開始、FlexGroup 支援不中斷供應的功能。

. 選取「存取此共享區時加密資料*」核取方塊以啟用SMB 3.0加密。
. 提供共用區的說明或註解、然後按一下*「Create」（建立）*。


.結果
CIFS共用區是以群組中設為「所有人的完整控制權」的存取權限所建立。



== 停止共用存取

當您想要移除資料夾、qtree或Volume的共用網路存取時、可以使用System Manager來停止共用。

.開始之前
您必須已安裝CIFS授權。

.步驟
. 按一下「*儲存設備*>*共享區*」。
. 從* SVM*欄位的下拉式功能表中、選取您要停止之CIFS共用所在的SVM。
. 從共用清單中、選取您要停止共用的共用、然後按一下*停止共用*。
. 選取確認核取方塊、然後按一下*停止*。
. 驗證共享區是否不再列在*共享區*視窗中。




== 建立主目錄共用

您可以使用System Manager建立主目錄共用區、以及管理主目錄搜尋路徑。

.開始之前
CIFS必須設定並啟動。

.步驟
. 按一下「*儲存設備*>*共享區*」。
. 按一下「*建立主目錄*」、然後提供決定使用者如何對應至目錄的模式資訊。
. 按一下「 * 建立 * 」。
. 驗證您所建立的主目錄是否列在*共用*視窗中。




== 編輯共用設定

您可以使用System Manager修改共用區的設定、例如符號連結設定、共用使用者或群組的存取權限、以及共用區的存取類型。您也可以啟用或停用透過Hyper-V的共用區持續可用度、以及啟用或停用存取型列舉（ABE）。從System Manager 9.6開始、FlexGroup 支援不中斷供應的功能。

.步驟
. 按一下「*儲存設備*>*共享區*」。
. 從共用清單中選取您要修改的共用區、然後按一下*編輯*。
. 在*編輯共用設定*對話方塊中、視需要修改共用設定：
+
.. 在「*一般*」索引標籤中、啟用Hyper-V上的共享區持續可用度
+
啟用持續可用度可讓SMB 3.0和支援SMB 3.0的用戶端在不中斷營運的情況下持續開啟檔案。持續開啟的檔案會受到保護、不受容錯移轉、還原及LIF移轉等中斷事件的影響。

.. 在「*權限*」索引標籤中、新增使用者或群組、然後指派權限以指定存取類型。
.. 在*選項*索引標籤中、選取所需的選項。


. 按一下*儲存並關閉*。
. 驗證您在「*共享區*」視窗中對所選共享區所做的變更。




== 如何啟用動態主目錄ONTAP

利用支援支援的主目錄、您可以根據連線的使用者及一組變數、設定對應至不同目錄的SMB共用區。ONTAP您可以使用幾個主目錄參數來設定一個共用區、以定義使用者在入口點（共享區）和主目錄（SVM上的目錄）之間的關係、而非為每個使用者建立個別的共用區。

以訪客使用者身分登入的使用者沒有主目錄、也無法存取其他使用者的主目錄。有四個變數可決定使用者如何對應至目錄：

* *共享名稱*
+
這是您建立的共用名稱、使用者可連線至該共用。您必須設定此共用的主目錄屬性。

+
共用名稱可以使用下列動態名稱：

+
** `%w` （使用者的 Windows 使用者名稱）
** `%d` （使用者的 Windows 網域名稱）
** `%u` （使用者對應的 UNIX 使用者名稱）


+
若要讓共用名稱在所有主目錄中都是唯一的、共用名稱必須包含/`%w` 或 `%u` 變動。共用名稱可以同時包含 `%d` 和/`%w` 變數（例如、 `%d`/`%w`）、或共享區名稱可以包含靜態部分和可變部分（例如 hom_ ）/`%w`）。

* *共享路徑*
+
這是由共用定義的相對路徑、因此會與其中一個共用名稱相關聯、並附加到每個搜尋路徑、以從SVM根目錄產生使用者的完整主目錄路徑。它可以是靜態的（例如、 `home`）、動態（例如、 `%w`）、或兩者的組合（例如、 `eng/%w`）。

* *搜尋路徑*
+
這是從SVM根目錄開始的一組絕對路徑、您可以指定這些路徑來引導ONTAP 針對主目錄進行搜尋。您可以使用指定一或多個搜尋路徑 `vserver cifs home-directory search-path add` 命令。如果您指定多個搜尋路徑、ONTAP 則在找到有效路徑之前、將會依照指定的順序嘗試這些路徑。

* *目錄*
+
這是您為使用者建立的使用者主目錄。目錄名稱通常是使用者的名稱。您必須在搜尋路徑所定義的其中一個目錄中建立主目錄。



舉例來說、請考慮下列設定：

* 使用者：John Smith
* 使用者網域：Acme
* 使用者名稱：jsmith
* SVM名稱：VS1
* 主目錄共用名稱 #1 ： hom_ `%w` - 共享路徑： `%w`
* 主目錄共用名稱 #2 ： `%w` - 共享路徑： `%d/%w`
* 搜尋路徑 #1 ： `/vol0home/home`
* 搜尋路徑 #2 ： `/vol1home/home`
* 搜尋路徑 #3 ： `/vol2home/home`
* 主目錄： `/vol1home/home/jsmith`


案例 1 ：使用者連線至 `\\vs1\home_jsmith`。這會比對第一個主目錄共用名稱、並產生相對路徑 `jsmith`。ONTAP 現在會搜尋名為的目錄 `jsmith` 依序檢查每個搜尋路徑：

* `/vol0home/home/jsmith` 不存在；請繼續搜尋路徑 #2 。
* `/vol1home/home/jsmith` 存在；因此不會核取搜尋路徑 #3 ；使用者現在已連線至其主目錄。


案例 2 ：使用者連線至 `\\vs1\jsmith`。這會比對第二個主目錄共用名稱、並產生相對路徑 `acme/jsmith`。ONTAP 現在會搜尋名為的目錄 `acme/jsmith` 依序檢查每個搜尋路徑：

* `/vol0home/home/acme/jsmith` 不存在；請繼續搜尋路徑 #2 。
* `/vol1home/home/acme/jsmith` 不存在；請繼續搜尋路徑 #3 。
* `/vol2home/home/acme/jsmith` 不存在；主目錄不存在；因此連線失敗。




== 共享區

您可以使用「共享區」視窗來管理您的共享區、以及檢視共享區的相關資訊。



=== 命令按鈕

* *建立共用*
+
開啟「建立共用」對話方塊、可讓您建立共用。

* *建立主目錄*
+
開啟「建立主目錄共用」對話方塊、可讓您建立新的主目錄共用。

* *編輯*
+
開啟「編輯設定」對話方塊、可讓您修改所選共用的內容。

* *停止共享*
+
停止共用選取的物件。

* *重新整理*
+
更新視窗中的資訊。





=== 共享區清單

共用清單會顯示每個共用區的名稱和路徑。

* *共享名稱*
+
顯示共用的名稱。

* *路徑*
+
顯示共享的現有資料夾、qtree或磁碟區的完整路徑名稱。路徑分隔符號可以是反斜槓或正斜槓、雖然ONTAP 它會將所有路徑分隔符號顯示為正斜槓。

* *主目錄*
+
顯示主目錄共用的名稱。

* *意見*
+
顯示共用區的其他說明（如果有）。

* *持續可用的共享*
+
顯示是否已啟用共用以確保持續可用度。從System Manager 9.6開始、FlexGroup 支援不中斷供應的功能。





=== 詳細資料區域

共用清單下方的區域會顯示每個共用區的共用內容和存取權限。

* *內容*
+
** 名稱
+
顯示共用的名稱。

** oplocks狀態
+
指定共用區是否使用投機性鎖定（oplocks）。

** 可瀏覽的
+
指定Windows用戶端是否可以瀏覽共用區。

** 顯示Snapshot
+
指定用戶端是否可以檢視Snapshot複本。

** 持續可用的共用
+
指定是否啟用或停用共用區以確保持續可用度。從System Manager 9.6開始、FlexGroup 支援不中斷供應的功能。

** 存取型列舉
+
指定是否在共用區上啟用或停用存取型列舉（ABE）。

** BranchCache
+
指定在共用區上啟用或停用BranchCache。

** SMB加密
+
指定是在儲存虛擬機器（SVM）層級或共用層級啟用使用SMB 3.0的資料加密。如果在SVM層級啟用SMB加密、則SMB加密會套用至所有共享區、且此值會顯示為「已啟用」（在SVM層級）。

** 舊版
+
指定是否可從用戶端檢視及還原舊版。



* *共享存取控制*
+
顯示共用的網域使用者、網域群組、本機使用者和本機群組的存取權限。



*相關資訊*

xref:task_setting_up_cifs.adoc[設定 CIFS]
