---
permalink: online-help-96-97/concept_schedules.html 
sidebar: sidebar 
keywords: online, help, system, manager, manage, schedule, storage 
summary: 您可以使用System Manager在儲存系統中建立及管理排程。 
---
= 使用System Manager（ONTAP 更新版本）管理排程-更新版本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用ONTAP 經典版的《經典版》（ONTAP 僅適用於更新版本的版本）來建立及管理儲存系統中的排程。



== 建立排程

您可以使用System Manager建立排程、以便在特定時間或定期執行工作。

.關於這項工作
當您在MetroCluster 一個完整組態中建立排程時、最佳做法是在存續站台的叢集上建立一個等效排程。

.步驟
. 按一下* Protection（保護）**排程*。
. 按一下「 * 建立 * 」。
. 在「*建立排程*」對話方塊中、指定排程名稱。
. 根據您的需求建立排程：
+
|===
| 如果您要建立... | 執行此動作... 


 a| 
特定日期的每日或特定排程
 a| 
選取* Basic *、然後指定排程和週期詳細資料（以小時和分鐘為單位）。



 a| 
以特定時間間隔執行的排程
 a| 
選取*「時間間隔」*、然後指定排程和週期詳細資料（以天、小時和分鐘為單位）。



 a| 
在特定期間執行的排程
 a| 
選取*進階*、然後指定排程和週期詳細資料（以月、日、工作日、小時和分鐘為單位）。

|===
. 按一下「 * 建立 * 」。




== 編輯排程

如果先前建立的cron排程或時間間隔排程不符合您的需求、您可以使用System Manager進行變更。您可以修改排程詳細資料、例如週期性天數和時數、時間間隔選項、以及進階cron選項。

.關於這項工作
當您在MetroCluster 某個功能完善的組態中編輯排程時、最好也在運作正常的站台叢集上編輯相同的排程。

.步驟
. 按一下* Protection（保護）**排程*。
. 選取您要修改的排程、然後按一下*編輯*。
. 在*編輯排程*對話方塊中、執行適當的動作來修改排程：
+
|===
| 如果您選取排程選項為... | 來吧... 


 a| 
基本
 a| 
指定週期性天數和週期性排程詳細資料。



 a| 
時間間隔
 a| 
指定時間間隔選項（以天、小時和分鐘為單位）。



 a| 
進階
 a| 
指定進階cron選項、包括月、日、週日（若適用）、小時和分鐘。

|===
. 按一下「*確定*」。




== 刪除排程

[role="lead"]
您可以使用System Manager刪除執行特定儲存管理工作的排程。

.步驟
. 按一下* Protection（保護）**排程*。
. 選取您要刪除的排程、然後按一下*刪除*。
. 選取確認核取方塊、然後按一下*刪除*。




== 管理排程

您可以設定許多工作（例如Volume Snapshot複本和鏡射複製）、以在指定的排程上執行。根據指定排程執行的排程稱為 _cron 排程、因為它們與 UNIX 相似 `cron` 排程。每隔一段時間執行的排程稱為「_interval_排程」。

您可以使用下列方式來管理排程：

* 建立cron排程或間隔排程
* 顯示所有排程的相關資訊
* 修改cron排程或間隔排程
* 刪除cron排程或間隔排程
+
您無法刪除執行中工作目前正在使用的排程。



叢集管理員可以執行所有排程管理工作。



== 排程時間

您可以使用「排程」視窗來管理排程工作、例如建立、顯示、修改及刪除排程的相關資訊。



=== 命令按鈕

* *建立*
+
開啟「建立排程」對話方塊、可讓您建立時間和時間間隔排程。

* *編輯*
+
開啟「編輯排程」對話方塊、可讓您編輯選取的排程。

* *刪除*
+
開啟「刪除排程」對話方塊、可讓您刪除選取的排程。

* *重新整理*
+
更新視窗中的資訊。





=== 排程清單

* *名稱*
+
指定排程名稱。

* *類型*
+
指定排程類型-時間型或時間間隔型。





=== 詳細資料區域

詳細資料區域會顯示執行所選排程的相關資訊。
