---
permalink: online-help-96-97/concept_quotas.html 
sidebar: sidebar 
keywords: system, manager, quota, online, help, view, activate, deactivate, information, types, targets, default, limits, space, files, manage, tree, group 
summary: 您可以使用System Manager來建立、編輯及刪除配額。 
---
= 使用System Manager管理配額- ONTAP 不含更新版本的更新版本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用ONTAP 經典版的《經典版》（ONTAP 僅適用於更新版本的版本）來建立、編輯及刪除配額。



== 建立配額

配額可讓您限制或追蹤使用者、群組或qtree所使用的磁碟空間和檔案數量。您可以使用System Manager中的「新增配額」精靈來建立配額、並將配額套用至特定的Volume或qtree。

.關於這項工作
使用System Manager、您可以指定硬限制的最小值、以及配額可以擁有的檔案數量的軟限制、最小值為1000。如果要指定低於1000的值、則應使用命令列介面（CLI）。

.步驟
. 按一下「*儲存設備*>*配額*」。
. 從* SVM*欄位的下拉式功能表中、選取您要在其中建立配額的儲存虛擬機器（SVM）。
. 在*使用者定義的配額*索引標籤中、按一下*建立*。
+
隨即顯示Create Quota Wizard（建立配額精靈）。

. 依照精靈的提示輸入或選取資訊。
. 確認詳細資料、然後按一下「*完成*」完成精靈。




=== 接下來該怎麼做

您可以使用本機使用者名稱或RID來建立使用者配額。如果您使用使用者名稱或群組名稱來建立使用者配額或群組配額、則會使用 ``/etc/passwd``檔案和``/etc/group``檔案必須分別更新。



== 刪除配額

當使用者及其儲存需求和限制變更時、您可以使用System Manager刪除一或多個配額。

.步驟
. 按一下「*儲存設備*>*配額*」。
. 從「* SVM*」欄位的下拉式功能表中、選取您要刪除的配額所在的儲存虛擬機器（SVM）。
. 選取您要刪除的一或多個配額、然後按一下*刪除*。
. 選取確認核取方塊、然後按一下*刪除*。




== 編輯配額限制

您可以使用System Manager來編輯磁碟空間臨界值、配額目標可使用的磁碟空間量硬限制和軟限制、以及配額目標可以擁有的檔案數量硬限制和軟限制。

.步驟
. 按一下「*儲存設備*>*配額*」。
. 從* SVM*欄位的下拉式功能表中、選取您要編輯的配額所在的儲存虛擬機器（SVM）。
. 選取您要編輯的配額、然後按一下*編輯限制*。
. 在*編輯限制*對話方塊中、視需要編輯配額設定。
+
一百（100）是您可以指定硬限制的最小值、以及配額可以擁有的檔案數量軟限制。如果您想要指定低於 100 的值、請使用命令列介面（ CLI ）。

. 按一下*儲存並關閉*。
. 驗證您在*使用者定義的配額*標籤中對所選配額所做的變更。




== 啟動或停用配額

您可以使用System Manager在儲存系統上選取的一或多個磁碟區上啟動或停用配額。當使用者及其儲存需求和限制變更時、您可以啟動或停用配額。

.步驟
. 按一下「*儲存設備*>*配額*」。
. 從SVM欄位的下拉式功能表中、選取要啟動或停用配額的儲存虛擬機器（SVM）。
. 在「磁碟區*上的配額狀態」索引標籤中、選取您要啟動或停用配額的一或多個磁碟區。
. 視需要按一下「*啟動*」或「*停用*」。
. 如果您要停用配額、請選取確認核取方塊、然後按一下*確定*。
. 驗證「*狀態*」欄中磁碟區的配額狀態。




== 調整配額大小

您可以使用System Manager中的Resize Quota（調整配額大小）對話方塊來調整指定磁碟區中的作用中配額、使其反映您對配額所做的變更。

.開始之前
您必須為要調整配額大小的磁碟區啟用配額。

.步驟
. 按一下「*儲存設備*>*配額*」。
. 在「*配額*」視窗的「磁碟區*上的配額狀態」索引標籤中、選取您要調整配額大小的一或多個磁碟區。
. 按一下*調整大小*。




== 檢視配額資訊

您可以使用System Manager中的Quotas視窗來檢視配額詳細資料、例如套用配額的磁碟區和qtree、配額類型、套用配額的使用者或群組、以及空間和檔案使用量。

.步驟
. 按一下「*儲存設備*>*配額*」。
. 從* SVM*欄位的下拉式功能表中、選取您要檢視其相關資訊的配額所在儲存虛擬機器（SVM）。
. 執行適當的行動：
+
[cols="1a,1a"]
|===
| 如果... | 然後... 


 a| 
您想要檢視您所建立之所有配額的詳細資料
 a| 
按一下*使用者定義的配額*索引標籤。



 a| 
您想要檢視目前作用中配額的詳細資料
 a| 
按一下*配額報告*索引標籤。

|===
. 從顯示的配額清單中選取您要檢視的配額資訊。
. 檢閱配額詳細資料。




== 配額類型

配額可以根據套用配額的目標來分類。

以下是根據套用配額的目標而定的配額類型：

* *使用者配額*
+
目標是使用者。

+
使用者可以使用UNIX使用者名稱、UNIX UID、Windows SID、其UID與使用者相符的檔案或目錄、Windows 2000之前格式的Windows使用者名稱、以及具有使用者SID所擁有ACL的檔案或目錄來表示。您可以將其套用至磁碟區或qtree。

* *群組配額*
+
目標是群組。

+
群組由UNIX群組名稱、Gid、或是其Gid符合群組的檔案或目錄來表示。不套用以Windows ID為基礎的群組配額。ONTAP您可以將配額套用至磁碟區或qtree。

* * Qtree配額*
+
目標是qtree、由qtree的路徑名稱指定。

+
您可以決定目標qtree的大小。

* *預設配額*
+
自動將配額限制套用至一組大型配額目標、而不會為每個目標建立個別配額。

+
預設配額可套用至所有三種配額目標類型（使用者、群組和qtree）。配額類型是由類型欄位的值所決定。





== 配額限制

您可以套用磁碟空間限制、或限制每個配額類型的檔案數量。如果您未指定配額限制、則不會套用任何配額。

配額可以是軟的或硬的。軟配額會導致Data ONTAP 當超過指定的限制時、不再傳送通知、硬配額則會在超過指定的限制時、防止寫入作業成功。

硬額度會對系統資源造成硬限制、導致超出限制的任何作業都會失敗。下列設定會建立硬額度：

* 磁碟限制參數
* 檔案限制參數


軟性配額會在資源使用量達到特定層級時傳送警告訊息、但不會影響資料存取作業、因此您可以在超出配額之前採取適當的行動。下列設定會建立軟性配額：

* 磁碟限制參數臨界值
* Soft Disk限制參數
* Soft Files限制參數


臨界值和軟式磁碟配額可讓系統管理員收到一個以上的配額通知。一般而言、系統管理員會將「磁碟限制臨界值」設定為僅稍微小於「磁碟限制」的值、以便在寫入開始失敗之前、臨界值會提供「最終警告」。

* *磁碟空間硬限制*
+
套用至硬碟配額的磁碟空間限制。

* *磁碟空間軟限制*
+
套用至軟性配額的磁碟空間限制。

* *臨界值限制*
+
套用至臨界值配額的磁碟空間限制。

* *檔案硬限制*
+
硬配額上的檔案數目上限。

* *檔案軟限制*
+
軟配額中的檔案數目上限。





== 配額管理

System Manager包含多項功能、可協助您建立、編輯或刪除配額。您可以建立使用者、群組或樹狀結構配額、也可以在磁碟和檔案層級指定配額限制。所有配額都是以每個磁碟區為基礎來建立。

建立配額之後、您可以執行下列工作：

* 啟用和停用配額
* 調整配額大小




== 配額視窗

您可以使用配額視窗來建立、顯示及管理配額的相關資訊。



=== 索引標籤

* *使用者定義的配額*
+
您可以使用*使用者定義的配額*索引標籤來檢視所建立配額的詳細資料、以及建立、編輯或刪除配額。

* *配額報告*
+
您可以使用「配額報告」索引標籤來檢視空間和檔案使用量、以及編輯作用中配額的空間和檔案限制。

* *磁碟區上的配額狀態*
+
您可以使用「Volumes（磁碟區）」索引標籤上的「Quota Status（配額狀態）」來檢視配額狀態、以及開啟或關閉配額、以及調整配額大小。





=== 命令按鈕

* *建立*
+
開啟「建立配額」精靈、可讓您建立配額。

* *編輯限制*
+
開啟「編輯限制」對話方塊、可讓您編輯所選配額的設定。

* *刪除*
+
從配額清單中刪除選取的配額。

* *重新整理*
+
更新視窗中的資訊。





=== 使用者定義的配額清單

配額清單會顯示每個配額的名稱和儲存資訊。

* * Volume *
+
指定要套用配額的磁碟區。

* * Qtree *
+
指定與配額相關聯的qtree。「All qtree」表示配額與所有qtree相關聯。

* *類型*
+
指定配額類型：使用者、群組或樹狀結構。

* *使用者/群組*
+
指定與配額相關聯的使用者或群組。「所有使用者」表示配額與所有使用者相關聯。「所有群組」表示配額與所有群組相關聯。

* *配額目標*
+
指定配額指派給的目標類型。目標可以是qtree、使用者或群組。

* *空間硬限制*
+
指定套用至硬體配額的磁碟空間限制。

+
此欄位預設為隱藏。

* *空間軟限制*
+
指定套用至軟性配額的磁碟空間限制。

+
此欄位預設為隱藏。

* *臨界值*
+
指定套用至臨界值配額的磁碟空間限制。

+
此欄位預設為隱藏。

* *檔案硬限制*
+
指定硬配額中的檔案數目上限。

+
此欄位預設為隱藏。

* *檔案軟限制*
+
指定軟配額中的檔案數目上限。

+
此欄位預設為隱藏。





=== 詳細資料區域

配額清單下方的區域會顯示配額詳細資料、例如配額錯誤、空間使用量和限制、以及檔案使用量和限制。

*相關資訊*

https://docs.netapp.com/us-en/ontap/volumes/index.html["邏輯儲存管理"^]
