---
permalink: online-help-96-97/concept_cluster_expansion.html 
sidebar: sidebar 
keywords: cluster, expanision, system, manager, storage, size, capabilities, add, node, configure, network, online, help 
summary: 您可以使用System Manager將相容的節點新增至叢集、並設定節點網路詳細資料、藉此增加儲存設備的大小和功能。您也可以檢視節點摘要。 
---
= 使用System Manager進行叢集擴充- ONTAP 不含更新版本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用ONTAP 經典版的《經典版》（ONTAP 僅適用於更新版本的版本）、將相容的節點新增至叢集並設定節點網路詳細資料、藉此增加儲存設備的大小和功能。您也可以檢視節點摘要。

登入System Manager時、System Manager會自動偵測已連接纜線但尚未新增至叢集的相容節點、並提示您新增節點。您可以在系統管理員偵測到節點時新增相容節點、也可以稍後手動新增節點。



== 新增節點至叢集

您可以使用System Manager將節點新增至現有叢集、以增加儲存系統的大小和功能。

.開始之前
* 新的相容節點必須連接至叢集。
+
「網路」視窗中只會列出預設廣播網域中的連接埠。

* 叢集中的所有節點都必須啟動並執行。
* 所有節點都必須為相同版本。


.步驟
. 將新的相容節點新增至叢集：
+
|===
| 如果您... | 執行此動作... 


 a| 
未登入System Manager
 a| 
.. 登入System Manager。
+
[NOTE]
====
系統管理員會在登入時自動偵測到新的相容節點。System Manager會提示您將新的相容節點新增至叢集。

====
.. 單擊* Add Node to Cluster-*。
.. 修改節點名稱。
.. 指定節點授權。
.. 按一下*提交並繼續*。




 a| 
已登入System Manager
 a| 
.. 按一下*組態*>*叢集*>*擴充*。
+
System Manager會搜尋新增的節點。如果顯示任何警告、您必須先修正這些警告、然後再繼續。如果發現新的相容節點、請繼續下一步。

.. 修改節點名稱。
.. 指定節點授權。
.. 按一下*提交並繼續*。


|===




== 設定節點的網路詳細資料

您可以使用System Manager為新增的節點設定節點管理LIF和服務處理器設定。

.開始之前
* 在建立LIF的預設IPspace中、必須有足夠數量的連接埠。
* 所有連接埠都必須正常運作。


.步驟
. 設定節點管理：
+
.. 在「* IP位址*」欄位中輸入IP位址。
.. 在「*連接埠*」欄位中選取節點管理連接埠。
.. 輸入網路遮罩和閘道詳細資料。


. 設定服務處理器設定：
+
.. 選取*置換預設值*核取方塊以置換預設值。
.. 輸入IP位址、網路遮罩和閘道詳細資料。


. 按一下*提交並繼續*以完成節點的網路組態。
. 驗證「*摘要*」頁面中的節點詳細資料。




=== 接下來該怎麼做

* 如果叢集受到保護、您應該在新增的節點中建立所需數量的叢集間生命體、以避免部分對等和不良保護。
* 如果叢集中已啟用SAN資料傳輸協定、您應該建立所需數量的SAN資料生命量來提供資料。


*相關資訊*

xref:task_creating_network_interfaces.adoc[建立網路介面]
