---
permalink: online-help-96-97/concept_name_mapping.html 
sidebar: sidebar 
keywords: name, mapping, system, manager, specify, user, platform, online, help, command, button, rules 
summary: 您可以使用System Manager來指定名稱對應項目、以對應不同平台的使用者。 
---
= 使用System Manager進行名稱對應- ONTAP 不含更新版本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用ONTAP 經典版的支援功能（ONTAP 僅適用於支援支援支援的版本）來指定名稱對應項目、以對應不同平台的使用者。



== 名稱對應轉換規則

這個系統可為每個SVM保留一組轉換規則。ONTAP每個規則包含兩個部分：_Pattern_和_replace_。轉換從適當清單的開頭開始、並根據第一個相符規則執行替代。模式是UNIX樣式的規則運算式。取代是包含轉義序列的字串、代表模式中的子運算式、如同 UNIX `sed` 方案。



== 名稱對應視窗

您可以使用「名稱對應」視窗來指定名稱對應項目、以對應不同平台的使用者。



=== 名稱對應

您可以建立並使用名稱對應、將UNIX使用者對應至Windows使用者、Windows使用者對應至UNIX使用者、或將Kerberos使用者對應至UNIX使用者。



=== 命令按鈕

* *新增*
+
開啟「新增名稱對應項目」對話方塊、可讓您在儲存虛擬機器（SVM）上建立名稱對應。

* *編輯*
+
開啟「編輯名稱對應項目」對話方塊、可讓您編輯SVM上的名稱對應。

* *刪除*
+
開啟「刪除名稱對應項目」對話方塊、可讓您刪除名稱對應項目。

* *交換*
+
開啟「交換名稱對應項目」對話方塊、可讓您交換兩個選取名稱對應項目的位置。

* *重新整理*
+
更新視窗中的資訊。





=== 名稱對應清單

* *職位*
+
指定名稱對應在優先順序清單中的位置。名稱對應會依照其在優先順序清單中的發生順序來套用。

* *模式*
+
指定必須相符的使用者名稱模式。

* *更換*
+
指定使用者名稱的替代模式。

* *方向*
+
指定名稱對應的方向。可能的值包括krb_UNIX（用於Kerberos到UNIX的名稱映射）、win_UNIX（用於Windows到UNIX的名稱映射）和UNIK_win（用於UNIX到Windows的名稱映射）。





=== 命令按鈕

* *新增*
+
開啟「新增群組對應項目」對話方塊、可讓您在SVM上建立群組對應。

* *編輯*
+
開啟「編輯群組對應項目」對話方塊、可讓您編輯SVM上的群組對應。

* *刪除*
+
開啟「刪除群組對應項目」對話方塊、可讓您刪除群組對應項目。

* *交換*
+
開啟「交換群組對應項目」對話方塊、可讓您交換兩個選取群組對應項目的位置。

* *重新整理*
+
更新視窗中的資訊。





=== 群組對應清單

* *職位*
+
指定群組對應在優先順序清單中的位置。群組對應會依照其在優先順序清單中的發生順序來套用。

* *模式*
+
指定必須相符的使用者名稱模式。

* *更換*
+
指定使用者名稱的替代模式。

* *方向*
+
指定群組對應的方向。可能的值包括 `krb_unix` 對於 Kerberos 對 UNIX 群組對應、 `win_unix` 適用於 Windows 至 UNIX 群組對應、以及 `unix_win` 適用於 UNIX 至 Windows 群組對應。



*相關資訊*

https://docs.netapp.com/us-en/ontap/smb-admin/index.html["SMB/CIFS管理"]
