---
permalink: online-help-96-97/concept_managing_network.html 
sidebar: sidebar 
keywords: system, manager, storage, create, manage, ipspace, broadcast, domain, subnet, network, interface, ethernet, port, fc, fcoe, adapter, online, help 
summary: 您可以使用System Manager來管理儲存系統的網路、方法是建立及管理IPspace、廣播網域、子網路、網路介面、乙太網路連接埠、 和FC/FCoE介面卡。 
---
= 使用System Manager（ONTAP 系統管理程式）來管理網路-更新版本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用ONTAP 經典版的《經典版》（ONTAP 僅適用於更新版本的版本）來管理儲存系統的網路、方法是建立及管理IPspace、廣播網域、子網路、網路介面、乙太網路連接埠、 和FC/FCoE介面卡。



== 網路視窗

[role="lead"]
您可以使用「網路」視窗來檢視網路元件清單、例如子網路、網路介面、乙太網路連接埠、廣播網域、 FC/FCoE和NVMe介面卡、以及IPspaces、以及在儲存系統中建立、編輯或刪除這些元件。



=== 索引標籤

* *子網路*
+
可讓您檢視子網路清單、並從儲存系統建立、編輯或刪除子網路。

* *網路介面*
+
可讓您檢視網路介面清單、從儲存系統建立、編輯或刪除介面、移轉lifs、變更介面狀態、以及將介面傳回主連接埠。

* *乙太網路連接埠*
+
可讓您檢視及編輯叢集的連接埠、以及建立、編輯或刪除介面群組和VLAN連接埠。

* *廣播網域*
+
可讓您檢視廣播網域清單、以及從儲存系統建立、編輯或刪除網域。

* * FC/FCoE與NVMe介面卡*
+
可讓您檢視叢集中的連接埠、並編輯FC/FCoE和NVMe介面卡設定。

* * IP空間*
+
可讓您檢視IPspace和廣播網域清單、以及從儲存系統建立、編輯或刪除IPspace。





=== 子網路索引標籤



=== 命令按鈕

* *建立*
+
開啟「建立子網路」對話方塊、可讓您建立新的子網路、其中包含建立網路介面的組態資訊。

* *編輯*
+
開啟「編輯子網路」對話方塊、可讓您修改子網路的特定屬性、例如名稱、子網路位址、IP位址範圍及閘道詳細資料。

* *刪除*
+
刪除選取的子網路。

* *重新整理*
+
更新視窗中的資訊。





=== 子網路清單

* *名稱*
+
指定子網路的名稱。

* *子網路IP/子網路遮罩*
+
指定子網路位址詳細資料。

* *閘道*
+
指定閘道的IP位址。

* *可用*
+
指定子網路中可用的IP位址數目。

* *已用*
+
指定子網路中使用的IP位址數目。

* *總數*
+
指定子網路中的IP位址總數（可用和使用）。

* *廣播網域*
+
指定子網路所屬的廣播網域。

* * IPspace*
+
指定子網路所屬的IPspace。





=== 詳細資料區域

子網路清單下方的區域會顯示所選子網路的詳細資訊、包括子網路範圍、以及顯示可用、已用及IP位址總數的圖表。



=== 網路介面索引標籤的限制

* 對於叢集生命期、節點管理生命期、VIP生命期和BGP生命期、您無法使用System Manager執行下列動作：
+
** 建立、編輯、刪除、啟用或停用lifs
** 移轉lifs或將lifs傳送回主連接埠


* 對於叢集管理生命期、您可以使用System Manager移轉生命期、或將生命期傳回主連接埠。
+
不過、您無法建立、編輯、刪除、啟用、 或停用lifs。

* 對於叢集間的LIF、您可以使用System Manager來建立、編輯、刪除、啟用或停用LIF。
+
但是、您無法移轉lifs、或將lifs傳回主連接埠。

* 您無法在下列組態中建立、編輯或刪除網路介面：
+
** 一個可執行的組態MetroCluster
** 設定用於災難恢復（DR）的SVM。






=== 命令按鈕

* *建立*
+
開啟「建立網路介面」對話方塊、可讓您建立網路介面和叢集間LIF、以提供資料及管理SVM。

* *編輯*
+
開啟「編輯網路介面」對話方塊、您可以使用此對話方塊來啟用資料LIF的管理存取。

* *刪除*
+
刪除選取的網路介面。

+
只有停用資料LIF時、才會啟用此按鈕。

* *狀態*
+
開啟下拉式功能表、提供啟用或停用所選網路介面的選項。

* *移轉*
+
可讓您將資料LIF或叢集管理LIF移轉至同一個節點上的不同連接埠、或移轉至叢集內的不同節點。

* *傳送至首頁*
+
可讓您將LIF裝載回其主連接埠。

+
只有當所選介面裝載於非主連接埠、且主連接埠可用時、才會啟用此命令按鈕。

+
當叢集中的任何節點當機時、此命令按鈕會停用。

* *重新整理*
+
更新視窗中的資訊。





=== 介面清單

您可以將指標移到彩色編碼圖示上、以檢視介面的作業狀態：

* 綠色表示介面已啟用。
* 紅色表示介面已停用。
* *介面名稱*
+
指定網路介面的名稱。

* *儲存虛擬機器*
+
指定介面所屬的SVM。

* * IP位址/ WWPN*
+
指定介面的IP位址或全球連接埠名稱（WWPN）。

* *目前連接埠*
+
指定介面所在的節點和連接埠名稱。

* *資料傳輸協定存取*
+
指定用於存取資料的傳輸協定。

* *管理存取*
+
指定是否在介面上啟用管理存取。

* *子網路*
+
指定介面所屬的子網路。

* * mx角色*
+
指定介面的作業角色、可以是資料、叢集間、叢集、叢集管理或節點管理。





=== 詳細資料區域

介面清單下方的區域會顯示所選介面的詳細資訊：容錯移轉內容、例如主連接埠、目前連接埠、連接埠速度、容錯移轉原則、容錯移轉群組及容錯移轉狀態、以及一般內容、例如管理狀態、角色、IPspace、廣播網域、網路遮罩、 閘道和DDNS狀態。



=== 乙太網路連接埠索引標籤



=== 命令按鈕

* *建立介面群組*
+
開啟Create Interface Group（建立介面群組）對話方塊、您可透過選擇連接埠來建立介面群組、並決定連接埠和網路流量分配的使用。

* *建立VLAN*
+
開啟Create VLAN（建立VLAN）對話方塊、您可以選擇乙太網路連接埠或介面群組、然後新增VLAN標記來建立VLAN。

* *編輯*
+
開啟下列其中一個對話方塊：

+
** 編輯乙太網路連接埠對話方塊：可讓您修改乙太網路連接埠設定。
** 編輯VLAN對話方塊：可讓您修改VLAN設定。
** Edit Interface Group（編輯介面群組）對話方塊：可讓您修改介面群組。


+
您只能編輯與廣播網域無關的VLAN。

* *刪除*
+
開啟下列其中一個對話方塊：

+
** 刪除VLAN對話方塊：可讓您刪除VLAN。
** 刪除介面群組對話方塊：可讓您刪除介面群組。


* *重新整理*
+
更新視窗中的資訊。





=== 連接埠清單

您可以將指標移到彩色編碼圖示上、以檢視連接埠的作業狀態：

* 綠色表示連接埠已啟用。
* 紅色表示連接埠已停用。
* *連接埠*
+
顯示實體連接埠、VLAN連接埠或介面群組的連接埠名稱。

* *節點*
+
顯示實體介面所在的節點。

* *廣播網域*
+
顯示連接埠的廣播網域。

* * IPspace*
+
顯示連接埠所屬的IPspace。

* *類型*
+
顯示介面類型、例如介面群組、實體介面、VIP或VLAN。





=== 詳細資料區域

連接埠清單下方的區域會顯示連接埠內容的詳細資訊。

* *詳細資料索引標籤*
+
顯示管理詳細資料和作業詳細資料。

+
在作業詳細資料中、索引標籤會顯示連接埠的健全狀況狀態。連接埠可以正常運作或降級。降級連接埠是發生持續網路波動的連接埠、或是無法連線至同一個廣播網域中任何其他連接埠的連接埠。

+
此外、此索引標籤也會顯示所選連接埠上裝載之網路介面的介面名稱、SVM詳細資料及IP位址詳細資料。也會指出介面是否位於主連接埠。

* *效能索引標籤*
+
顯示乙太網路連接埠的效能指標圖表、包括錯誤率和處理量。

+
變更用戶端時區或叢集時區會影響效能度量圖。您應該重新整理瀏覽器以檢視更新的圖表。





=== 廣播網域索引標籤



=== 命令按鈕

* *建立*
+
開啟「建立廣播網域」對話方塊、可讓您建立新的廣播網域以包含連接埠。

* *編輯*
+
開啟「編輯廣播網域」對話方塊、可讓您修改廣播網域的屬性、例如名稱、MTU大小及相關連接埠。

* *刪除*
+
刪除選取的廣播網域。

* *重新整理*
+
更新視窗中的資訊。





=== 廣播網域清單

* *廣播網域*
+
指定廣播網域的名稱。

* * MTU *
+
指定MTU大小。

* * IPspace*
+
指定IPspace。

* *組合連接埠更新狀態*
+
指定建立或編輯廣播網域時連接埠更新的狀態。連接埠更新中的任何錯誤都會顯示在個別的視窗中、您可以按一下相關的連結來開啟該視窗。





=== 詳細資料區域

廣播網域清單下方的區域會顯示廣播網域中的所有連接埠。在非預設IPspace中、如果廣播網域有更新錯誤的連接埠、則此類連接埠不會顯示在詳細資料區域中。您可以將指標移到彩色編碼圖示上、以檢視連接埠的作業狀態：

* 綠色表示連接埠已啟用。
* 紅色表示連接埠已停用。




=== FC/FCoE和NVMe介面卡索引標籤



=== 命令按鈕

* *編輯*
+
開啟「編輯FC/FCoE和NVMe設定」對話方塊、可讓您修改介面卡的速度。

* *狀態*
+
可讓您將介面卡上線或離線。

* *重新整理*
+
更新視窗中的資訊。





=== FC/FCoE和NVMe介面卡清單

* * WWNN*
+
指定FC/FCoE和NVMe介面卡的唯一識別碼。

* *節點名稱*
+
指定使用介面卡的節點名稱。

* *插槽*
+
指定使用介面卡的插槽。

* * WWPN*
+
指定介面卡的FC全球連接埠名稱（WWPN）。

* *狀態*
+
指定介面卡的狀態是在線上還是離線。

* *速度*
+
指定速度設定為自動或手動。





=== 詳細資料區域

FC/FCoE和NVMe介面卡清單下方的區域會顯示所選介面卡的詳細資訊。

* *詳細資料索引標籤*
+
顯示介面卡詳細資料、例如媒體類型、連接埠位址、資料連結速率、連線狀態、作業狀態、 網路狀態、以及介面卡的速度。

* *效能索引標籤*
+
顯示FC/FCoE和NVMe介面卡的效能指標圖表、包括IOPS和回應時間。

+
變更用戶端時區或叢集時區會影響效能度量圖。您應該重新整理瀏覽器以查看更新的圖表。





=== IPspaces索引標籤



=== 命令按鈕

* *建立*
+
開啟「建立IPspace」對話方塊、可讓您建立新的IPspace。

* *編輯*
+
開啟「編輯IPspace」對話方塊、可讓您重新命名現有的IPspace。

* *刪除*
+
刪除選取的IPspace。

* *重新整理*
+
更新視窗中的資訊。





=== IPspaces清單

* *名稱*
+
指定IPspace的名稱。

* *廣播網域*
+
指定廣播網域。





=== 詳細資料區域

IPspaces清單下方的區域會顯示所選IPspace中的儲存虛擬機器（SVM）清單。
