---
permalink: online-help-96-97/concept_namespace.html 
sidebar: sidebar 
keywords: junction, path, window, system, manager, mount, unmount, flexvol, volume, svm, namespace, online, help, policies, export 
summary: 您可以使用System Manager中的Junction Path（交會路徑）視窗、在FlexVol SVM命名空間中的交會處掛載或卸載。 
---
= System Manager中的「交會路徑」視窗- ONTAP 更新版本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用ONTAP 經典版的《Suse System Manager》（ONTAP 更新版本）中的「Junction Path」（交會路徑）視窗、在FlexVol SVM命名空間的交會處掛載或卸載《SVM》（更新版本）。



== 掛載磁碟區

您可以使用System Manager將磁碟區掛載到儲存虛擬機器（SVM）命名空間的交會處。

.關於這項工作
* 如果您將磁碟區掛載到具有不同於路徑中直接父磁碟區語言設定的交會路徑、NFSv3用戶端將無法存取部分檔案、因為部分字元可能無法正確解碼。
+
如果直接父目錄是根Volume、就不會發生此問題。

* 您只能在SnapLock SVM的根目錄下掛載一個SfNetApp Volume。
* 您無法在SnapLock 一個穩定磁碟區下掛載一般磁碟區。


.步驟
. 按一下「*儲存設備*>*交會路徑*」。
. 從「* SVM*」欄位的下拉式功能表中、選取要掛載磁碟區的SVM。
. 按一下*掛載*、然後選取要掛載的磁碟區。
. *選用：*如果您要變更預設的交會名稱、請指定新名稱。
. 按一下*瀏覽*、然後選取您要掛載磁碟區的交會路徑。
. 按一下「*確定*」、然後按一下「*掛載*」。
. 驗證「*詳細資料*」標籤中的新交會路徑。




== 卸載FlexVol 此功能

您可以使用System Manager中Storage（儲存設備）窗格的Junction Path（交會路徑）選項、從FlexVol 儲存虛擬機器（SVM）命名空間的交會處卸載支援資料區。

.步驟
. 按一下「*儲存設備*>*交會路徑*」。
. 從「* SVM*」欄位的下拉式功能表中、選取您要卸載磁碟區的SVM。
. 選取必須卸載的磁碟區、然後按一下*卸載*。
. 選取確認核取方塊、然後按一下*取消掛載*。




== 變更匯出原則

建立磁碟區時、磁碟區會自動繼承儲存虛擬機器（SVM）根磁碟區的預設匯出原則。您可以使用System Manager變更與磁碟區相關聯的預設匯出原則、以重新定義用戶端對資料的存取。

.步驟
. 按一下「*儲存設備*>*交會路徑*」。
. 從* SVM*欄位的下拉式功能表中、選取您要修改的磁碟區所在的SVM。
. 選取磁碟區、然後按一下*變更匯出原則*。
. 選取匯出原則、然後按一下*變更*。
. 確認「* Junction Path*」視窗中的「*匯出原則*」欄顯示您套用至磁碟區的匯出原則。


.結果
預設匯出原則會取代為您選取的匯出原則。



== 交會路徑視窗

您可以使用Junction Path功能表來管理儲存虛擬機器（SVM）的NAS命名空間。



=== 命令按鈕

* *掛載*
+
開啟「掛載Volume」對話方塊、可讓您將磁碟區掛載至SVM命名空間中的交會處。

* *卸載*
+
開啟「卸載Volume」對話方塊、可讓您從其父Volume卸載Volume。

* *變更匯出原則*
+
開啟「變更匯出原則」對話方塊、可讓您變更與磁碟區相關的現有匯出原則。

* *重新整理*
+
更新視窗中的資訊。





=== 交會路徑清單

* *路徑*
+
指定掛載磁碟區的交會路徑。您可以按一下交會路徑來檢視相關的磁碟區和qtree。

* *儲存物件*
+
指定連接路徑上掛載的磁碟區名稱。您也可以檢視磁碟區所包含的qtree。

* *匯出政策*
+
指定掛載Volume的匯出原則。

* *安全風格*
+
指定磁碟區的安全樣式。可能的值包括UNIX（適用於UNIX模式位元）、NTFS（適用於CIFS ACL）和混合（適用於混合NFS和CIFS權限）。





=== 詳細資料索引標籤

顯示所選磁碟區或qtree的一般資訊、例如名稱、儲存物件類型、掛載物件的交會路徑、以及匯出原則。如果選取的物件是qtree、則會顯示有關空間硬限制、空間軟限制和空間使用量的詳細資料。
