---
permalink: online-help-96-97/reference_disks_window.html 
sidebar: sidebar 
keywords: command, button, disk, window, inventory, detail, online, help 
summary: 您可以使用「磁碟」視窗來檢視儲存系統中的所有磁碟。 
---
= System Manager ONTAP 中的「磁碟」視窗-更新版本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用ONTAP 經典版的「磁碟」視窗（ONTAP 可在更新版本的版本中使用）來檢視儲存系統中的所有磁碟。



== 命令按鈕

* *指派*
+
將磁碟的擁有權指派或重新指派給節點。

+
只有選取磁碟的容器類型為未指派、備援或共用時、才會啟用此按鈕。

* *零備援*
+
清除所有資料、並格式化備用磁碟和陣列LUN。

* *重新整理*
+
更新視窗中的資訊。





== 索引標籤



== 摘要

顯示叢集中磁碟的詳細資訊、包括備用磁碟和指派磁碟的大小。此索引標籤也會以圖形方式顯示HDD的備用磁碟、集合體和根集合體資訊、以及快取磁碟（SSD）的備用磁碟、儲存池中的磁碟、集合體、Flash Pool Aggregate和根集合體等資訊。

若系統具備All Flash Optimized特性設定、則不會顯示HDD面板。

詳細資料面板提供分割區和未分割備用磁碟（磁碟類型、節點、磁碟大小、RPM、Checksum、 可用磁碟數量和備用容量）、格式為表格。



== 庫存

* *名稱*
+
顯示磁碟的名稱。

* * Container類型*
+
顯示磁碟的使用目的。可能的值包括Aggregate、中斷、Foreign、Label Maintenance、維護、 共享、備用、未指派、Volume、未知、 和不受支援。

* *分割區類型*
+
顯示磁碟的分割區類型。

* *節點名稱*
+
顯示包含Aggregate的節點名稱。

+
此欄位僅適用於叢集層級。

* *擁有者*
+
顯示指派此磁碟的主節點名稱。

* *目前擁有者*
+
顯示目前擁有此磁碟的節點名稱。

* *根擁有者*
+
顯示目前擁有此磁碟根分割區的節點名稱。

* *資料擁有者*
+
顯示目前擁有此磁碟資料分割區的節點名稱。

* *資料1擁有者*
+
顯示目前擁有磁碟資料1分割區的節點名稱。

* *資料2擁有者*
+
顯示目前擁有磁碟資料2分割區的節點名稱。

* *儲存資源池*
+
顯示與磁碟相關聯的儲存資源池名稱。

* *類型*
+
顯示磁碟類型。

* *韌體版本*
+
顯示磁碟的韌體版本。

* *模型*
+
顯示磁碟的機型。

* * RPM *
+
顯示選項時磁碟機的有效速度 `raid.mix.hdd.rpm.capacity` 會啟用、並在選項出現時顯示磁碟機的實際速度 `raid.mix.hdd.rpm.capacity` 已停用。

+
此欄位不適用於SSD。

* *有效大小*
+
顯示磁碟上可用的空間。

* *實體空間*
+
顯示磁碟的實體空間總計。

* *機櫃*
+
顯示實體磁碟所在的磁碟櫃。

+
此欄位預設為隱藏。

* *海灣*
+
顯示實體磁碟機櫃內的磁碟櫃。

+
此欄位預設為隱藏。

* *資源池*
+
顯示指派所選磁碟的集區名稱。

+
此欄位預設為隱藏。

* * Checksum *
+
顯示Checksum的類型。

+
此欄位預設為隱藏。

* *載體ID*
+
指定位於指定多磁碟載體內之磁碟的相關資訊。ID為64位元值。

+
此欄位預設為隱藏。





== 詳細目錄區域

詳細目錄索引標籤下方的區域會顯示所選磁碟的詳細資訊、包括有關集合體或磁碟區（若適用）、廠商ID、零位狀態（以百分比表示）、磁碟序號、以及磁碟毀損時的錯誤詳細資料。對於共享磁碟、「Inventory details」（資源清冊詳細資料）區域會顯示所有集合體的名稱、包括根集合體和非根集合體。

*相關資訊*

xref:task_viewing_disk_information.adoc[檢視磁碟資訊]
