---
permalink: online-help-96-97/reference_svm_window.html 
sidebar: sidebar 
keywords: storage, virtual, machine, window, svm, online, help, command, button, peer 
summary: 您可以使用「儲存虛擬機器」視窗來管理儲存虛擬機器（SVM）、並顯示相關資訊。 
---
= System Manager ONTAP 中的Storage Virtual Machines視窗- VMware 9.7及更早版本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用ONTAP 《經典版》（ONTAP 英文版）中的「儲存虛擬機器」視窗（英文版）來管理儲存虛擬機器（SVM）、並顯示相關資訊。

您無法使用System Manager來管理（建立、刪除、啟動或停止）設定用於災難恢復（DR）的SVM。此外、您也無法在應用程式介面中檢視與設定用於災難恢復的SVM相關的儲存物件。



== 命令按鈕

* *建立*
+
開啟「儲存虛擬機器（SVM）設定精靈」、可讓您建立新的SVM。

* *編輯*
+
開啟「編輯儲存虛擬機器」對話方塊、可讓您修改所選SVM的內容、例如名稱服務交換器、名稱對應交換器和Aggregate清單。

* *刪除*
+
刪除選取的SVM。

* *開始*
+
啟動選取的SVM。

* *停止*
+
停止選取的SVM。

* * SVM設定*
+
管理所選SVM的儲存、原則及組態。

* *保護作業*
+
提供下列選項：

+
** *初始化*
+
可讓您初始化SVM關係、以執行從來源SVM到目的地SVM的基準傳輸。

** *更新*
+
可讓您將資料從來源SVM更新至目的地SVM。

** *啟動目的地SVM*
+
可讓您啟動目的地SVM。

** *從來源SVM*重新同步
+
可讓您啟動中斷關係的重新同步。

** *從目的地SVM重新同步（反轉重新同步）*
+
可讓您重新同步從目的地SVM到來源SVM的關係。

** *重新啟動來源SVM*
+
可讓您重新啟動來源SVM。



* *重新整理*
+
更新視窗中的資訊。

* *追蹤檔案存取*
+
可讓您針對指定的使用者名稱、追蹤所選SVM上檔案或共用的存取能力。





== SVM清單

SVM清單會顯示每個SVM的名稱及其允許的傳輸協定。

您只能使用System Manager檢視資料SVM。

* *名稱*
+
顯示 SVM 的名稱。

* *州*
+
顯示SVM狀態、例如執行、啟動、停止或停止。

* *子類型*
+
顯示SVM的子類型、可以是下列其中一種：

+
** 預設
+
指定SVM為資料服務SVM。

** DP目的地
+
指定已設定SVM進行災難恢復。

** 同步來源
+
指定SVM位於MetroCluster 進行SVM組態的主要站台。

** 同步目的地
+
指定SVM位於MetroCluster 恢復運作的站台、以進行功能性設定。



* *允許的傳輸協定*
+
在每個SVM上顯示允許的傳輸協定、例如CIFS和NFS。

* * IPspace*
+
顯示相關SVM的IPspace。

* * Volume類型*
+
在FlexVol 每個SVM上顯示允許的Volume類型、例如Sfingvolume。

* *受保護*
+
顯示SVM是否受到保護。

* *組態狀態*
+
顯示SVM的組態狀態為鎖定或解除鎖定。





== 詳細資料區域

SVM清單下方的區域會顯示所選SVM的詳細資訊、例如允許的磁碟區類型、語言及Snapshot原則。

您也可以設定此SVM上允許的傳輸協定。如果您在建立SVM時尚未設定傳輸協定、可以按一下傳輸協定連結來設定傳輸協定。

您無法使用System Manager設定用於災難恢復的ANSVM傳輸協定。

[NOTE]
====
如果SVM的FCP服務已經啟動、按一下FC/FCoE連結即可開啟「網路介面」視窗。

====
此色彩表示傳輸協定組態的狀態：

|===
| 狀態 | 說明 


 a| 
綠色
 a| 
生命存在且已設定傳輸協定。您可以按一下連結來檢視組態詳細資料。

[NOTE]
====
組態可能已部分完成。不過、服務正在執行中。您可以從「網路介面」視窗建立LIF並完成組態。

====


 a| 
黃色
 a| 
表示下列其中一項：

* 生命存在。服務已建立、但尚未執行。
* 生命存在。未建立服務。
* 服務已建立。生命不存在。




 a| 
灰色
 a| 
未設定傳輸協定。您可以按一下傳輸協定連結來設定傳輸協定。



 a| 
灰色框線
 a| 
傳輸協定授權已過期或遺失。您可以按一下傳輸協定連結、在「授權」頁面中新增授權。

|===
您也可以新增管理介面並檢視詳細資料、例如保護關係、保護原則、NIS網域等。

「*詳細資料*」區域也包含檢視SVM之「公共SSL憑證」的連結。按一下此連結時、您可以執行下列工作：

* 檢視憑證詳細資料、序號、開始日期及到期日。
* 將憑證複製到剪貼簿。
* 以電子郵件傳送憑證詳細資料。




== 對等儲存虛擬機器區域

顯示與所選SVM連接的SVM清單、以及使用對等關係的應用程式詳細資料。
