---
permalink: online-help-96-97/reference_trace_file_access_window.html 
sidebar: sidebar 
keywords: system, manager, commnd, button, trace, file, access, window, online, help, cif, entry, list 
summary: 從System Manager 9.6開始、您可以使用「追蹤檔案存取」視窗來診斷使用CIFS或NFS傳輸協定存取SVM上的檔案和共用時發生的問題。 
---
= System Manager中的「追蹤檔案存取」視窗
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
從ONTAP 「功能區系統管理程式9.6」開始、您可以使用「追蹤檔案存取」視窗來診斷使用CIFS或NFS傳輸協定存取SVM上的檔案和共用時發生的問題。



== 命令按鈕

* *繼續*
+
開始在所選SVM上設定及初始化檔案存取追蹤的程序。

* *傳輸協定*
+
可讓您選取用來存取所選SVM上檔案和共用的傳輸協定、包括CIFS或NFS。

* *進階選項圖示*
+
可讓您指定其他詳細資料、以縮小追蹤範圍。

* *在追蹤結果中顯示*
+
可讓您在「進階選項」對話方塊中指定是否要追蹤結果只顯示遭拒的檔案存取要求、或顯示所有檔案存取要求、包括成功和遭拒的檔案存取要求。

* *開始追蹤*
+
可讓您開始追蹤。結果顯示、在未來60分鐘內提交的檔案存取要求有存取問題。

* *停止追蹤*
+
可讓您停止追蹤。

* *查看權限*
+
可讓您顯示權限。使用CIFS傳輸協定時、您可以顯示有效的檔案和共用權限。使用NFS傳輸協定時、您可以顯示有效的檔案權限。

* *複製到剪貼簿*
+
可讓您將結果表複製到剪貼簿。

* *匯出追蹤結果*
+
可讓您將追蹤結果匯出為以逗號分隔值（.csv)格式的檔案。





== 輸入欄位

* *使用者名稱*
+
您可以輸入收到您要追蹤之檔案存取要求錯誤的使用者名稱。

* *搜尋追蹤結果*
+
您可以在搜尋結果中輸入要尋找的特定資訊、然後按一下* Enter *。

* *用戶端IP位址*
+
在「進階選項」對話方塊中、您可以將用戶端的IP位址指定為其他詳細資料、以縮小追蹤範圍。

* *檔案*
+
在「進階選項」對話方塊中、您可以指定要存取的檔案或檔案路徑、做為額外的詳細資料、以縮小追蹤範圍。



.CIFS傳輸協定追蹤的結果清單
當您指定CIFS傳輸協定時、結果清單會根據您指定的參數、顯示下列追蹤資料。資料會以相反的時間順序顯示。如果您停止追蹤、結果會保留在清單中、直到您開始另一個追蹤為止。

* 共享區：系統嘗試存取的共享區名稱、無論是否成功。
* 路徑：系統嘗試存取的檔案路徑、無論是否成功。
* 用戶端IP位址：起始存取要求的用戶端IP位址。
* 原因：嘗試存取檔案或共用區的成功或失敗原因。
+
[NOTE]
====
當追蹤結果顯示訊息、指出「Synchronize（同步）」、「Read Control（讀取控制）」、「Read Attributes"（讀取屬性）、「Execute（執行）」、「Read EA（讀取EA）」、 「寫入」或「讀取」訊息表示所需的存取權限尚未授予所列的權限集。若要檢視實際權限狀態、您必須使用提供的連結來檢視權限。

====


.NFS 傳輸協定追蹤結果清單
當您指定NFS傳輸協定時、結果清單會根據您指定的參數顯示下列追蹤資料。資料會以相反的時間順序顯示。如果您停止追蹤、結果會保留在清單中、直到您開始另一個追蹤為止。

* 路徑：系統嘗試存取的檔案路徑、無論是否成功。
* 用戶端IP位址：起始存取要求的用戶端IP位址。
* 原因：嘗試存取檔案或共用區的成功或失敗原因。
+
[NOTE]
====
當追蹤結果顯示訊息、指出「Synchronize（同步）」、「Read Control（讀取控制）」、「Read Attributes"（讀取屬性）、「Execute（執行）」、「Read EA（讀取EA）」、 「寫入」或「讀取」訊息表示所需的存取權限尚未授予所列的權限集。若要檢視實際權限狀態、您必須使用提供的連結來檢視權限。

====


*相關資訊*

https://docs.netapp.com/us-en/ontap/smb-admin/index.html["SMB/CIFS管理"]

xref:../nas-multiprotocol-config/index.html[SMB/CIFS與NFS多重傳輸協定組態]
