---
permalink: online-help-96-97/reference_svm_dashboard_window.html 
sidebar: sidebar 
keywords: svm, dashboard, detail, online, help 
summary: 儀表板提供有關儲存虛擬機器（SVM）及其效能的累積性概覽資訊。您可以使用儀表板視窗來檢視與SVM相關的重要資訊、例如設定的傳輸協定、容量即將達到的磁碟區、以及效能。 
---
= System Manager中的SVM儀表板視窗ONTAP -不包括更新版本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
經典版的《經典版》（適用於VMware 9.7及更早版本）儀表板視窗ONTAP 、提供儲存虛擬機器（SVM）及其效能的累積性概覽資訊。ONTAP您可以使用儀表板視窗來檢視與SVM相關的重要資訊、例如設定的傳輸協定、容量即將達到的磁碟區、以及效能。



== SVM詳細資料

此視窗會透過各種面板顯示SVM的詳細資料、例如「傳輸協定狀態」面板、「容量即將到達的磁碟區」面板、「應用程式」面板和「效能」面板。

* *傳輸協定狀態*
+
概述為SVM設定的傳輸協定。您可以按一下傳輸協定名稱來檢視組態。

+
如果未設定傳輸協定、或SVM無法使用傳輸協定授權、您可以按一下傳輸協定名稱來設定傳輸協定或新增傳輸協定授權。

* *容量即將達到容量*
+
顯示容量使用率接近80%以上且需要立即注意或修正行動的磁碟區相關資訊。

* *應用程式*
+
顯示SVM前五大應用程式的相關資訊。您可以根據IOPS（從低到高或從高到低）或容量（從低到高或從高到低）、來檢視前五大應用程式。您必須按一下特定的長條圖、才能檢視應用程式的詳細資訊。對於容量、會顯示總空間、已用空間和可用空間、而對於IOPS、則會顯示IOPS詳細資料。對於L2/L3應用程式、也會顯示延遲指標。

+
[NOTE]
====
應用程式視窗中顯示的已用大小與CLI中使用的大小不一致。

====
+
您可以按一下*檢視詳細資料*、以開啟特定應用程式的「應用程式」視窗。您可以按一下*「檢視所有應用程式」*來檢視SVM的所有應用程式。

+
「應用程式」面板的重新整理時間間隔為一分鐘。

* * SVM效能*
+
顯示SVM中傳輸協定的效能指標、包括延遲和IOPS。

+
如果無法從ONTAP VMware擷取SVM效能的相關資訊、您將無法檢視個別的圖表。在這種情況下、System Manager會顯示特定的錯誤訊息。

+
SVM效能面板的重新整理時間間隔為15秒。


