---
permalink: online-help-96-97/reference_dashboard_window.html 
sidebar: sidebar 
keywords: system, manager, dashboard, window, multiple, panel, online, help 
summary: 儀表板視窗包含多個面板、可提供系統及其效能的累計概覽資訊。 
---
= System Manager儀表板視窗ONTAP -適用於更新版本的更新版本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
經典版的《儀表板視窗ONTAP 》（ONTAP 僅適用於VMware 9.7及更早版本）包含多個面板、可提供系統及其效能的累積性概覽資訊。

您可以使用儀表板視窗來檢視重要警示和通知、集合體和磁碟區的效率和容量、叢集中可用的節點、高可用度（HA）配對中節點的狀態、最活躍的應用程式和物件等相關資訊、 以及叢集或節點的效能指標。

* *警示與通知*
+
以紅色顯示所有警示、例如緊急EMS事件、離線節點詳細資料、毀損的磁碟詳細資料、高風險授權、以及離線網路連接埠詳細資料。以黃色顯示所有通知、例如叢集層級過去24小時內發生的健全狀況監視器通知、中度風險的授權權利、未指派的磁碟詳細資料、移轉的lifs數目、故障的Volume Move作業、 和Volume可在過去24小時內移動需要管理介入的作業。

+
「警示與通知」面板最多會顯示三個警示與通知、顯示「檢視全部」連結。您可以按一下「檢視全部」連結、以檢視警示和通知的詳細資訊。

+
「警示與通知」面板的重新整理時間間隔為一分鐘。

* *叢集概述*
+
顯示接近容量的集合體和磁碟區、叢集或節點的儲存效率、以及高容量的保護詳細資料。

+
Capacity（容量）索引標籤會依已用空間的遞減順序、顯示接近容量的最上層線上集合體。

+
當您在「Volumes exeing used capees of」（超過使用容量的磁碟區）欄位中輸入有效值時、容量索引標籤會提供使用容量最高的磁碟區數目連結。它也會顯示叢集中可用的非作用中（冷）資料量。

+
「效率」索引標籤會顯示叢集或節點的儲存效率節約效益。您可以檢視已使用的邏輯空間總計、已使用的實體空間總計、以及整體節約效益。您可以選取叢集或特定節點來檢視儲存效率節約效益。對於System Manager 9.5、Snapshot複本所使用的空間不包含在已使用的邏輯空間總量、已使用的實體空間總量及整體節約成本等值中。不過、從System Manager 9.6開始、Snapshot複本所使用的空間會包含在已使用的邏輯空間總量、已使用的實體空間總量及整體節約成本等值中。

+
「叢集概觀」面板的重新整理時間間隔為15分鐘。

+
Protection（保護）選項卡顯示有關未定義保護關係的整個叢集磁碟區的資訊。只FlexVol 會顯示符合下列條件的「僅限」功能區和FlexGroup 「僅限」資料區：

+
** 這些磁碟區是RW磁碟區、而且處於線上狀態。
** 包含磁碟區的Aggregate已上線。
** 磁碟區具有保護關係、尚未初始化。
您可以瀏覽至「Volumes（磁碟區）」視窗、檢視未定義保護關係的磁碟區。


+
「Protection（保護）」索引標籤也會顯示前五大SVM、這些SVM的磁碟區數量最多、而且這些磁碟區沒有定義保護關係。

* *節點*
+
顯示叢集中可用節點的數量和名稱、以及HA配對中節點的狀態的圖示。您應該將游標放在節點的圖示上、以檢視HA配對中節點的狀態。

+
您可以使用節點連結來檢視所有節點的詳細資訊。您也可以按一下圖示表示、檢視節點的模型、以及節點中可用的集合體、儲存池、磁碟櫃和磁碟數量。您可以使用「管理節點」連結來管理節點。您可以使用「管理HA」連結來管理HA配對中的節點。

+
節點面板的重新整理時間間隔為15分鐘。

* *應用程式與物件*
+
您可以使用「應用程式與物件」面板來顯示叢集中的應用程式、用戶端和檔案相關資訊。

+
應用程式索引標籤會顯示叢集前五大應用程式的相關資訊。您可以根據IOPS和延遲（從低到高或從高到低）或容量（從低到高或從高到低）來檢視前五大應用程式。

+
您應該按一下特定的長條圖、以檢視應用程式的詳細資訊。容量的總空間、已用空間和可用空間會顯示、IOPS的IOPS詳細資料會顯示、延遲詳細資料則會顯示。

+
您可以按一下*檢視詳細資料*、以開啟特定應用程式的「應用程式」視窗。

+
物件索引標籤會顯示叢集中前五個作用中用戶端和檔案的相關資訊。您可以根據IOPS或處理量來檢視前五大作用中用戶端和檔案。

+
[NOTE]
====
此資訊僅會針對CIFS和NFS傳輸協定顯示。

====
+
「應用程式與物件」面板的重新整理時間間隔為一分鐘。

* *效能*
+
根據延遲、IOPS及處理量、顯示叢集的平均效能指標、讀取效能指標及寫入效能指標。預設會顯示平均效能指標。您可以按一下「讀取」或「寫入」、分別檢視讀取效能指標或寫入效能指標。您可以檢視叢集或節點的效能指標。

+
如果無法從ONTAP VMware View擷取叢集效能的相關資訊、您將無法檢視個別的圖表。在這種情況下、System Manager會顯示特定的錯誤訊息。

+
「效能」面板中圖表的重新整理時間間隔為15秒。





== 使用儀表板監控叢集

System Manager中的儀表板可讓您監控叢集的健全狀況和效能。您也可以使用儀表板來識別硬體問題和儲存組態問題。

.步驟
. 按一下*儀表板*索引標籤、即可檢視健全狀況與效能儀表板面板。

