---
permalink: online-help-96-97/reference_application_provisioning_settings.html 
sidebar: sidebar 
keywords: application, provisioning, setting, microsoft, sql, database, applications, san, mongodb, oracle, host, access, initiator, sap, hana, smb 
summary: 設定資料庫、伺服器或虛擬桌面的基本或增強範本時、您必須向System Manager提供詳細資料。在佈建應用程式之後、您可以編輯詳細資料並指定調整大小（僅限增加大小）。本節說明每個範本中的欄位。只會顯示資源配置或編輯特定應用程式設定所需的欄位。 
---
= System Manager中的應用程式資源配置設定- ONTAP 更新版本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必須在ONTAP 以經典版的《經典版》（ONTAP 適用於更新版本的版本）設定資料庫、伺服器或虛擬桌面的基本或增強範本時、提供詳細資料。在佈建應用程式之後、您可以編輯詳細資料並指定調整大小（僅限增加大小）。本節說明每個範本中的欄位。只會顯示資源配置或編輯特定應用程式設定所需的欄位。



== 透過SAN的Microsoft SQL資料庫應用程式詳細資料

您可以輸入下列資訊、以便透過SAN配置Microsoft SQL資料庫應用程式或編輯設定：

* *資料庫名稱*
+
必填：您正在設定的資料庫名稱；此字串會在為每個資料庫配置儲存資源時做為前置詞。

* *資料庫大小*
+
必填：資料庫大小、單位為MB、GB、TB或PB。

* *資料庫服務層級* ONTAP
+
必填：資料庫的服務層級。

* *日誌大小*
+
必填：以MB、GB、TB或PB為單位的資料庫記錄大小。

* *適用於Log*的服務層級ONTAP
+
必填：記錄的服務層級。

* *坦普資料庫*
+
必填：以MB、GB、TB或PB為單位的Tempdb資料庫大小。

* *匯出傳輸協定*
+
必填：匯出傳輸協定為SAN

* *伺服器核心數（在SQL伺服器上）*
+
表示資料庫伺服器上的CPU核心數量、增量為2。

* *跨HA控制器節點*
+
指定是否應跨高可用度節點配對建立儲存物件。





== SAP HANA資料庫資源配置詳細資料

* * Active SAP HANA節點*
+
作用中SAP HANA節點的數量。節點數量上限為16個。

* *每個HANA節點的記憶體大小*
+
單一SAP HANA節點的記憶體大小。

* *每個HANA節點的資料磁碟大小*
+
每個節點的資料磁碟大小。

+
[NOTE]
====
如果設為0、則會使用上方的記憶體大小欄位來計算資料區域的大小。

====




== SMB上的Microsoft SQL資料庫應用程式詳細資料

您可以輸入下列資訊、以便透過SMB配置Microsoft SQL資料庫應用程式、或編輯設定：

* *資料庫名稱*
+
必填：您正在設定的資料庫名稱；此字串會在為每個資料庫配置儲存資源時做為前置詞。

* *資料庫大小*
+
必填：資料庫大小、單位為MB、GB、TB或PB。

* *資料庫服務層級*
+
必填：資料庫的服務層級。

* *伺服器核心數（在SQL伺服器上）*
+
表示資料庫伺服器上的CPU核心數量、增量為2。

* *日誌大小*
+
必填：以MB、GB、TB或PB為單位的資料庫記錄大小。

* *記錄服務層級*
+
必填：記錄的服務層級。

* *為Tempdb*提供資源
+
必填：指出是否已配置Tempdb。

* *匯出傳輸協定*
+
必填：匯出傳輸協定為SMB或SAN。

+
只有在叢集獲得CIFS授權（已針對SVM設定）時、才能選擇SMB。

* *授予使用者存取權*
+
必填：應用程式的存取層級。

* *權限*
+
必填：應用程式的權限等級。





== SQL Server帳戶的詳細資料

您可以輸入下列資訊、以提供對SQL Server帳戶的完整控制權：

[NOTE]
====
系統會授予安裝帳戶 `SeSecurityPrivilege`。

====
* * SQL Server服務帳戶*
+
必要：這是現有的網域帳戶；請指定為 `domain\user`。

* * SQL Server代理服務帳戶*
+
選用：如果已設定SQL伺服器代理程式服務、請以網域\使用者格式指定此網域帳戶。





== Oracle資料庫應用程式詳細資料

您可以輸入下列資訊來配置Oracle資料庫應用程式或編輯設定：

* *資料庫名稱*
+
必填：您正在設定的資料庫名稱；此字串會在為每個資料庫配置儲存資源時做為前置詞。

* *資料檔案大小*
+
必填：資料檔案的大小、單位為MB、GB、TB或PB。

* *資料檔案的服務層級* ONTAP
+
必填：資料檔案的服務層級。

* *重做記錄群組大小*
+
必填：重作記錄群組的大小、單位為MB、GB、TB或PB。

* *重做記錄群組的服務層級* ONTAP
+
必填：重作記錄群組的服務層級。

* *歸檔日誌大小*
+
必填：歸檔記錄的大小、單位為MB、GB、TB或PB。

* *歸檔記錄的服務層級* ONTAP
+
必填：歸檔群組的服務層級。

* *匯出傳輸協定*
+
匯出傳輸協定：SAN或NFS

* *啟動器*
+
啟動器群組中啟動器（WWPN或IQN）的以逗號分隔的清單。

* *授予主機存取權*
+
提供應用程式存取權的主機名稱。





== MongoDB應用程式詳細資料

您可以輸入下列資訊來配置MongoDB應用程式或編輯設定：

* *資料庫名稱*
+
必填：您正在設定的資料庫名稱；此字串會在為每個資料庫配置儲存資源時做為前置詞。

* *資料集大小*
+
必填：資料檔案的大小、單位為MB、GB、TB或PB。

* *資料集的服務層級* ONTAP
+
必填：資料檔案的服務層級。

* *複寫係數*
+
必填：複製次數。

* *主主機對應*
+
必填：主要主機的名稱。

* *複本主機1*的對應
+
必填：第一個主機複本的名稱。

* * 複本主機的對應 *
+
必填：第二個主機複本的名稱。





== 虛擬桌面應用程式的詳細資料

您可以輸入下列資訊來配置虛擬桌面基礎架構（VDI）或編輯設定：

* *平均桌面大小（用於SAN虛擬桌面）*
+
這是用來判斷每個磁碟區的精簡配置大小、單位為MB、GB、TB或PB。

* *桌面大小*
+
這是用來判斷應以MB、GB、TB或PB為單位來配置的磁碟區大小。

* *適用於桌面*的服務層級ONTAP
+
必填：資料檔案的服務層級。

* *桌面數量*
+
此數字用於判斷所建立的磁碟區數量。

+
[NOTE]
====
這不用於配置虛擬機器。

====
* *選擇Hypervisor *
+
用於這些磁碟區的Hypervisor；Hypervisor會決定正確的資料存放區傳輸協定。選項包括VMware、Hyper-V或XenServer / KVM。

* *桌面持續性*
+
決定桌面是持續性的還是非持續性的。選取桌面持續性會設定磁碟區的預設值、例如Snapshot排程和後置處理重複資料刪除原則。所有磁碟區的內嵌效率預設為啟用。

+
[NOTE]
====
這些原則可在資源配置後手動修改。

====
* *資料存放區首碼*
+
輸入的值用於產生資料存放區名稱、以及匯出原則名稱或共用名稱（若適用）。

* *匯出傳輸協定*
+
匯出傳輸協定：SAN或NFS

* *啟動器*
+
啟動器群組中啟動器（WWPN或IQN）的以逗號分隔的清單。

* *授予主機存取權*
+
提供應用程式存取權的主機名稱。





== 啟動器詳細資料

您可以輸入下列資訊來設定啟動器：

* *啟動器群組*
+
您可以選取現有群組或建立新群組。

* *啟動器群組名稱*
+
新啟動器群組的名稱。

* *啟動器*
+
啟動器群組中啟動器（WWPN或IQN）的以逗號分隔的清單。



下列欄位僅適用於_SAP HANA資源配置：

* *啟動器作業系統類型*
+
新啟動器群組的作業系統類型。

* * FCP Portset*
+
啟動器群組繫結的FCP連接埠集。





== 主機存取組態

您可以輸入下列資訊來設定主機對磁碟區的存取：

* * Volume匯出組態*
+
選取要在建立期間套用至磁碟區的匯出原則。選項包括：

+
** 全部允許
+
此選項表示已建立匯出規則、允許對任何用戶端進行讀寫存取。

** 建立自訂原則
+
此選項可讓您指定要接收讀寫存取權的主機IP位址清單。



+
[NOTE]
====
您可以稍後使用System Manager工作流程修改Volume匯出原則。

====
* *主機IP位址*
+
這是以逗號分隔的IP位址清單。

+
[NOTE]
====
對於NFS型系統、會使用資料存放區前置碼建立新的匯出原則、並在其中建立規則、以便存取IP清單。

====




== 應用程式詳細資料

新增應用程式時、您可以在「應用程式詳細資料」視窗的「*總覽*」標籤中檢視組態設定。根據所設定的應用程式類型、會顯示NFS或CIFS存取與權限等其他詳細資料。

* *類型*
+
這是建立的一般應用程式、資料庫或虛擬基礎架構類型。

* * SVM*
+
建立應用程式的伺服器虛擬機器名稱。

* *大小*
+
Volume的總大小。

* *可用*
+
Volume中目前可用的空間量。

* *保護*
+
設定的資料保護類型。



您可以展開「*元件*」和「*磁碟區*」窗格、以取得有關已用空間、IOPs和延遲的效能詳細資料。

[NOTE]
====
「元件」窗格中顯示的「已用」大小與CLI中顯示的「已用」大小不同。

====