---
permalink: online-help-96-97/reference_cluster_update_window.html 
sidebar: sidebar 
keywords: online, help, cluster, update, window, tab, update, command, button, history, tab 
summary: 您可以使用「叢集更新」視窗、不中斷營運地執行自動化叢集更新、也可以不中斷地更新單節點叢集。 
---
= 使用System Manager的叢集更新視窗ONTAP -更新版本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用「叢集更新」視窗、不中斷營運地執行自動化叢集更新、也可以使用ONTAP 經典版的《支援還原系統管理程式》（ONTAP 更新版本於更新版本的更新版本）來中斷單節點叢集的更新。



== 索引標籤

* *叢集更新*
+
可讓您在不中斷營運的情況下執行自動化叢集更新、或是以不中斷營運的方式更新單節點叢集。

* *更新歷史記錄*
+
顯示先前叢集更新的詳細資料。





== 叢集更新索引標籤

「叢集更新」索引標籤可讓您在不中斷營運的情況下執行自動化叢集更新、或是以中斷營運的方式更新單節點叢集。



== 命令按鈕

* *重新整理*
+
更新視窗中的資訊。

* *選擇*
+
您可以選取更新的軟體映像版本。

+
** 叢集版本詳細資料：顯示目前使用的叢集版本、以及節點或高可用度（HA）配對的版本詳細資料。
** 可用的軟體映像：可讓您選取現有的軟體映像進行更新。
+
或者，您也可以從 NetApp 支援網站下載軟體映像檔，然後新增映像檔以進行更新。



* *驗證*
+
您可以根據更新的軟體映像版本來檢視及驗證叢集。更新前驗證會檢查叢集是否處於準備好進行更新的狀態。如果驗證完成時發生錯誤、表格會顯示各種元件的狀態、以及錯誤所需的修正行動。

+
您只能在驗證成功完成時執行更新。

* *更新*
+
您可以將叢集中的所有節點或叢集中的HA配對、更新為所選版本的軟體映像。更新進行中時、您可以選擇暫停更新、然後取消或繼續更新。

+
如果發生錯誤、更新會暫停、並顯示錯誤訊息及補救步驟。您可以選擇在執行補救步驟之後繼續更新、或是取消更新。當更新成功完成時、您可以使用節點名稱、正常運作時間、狀態和ONTAP 版本來檢視表格。





== 更新歷程記錄索引標籤

顯示叢集更新歷程記錄的詳細資料。



== 更新歷程記錄清單

* *映像版本*
+
指定ONTAP 節點要更新的版本的ImageImage。

* *安裝於*的軟體更新
+
指定安裝更新的磁碟類型。

* *狀態*
+
指定軟體映像更新的狀態（無論更新是否成功或取消）。

* *開始時間*
+
指定更新啟動的時間。

* *完成時間*
+
指定更新完成的時間。

+
此欄位預設為隱藏。

* *更新所需時間*
+
指定更新完成所需的時間。

* *舊版*
+
指定ONTAP 更新之前節點的版本。

* *更新版本*
+
指定ONTAP 更新後節點的版本。


