---
permalink: online-help-96-97/reference_protection_window.html 
sidebar: sidebar 
keywords: command, buttons, protection, window, relationship, vault, mirror, online, help, ls 
summary: 您可以使用「保護」視窗來建立及管理鏡射關係、資料庫關係、鏡射與資料庫關係、以及顯示這些關係的詳細資料。「Protection（保護）」視窗不會顯示負載共享（LS）關係和轉換資料保護（TDP）關係。 
---
= System Manager的保護範圍- ONTAP 不含更新版本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用Protection視窗搭配ONTAP 經典版的《經典版》（ONTAP 適用於更新版本的版本）來建立及管理鏡射關係、資料庫關係、鏡射與資料庫關係、並顯示這些關係的詳細資料。「Protection（保護）」視窗不會顯示負載共享（LS）關係和轉換資料保護（TDP）關係。



== 命令按鈕

* *建立*
+
開啟「建立保護關係」對話方塊、您可以使用此對話方塊從目的地Volume建立鏡射關係、資料庫關係、或鏡射與資料保險箱關係。

+
System Manager不會在「Create Protection Relationship」（建立保護關係）對話方塊中、顯示任何設定為災難恢復（DR）的儲存虛擬機器（SVM）。

* *編輯*
+
開啟「編輯保護關係」對話方塊、您可以使用此對話方塊來編輯關聯的排程和原則。

+
對於資料保險箱關係、鏡射與資料保險箱關係、或是版本彈性的鏡射關係、您可以修改原則類型來修改關係類型。

* *刪除*
+
開啟「刪除保護關係」對話方塊、您可以使用此對話方塊來刪除關係。

* *營運*
+
顯示可在保護關係上執行的作業。

* *重新整理*
+
更新視窗中的資訊。





== 保護關係清單

* *來源儲存虛擬機器*
+
顯示包含資料在關聯中鏡射或資料保存所在之磁碟區的SVM。

* *來源Volume *
+
顯示關聯中的資料鏡射或資料保存所在的磁碟區。

* *目的地Volume *
+
顯示關聯中資料鏡射或資料保存的磁碟區。

* *健康*
+
顯示關係是否健全。

* *物件類型*
+
顯示關係的物件類型、例如Volume、FlexGroup S動地 或SVM。

* *關係狀態*
+
顯示關聯狀態、例如Snap鏡 射、未初始化或中斷。

* *傳輸狀態*
+
顯示關係的狀態。

* *關係類型*
+
顯示關係類型、例如鏡射、資料保險箱或鏡射及資料保險箱。

* *延遲時間*
+
延遲時間是指成功傳輸至目的地系統的上一個Snapshot複本目前時間與時間戳記之間的差異。除非來源和目的地系統上的時鐘未同步、否則延遲時間一律至少會與上次成功傳輸的時間長度相同。時區差異會自動計算成延遲時間。

* *原則名稱*
+
顯示指派給關係的原則名稱。

* *原則類型*
+
顯示指派給關係的原則類型。原則類型可以是StrictSync、Sync、非同步鏡射、非同步Vault或非同步鏡射Vault。





== 詳細資料區域

* *詳細資料索引標籤*
+
顯示所選關係的一般資訊、例如來源叢集和目的地叢集、資料傳輸率、關係狀態、網路壓縮比率的詳細資料、資料傳輸狀態、目前資料傳輸類型、上次資料傳輸類型、最新Snapshot複本、 以及最新Snapshot複本的時間戳記。

* *原則詳細資料索引標籤*
+
顯示指派給所選保護關係之原則的詳細資料。此索引標籤也會顯示來源Volume中符合指定標籤的SnapMirror標籤和Snapshot複本排程。

* * Snapshot複本索引標籤*
+
顯示所選保護關係的Snapshot複本數、以及最新Snapshot複本的時間戳記、以及SnapMirror標籤屬性。


