---
permalink: online-help-96-97/task_delegating_administration_to_svm_administrators.html 
sidebar: sidebar 
keywords: online, help, delegate, administration, svm, administrator 
summary: 在設定具有基本網路組態的功能性儲存虛擬機器（SVM）或SVM之後、您可以選擇性地將SVM的管理委派給SVM管理員。 
---
= 利用System Manager ONTAP -更新版本的版本、將管理委派給SVM系統管理員
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用ONTAP 經典版的經典版（ONTAP 僅適用於支援支援的版本）、在設定功能性儲存虛擬機器（SVM）或SVM（具備基本網路組態）之後、選擇性地將SVM的管理委派給SVM管理員。

.關於這項工作
SVM系統管理員無法使用System Manager來管理委派的SVM。系統管理員只能使用命令列介面（CLI）來管理。

.步驟
. 在 * 管理員詳細資料 * 區段中、設定的密碼 `vsadmin` 使用者帳戶。
. 如果您想要專屬的LIF用於SVM管理、請選取*「Create a LIF for SVM management *（為SVM管理*建立LIF）」、然後指定網路詳細資料。
+
SAN傳輸協定需要專用的SVM管理LIF、因為其中的資料與管理傳輸協定無法共用相同的LIF。SVM管理生命區只能在資料連接埠上建立。

. 指定網路詳細資料、包括子網路詳細資料、以建立iSCSI LIF：
+
|===
| 如果您想要... | 然後... 


 a| 
使用子網路指定IP位址
 a| 
.. 選擇*使用子網路*。
.. 在「新增詳細資料」對話方塊中、選取必須指派IP位址的子網路。
+
對於叢集間的LIF、只會顯示與所選IPspace相關聯的子網路。

.. 如果您要指派特定IP位址給介面、請選取*使用特定IP位址*、然後輸入IP位址。
+
如果IP位址不在子網路範圍內、您指定的IP位址就會新增至子網路。

.. 按一下「*確定*」。




 a| 
無需使用子網路、即可手動指定IP位址
 a| 
.. 選擇*不含子網路*。
.. 在「新增詳細資料」對話方塊中、執行下列步驟：
+
... 指定IP位址和網路遮罩或字首。
... 選用：指定閘道。
... 如果您不想使用「目的地」欄位的預設值、請指定新的目的地值。
+
如果您未指定自訂值、「目的地」欄位會根據IP位址的系列、填入預設值。

+
如果路由不存在、系統會根據閘道和目的地自動建立新路由。



.. 按一下「*確定*」。


|===
. 指定用於建立資料LIF的連接埠：
+
.. 按一下*瀏覽*。
.. 從「選取網路連接埠或介面卡」對話方塊中選取連接埠。
.. 按一下「*確定*」。




.結果
。 `vsadmin` 帳戶已解除鎖定、並使用密碼進行設定。

的預設存取方法 `vsadmin` 帳戶為 ONTAP API `(ontapi)` 和 SSH `(ssh)`。SVM管理員可以使用管理IP位址登入儲存系統。



== 接下來該怎麼做

您必須使用「編輯儲存虛擬機器」對話方塊、將Aggregate指派給SVM。

[NOTE]
====
如果SVM沒有任何指派的集合體、SVM管理員就無法建立磁碟區。

====