---
permalink: online-help-96-97/task_creating_initiator_groups.html 
sidebar: sidebar 
keywords: create, initiator, group, system, manager, lun, online, help, manage, delete, edit, add 
summary: 您可以使用System Manager建立啟動器群組。啟動器群組可讓您控制主機對特定LUN的存取。您可以使用連接埠集來限制啟動器可以存取的生命期。 
---
= 使用System Manager（ONTAP 系統管理程式）管理啟動器群組-更新版本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用ONTAP 經典版的《經典版》（ONTAP 僅適用於更新版本的版本）來管理啟動器群組。啟動器群組可讓您控制主機對特定LUN的存取。您可以使用連接埠集來限制啟動器可以存取的生命期。



== 建立啟動器群組

.步驟
. 按一下「*儲存設備*>* LUN*」。
. 在「*啟動器群組*」索引標籤中、按一下「*建立*」。
. 在「*建立啟動器群組*」對話方塊的「*一般*」索引標籤中、指定群組的啟動器群組名稱、作業系統、主機別名、連接埠集及支援的傳輸協定。
. 按一下「 * 建立 * 」。




== 刪除啟動器群組

您可以使用System Manager中的「啟動器群組」索引標籤來刪除啟動器群組。

.開始之前
所有對應至啟動器群組的LUN都必須手動取消對應。

.步驟
. 按一下「*儲存設備*>* LUN*」。
. 在*啟動器群組*索引標籤中、選取您要刪除的一或多個啟動器群組、然後按一下*刪除*。
. 按一下*刪除*。
. 驗證您刪除的啟動器群組不再顯示在*啟動器群組*索引標籤中。




== 新增啟動器

您可以使用System Manager將啟動器新增至啟動器群組。當LUN所屬的啟動器群組對應至該LUN時、啟動器會提供LUN存取權。

.步驟
. 按一下「*儲存設備*>* LUN*」。
. 在「* LUN管理*」索引標籤中、選取您要新增啟動器的啟動器群組、然後按一下「*編輯*」。
. 在*編輯啟動器群組*對話方塊中、按一下*啟動器*。
. 按一下「 * 新增 * 」。
. 指定啟動器名稱、然後按一下「*確定*」。
. 按一下*儲存並關閉*。




== 從啟動器群組刪除啟動器

您可以使用System Manager中的「啟動器群組」索引標籤來刪除啟動器。若要從啟動器群組中刪除啟動器、您必須取消啟動器與啟動器群組的關聯。

.開始之前
所有對應至啟動器群組的LUN、如果其中包含您要刪除的啟動器、則必須手動取消對應。

.步驟
. 按一下「*儲存設備*>* LUN*」。
. 在*啟動器群組*索引標籤中、選取您要從中刪除啟動器的啟動器群組、然後按一下*編輯*。
. 在*編輯啟動器群組*對話方塊中、按一下*啟動器*索引標籤。
. 從文字方塊中選取並刪除啟動器、然後按一下「*儲存*」。
+
啟動器與啟動器群組無關聯。



*相關資訊*

xref:reference_luns_window.adoc[LUN視窗]
