---
permalink: online-help-96-97/task_updating_cluster_nondisruptively.html 
sidebar: sidebar 
keywords: nondisruptive, upgrades, NDU, cluster, system, manager, online, help 
summary: 您可以使用System Manager、將執行ONTAP 版本不中斷存取ONTAP 用戶端資料的高可用度（HA）配對中的叢集或個別節點、更新為特定版本的BIOS軟體、而不會中斷存取用戶端資料。 
---
= 使用System Manager ONTAP （系統管理程式）更新叢集、無需中斷營運-更新版本9.7及更早版本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用ONTAP 經典版的《經典版》（ONTAP 適用於更新版本的版本）、將執行ONTAP 版本為更新版本為特定ONTAP 版本的更新叢集或個別節點的高可用度（HA）配對、而不中斷用戶端資料的存取。

.開始之前
* 所有節點都必須成對使用HA。
* 所有節點都必須正常運作。
* 您必須將軟體映像檔從 NetApp 支援網站複製到網路上的 HTTP 伺服器或 FTP 伺服器，以便節點能夠存取該映像檔。
+
link:task_obtaining_ontap_software_images.html["取得ONTAP 軟體映像"]



.關於這項工作
* 如果您在更新裝載叢集管理LIF的節點時、嘗試從System Manager執行其他工作、可能會顯示錯誤訊息。
+
您必須等待更新完成、才能執行任何作業。

* 針對節點少於八個的叢集執行循環更新、並針對節點超過八個的叢集執行批次更新。
+
在循環更新中、叢集中的節點會一次更新一個。在批次更新中、會平行更新多個節點。

* 您可以在不中斷營運的情況ONTAP 下、將整個過程的更新從單一長期服務（LTS）版本更新至下一個LTS版本（LTS +1）。
+
例如ONTAP 、如果版本為LTS的版本為BIOS 9.1和ONTAP 更新版本、您就可以不中斷地將叢集從ONTAP Update 9.1更新為ONTAP 更新版本9.3。

* 從System Manager 9.6開始、如果NVMe傳輸協定是在System Manager 9.5中設定、而您是從System Manager 9.5升級到System Manager 9.6、則您不再有90天的寬限期、可以在沒有授權的情況下使用NVMe傳輸協定。如果您將ONTAP 寬限期從更新為9.6版時生效、寬限期必須更換為有效的NVMeoF授權、才能繼續使用NVMe功能。
+
此功能不適用於MetroCluster 不完整的組態。

* 如果未在System Manager 9.5中設定NVMe傳輸協定、且您從System Manager 9.5更新至System Manager 9.6、則不會提供寬限期、您必須安裝NVMe授權才能使用NVMe傳輸協定。
+
此功能不適用於MetroCluster 不完整的組態。

* 從ONTAP 使用支援功能支援的9.5開始、HA配對中的每個節點必須使用NVMe傳輸協定、至少設定一個NVMe LIF。您也可以為每個節點建立最多兩個NVMe LIF。當您升級ONTAP 至ENFS9.5時、必須確保使用NVMe傳輸協定、為HA配對中的每個節點定義至少一個NVMe LIF。


.步驟
. 按一下*組態*>*叢集*>*更新*。
. 在*更新*索引標籤中、新增映像或選取可用的映像。
+
|===
| 如果您想要... | 然後... 


 a| 
從本機用戶端新增軟體映像
 a| 
.. 按一下*從本機用戶端*新增。
.. 搜尋軟體映像、然後按一下*「Open*（開啟*）」。




 a| 
從 NetApp 支援網站新增軟體映像檔
 a| 
.. 按一下「*從伺服器新增*」。
.. 在「Add a New Software Image（新增軟體映像檔）」對話方塊中，輸入您儲存從 NetApp 支援網站下載之映像檔的 HTTP 伺服器或 FTP 伺服器的 URL。
+
對於匿名FTP、您必須在中指定URL `+ftp://anonymous@ftpserver+` 格式。

.. 按一下「 * 新增 * 」。




 a| 
選取可用的映像
 a| 
選擇所列的其中一個影像。

|===
. 按一下「*驗證*」執行更新前驗證檢查、以驗證叢集是否已準備好進行更新。
+
驗證作業會檢查叢集元件、以驗證更新是否可在不中斷營運的情況下完成、然後顯示任何錯誤或警告。它也會顯示您在更新軟體之前必須執行的任何必要補救行動。

+
[NOTE]
====
在繼續更新之前、您必須針對錯誤執行所有必要的補救行動。雖然您可以忽略警告的補救行動、但最佳做法是在繼續更新之前、先執行所有的補救行動。

====
. 單擊 * 下一步 * 。
. 按一下 * 更新 * 。
+
再次執行驗證。

+
** 驗證完成後、表格會顯示任何錯誤和警告、以及任何必要的補救行動、然後再繼續進行。
** 如果驗證完成時出現警告、您可以選擇*繼續更新並顯示警告*核取方塊、然後按一下*繼續*。
驗證完成且更新正在進行時、更新可能因為錯誤而暫停。您可以按一下錯誤訊息來檢視詳細資料、然後在繼續更新之前執行補救行動。


+
更新成功完成後、節點會重新開機、並重新導向至System Manager登入頁面。如果節點重新開機需要很長時間、您必須重新整理瀏覽器。

. 登入System Manager、按一下*組態*>*叢集*>*更新*>*更新歷程記錄*、然後檢視詳細資料、以確認叢集已成功更新至所選版本。


*相關資訊*

xref:concept_how_you_update_cluster_nondisruptively.adoc[如何在不中斷營運的情況下更新叢集]
