---
permalink: online-help-96-97/task_updating_single_node_clusters.html 
sidebar: sidebar 
keywords: update, singe, node, cluster, system, manager, online, help 
summary: 您可以使用System Manager來更新單節點叢集。 
---
= 使用System Manager更新單節點叢集- ONTAP 僅需更新版本即可
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用ONTAP 經典版的《經典版》（ONTAP 僅適用於更新版本的版本）來更新單節點叢集。

.開始之前
* 叢集必須執行ONTAP 的是更新版本的版本。
* 您必須將軟體映像檔從 NetApp 支援網站複製到網路上的 HTTP 伺服器、網路上的 FTP 伺服器，或是本機系統，以便節點能夠存取該映像檔。
+
link:task_obtaining_ontap_software_images.html["取得ONTAP 軟體映像"]



.關於這項工作
* 從System Manager 9.5開始、您可以使用雙套裝MetroCluster 的BIOS組態來更新單節點叢集。
+
您必須在兩個站台上執行此作業。

* 在MetroCluster 不中斷營運的情況下、在不中斷的情況下更新單節點叢集。
+
叢集重新開機時、System Manager使用者介面無法使用。

* 在System Manager 9.4及更新版本中、您可以在非MetroCluster組態中更新單節點叢集。
+
在非MetroCluster組態中更新單節點叢集會造成中斷。更新進行中時、用戶端資料無法使用。

* 如果您在更新裝載叢集管理LIF的節點時嘗試執行其他工作、可能會顯示錯誤訊息。
+
您必須等待更新完成、才能執行任何作業。

* 如果NVMe傳輸協定是在System Manager 9.4中設定、而您是從System Manager 9.4更新到System Manager 9.5、則NVMe傳輸協定將在90天的寬限期內提供、無需授權。
+
此功能不適用於MetroCluster 不完整的組態。

* 如果未在System Manager 9.5中設定NVMe傳輸協定、且您從System Manager 9.5更新至System Manager 9.6、則不會提供寬限期、您必須安裝NVMe授權才能使用NVMe傳輸協定。
+
此功能不適用於MetroCluster 不完整的組態。



.步驟
. 按一下*組態*>*叢集*>*更新*。
. 在*叢集更新*索引標籤中、新增軟體映像或選取可用的軟體映像。
+
|===
| 如果您想要... | 然後... 


 a| 
從本機用戶端新增軟體映像
 a| 
.. 按一下*從本機用戶端*新增。
.. 搜尋軟體映像、然後按一下*「Open*（開啟*）」。




 a| 
從 NetApp 支援網站新增軟體映像檔
 a| 
.. 按一下「*從伺服器新增*」。
.. 在「Add a New Software Image（新增軟體映像檔）」對話方塊中，輸入您儲存從 NetApp 支援網站下載之映像檔的 HTTP 伺服器或 FTP 伺服器的 URL。
+
對於匿名FTP、您必須在中指定URL `+ftp://anonymous@ftpserver+` 格式。

.. 按一下「 * 新增 * 」。




 a| 
選取可用的映像
 a| 
選擇所列的其中一個影像。

|===
. 按一下「*驗證*」執行更新前驗證檢查、以驗證叢集是否已準備好進行更新。
+
驗證作業會檢查叢集元件、以驗證是否可以完成更新、然後顯示任何錯誤或警告。驗證作業也會顯示您在更新軟體之前必須執行的任何必要補救行動。

+
[NOTE]
====
在繼續更新之前、您必須針對錯誤執行所有必要的補救行動。雖然您可以忽略警告的補救行動、但最佳做法是在繼續更新之前、先執行所有的補救行動。

====
. 單擊 * 下一步 * 。
. 按一下 * 更新 * 。
+
再次執行驗證。

+
** 驗證完成後、表格會顯示任何錯誤和警告、以及任何必要的補救行動、然後再繼續進行。
** 如果驗證完成時出現警告、您可以選擇*繼續更新並顯示警告*核取方塊、然後按一下*繼續*。
驗證完成且更新正在進行時、更新可能因為錯誤而暫停。您可以按一下錯誤訊息來檢視詳細資料、然後在繼續更新之前執行補救行動。


+
更新成功完成後、節點會重新開機、並重新導向至System Manager登入頁面。如果節點重新開機需要很長時間、您必須重新整理瀏覽器。

. 登入System Manager、然後按一下*組態*>*叢集*>*更新*>*更新歷程記錄*、確認叢集已成功更新至所選版本、然後檢視詳細資料。

