---
permalink: online-help-96-97/task_configuring_iscsi_protocol_on_svms.html 
sidebar: sidebar 
keywords: system, manager, iscsi, protocol, svm, online, help, lif, portset 
summary: 您可以在儲存虛擬機器（SVM）上設定iSCSI傳輸協定、以便使用System Manager提供區塊層級的資料存取。您可以建立iSCSI生命期和連接埠集、然後將生命期新增至連接埠集。LIF是在最適合的介面卡上建立、並指派給連接埠集、以確保資料路徑備援。 
---
= 使用System Manager在SVM上設定iSCSI傳輸協定- ONTAP 支援更新版本的更新版本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用ONTAP 經典版的經典版（ONTAP 適用於支援的版本為S9.7及更早版本）、在儲存虛擬機器（SVM）上設定iSCSI傳輸協定、以提供區塊層級的資料存取。您可以建立iSCSI生命期和連接埠集、然後將生命期新增至連接埠集。LIF是在最適合的介面卡上建立、並指派給連接埠集、以確保資料路徑備援。

.開始之前
* 必須在叢集上啟用iSCSI授權。
+
如果SVM上未啟用iSCSI傳輸協定、您可以使用Edit Storage Virtual Machine（編輯儲存虛擬機器）視窗來啟用SVM的傳輸協定。

* 叢集中的所有節點都必須正常運作。
* 每個節點至少必須有兩個資料連接埠、而且連接埠狀態必須為 `up`。


.關於這項工作
* 您可以在建立SVM時設定iSCSI傳輸協定、也可以稍後再設定。
* 不考慮使用資訊區集合體來自動建立磁碟區。SnapLock


.步驟
. 如果您在建立SVM時尚未設定iSCSI傳輸協定、請按一下「*儲存設備*」>「* SVMS*」。
. 選取SVM、然後按一下* SVM設定*。
. 在「*傳輸協定*」窗格中、按一下「* iSCSI *」。
. *選用：*在「*網路存取*」區段中、指定iSCSI目標的別名。
+
別名的最大字元數為128。如果您未指定目標別名、則SVM名稱會用作別名。

. 指定可指派給單一節點的iSCSI LIF數目。
+
每個節點的最小生命量為一。最大數量是中所有連接埠的最小值 `up` 跨節點的狀態。如果最大值為odd數字、則會將前一個偶數視為最大值。您可以選擇最小值和最大值範圍內的任何偶數。

+
4 節點叢集具有 node1 、 node2 和 node3 、每個都有六個連接埠 `up` 狀態、以及節點 4 、其中有七個連接埠 `up` 州/省。叢集的有效最大值為6。

+
如果您要指派給節點的生命量超過兩個、則必須為每個LIF指派至少一個連接埠集。

. 指定網路詳細資料、包括子網路詳細資料、以建立iSCSI LIF：
+
|===
| 如果您想要... | 然後... 


 a| 
使用子網路指定IP位址
 a| 
.. 選擇*使用子網路*。
.. 在「新增詳細資料」對話方塊中、選取必須指派IP位址的子網路。
+
對於叢集間的LIF、只會顯示與所選IPspace相關聯的子網路。

.. 如果您要指派特定IP位址給介面、請選取*使用特定IP位址*、然後輸入IP位址。
+
如果IP位址不在子網路範圍內、您指定的IP位址就會新增至子網路。

.. 按一下「*確定*」。




 a| 
無需使用子網路、即可手動指定IP位址
 a| 
.. 選擇*不含子網路*。
.. 在「新增詳細資料」對話方塊中、執行下列步驟：
+
... 指定IP位址和網路遮罩或字首。
... 選用：指定閘道。
... 如果您不想使用「目的地」欄位的預設值、請指定新的目的地值。
+
如果您未指定目的地值、則會根據IP位址的系列、在「目的地」欄位中填入預設值。



+
如果路由不存在、系統會根據閘道和目的地自動建立新路由。

.. 按一下「*確定*」。


|===
. 選取廣播網域。
. 選取介面卡類型。
+
如果叢集中已設定NIC卡、則應選取* NIC *。

+
如果您的叢集已設定了主權會議卡、您應該選取* CNA*。

+
如果叢集中已設定ifgrps、則應選取*介面群組*。

+
[NOTE]
====
必須在廣播網域中新增ifgrp連接埠。

====
. *選用：*在設定iSCSI傳輸協定時、透過指定LUN大小、LUN的作業系統類型、以及主機啟動器詳細資料來配置iSCSI儲存設備的LUN。
. 如果您要驗證或修改自動產生的iSCSI LIF組態、請選取*檢閱或修改LIF組態（進階設定）*。
+
您只能修改LIF名稱和主連接埠。預設情況下、portset會設為最小值。您必須指定唯一的項目。如果您指定重複的LIF名稱、System Manager會將數值附加至重複的LIF名稱。

+
根據所選的連接埠集、lifs會透過循環配置資源方法分散到各個連接埠集、以確保在節點故障或連接埠故障時提供備援。

. 按一下*提交並繼續*。


.結果
iSCSI LIF和portSet是以指定的組態建立。根據所選的連接埠集、在連接埠集之間散佈該等連接埠。如果已成功建立所有的lifs、則會啟動iSCSI服務。

如果LIF建立失敗、您可以使用「網路介面」視窗來建立LIF、使用LUN視窗將LIF附加至連接埠集、然後使用iSCSI視窗來啟動iSCSI服務。
