---
permalink: online-help-96-97/task_creating_qos_policy_groups.html 
sidebar: sidebar 
keywords: online, help, create, qos, policy, groups, system, manager, quality, service 
summary: 您可以使用System Manager建立儲存服務品質（QoS）原則群組、以限制工作負載的處理量、並監控工作負載效能。 
---
= 使用System Manager管理QoS原則群組- ONTAP 不含更新版本的更新版本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用ONTAP 經典版的支援功能（ONTAP 適用於支援支援支援的版本）來建立儲存服務品質（QoS）原則群組、以限制工作負載的處理量、並監控工作負載效能。



== 建立QoS原則群組

.步驟
. 按一下「*儲存設備*>* SVMS*」。
. 選取SVM、然後按一下* SVM設定*。
. 在「*原則*」窗格中、按一下「* QoS原則群組*」。
. 在「* QoS原則群組*」視窗中、按一下「*建立*」。
. 在「*建立原則群組*」對話方塊中、指定原則的群組名稱。
. 指定最小處理量限制。
+
** 在System Manager 9.5中、您只能針對效能型All Flash Optimized特性設定設定設定最低處理量限制。在System Manager 9.6中、您也可以設定ONTAP Select 適用於各種系統的最小處理量限制。
** 您無法在啟用FabricPool的Aggregate上設定磁碟區的最小處理量限制。
** 如果您未指定最小處理量值、或將最小處理量值設為0、系統會自動顯示「無」作為值。
+
此值區分大小寫。



. 指定最大處理量限制。
+
** 最小處理量限制和最大處理量限制必須為相同的單位類型。
** 如果未指定最小處理量限制、您可以設定IOPS和B/s、kb/s、MB/s等的最大處理量限制。
** 如果未指定最大處理量限制、系統會自動顯示「'Unlimited'」作為值。
+
此值區分大小寫。您指定的單位不會影響最大處理量。



. 按一下「*確定*」。




== 刪除QoS原則群組

您可以使用ONTAP 經典版的《支援功能》（ONTAP 適用於支援功能更新版本的版本）來刪除不再需要的儲存品質服務（QoS）原則群組。

.開始之前
您必須取消指派指派指派給原則群組的所有儲存物件。

.步驟
. 按一下「*儲存設備*>* SVMS*」。
. 選取SVM、然後按一下* SVM設定*。
. 在「*原則*」窗格中、按一下「* QoS原則群組*」。
. 在「* QoS原則群組*」視窗中、選取您要刪除的原則群組、然後按一下「*刪除*」。
. 在確認對話方塊中、按一下 * 刪除 * 。




== 編輯QoS原則群組

您可以使用ONTAP 經典版的「更新原則群組」對話方塊（ONTAP 可在更新版本的版本中使用）、修改現有儲存品質服務（QoS）原則群組的名稱和最大處理量。

.關於這項工作
* 在System Manager 9.5中、您只能針對效能型All Flash Optimized特性設定設定設定最低處理量限制。在System Manager 9.6中、您也可以設定ONTAP Select 適用於各種系統的最小處理量限制。
* 您無法在啟用FabricPool的Aggregate上設定磁碟區的最小處理量限制。


.步驟
. 按一下「*儲存設備*>* SVMS*」。
. 選取SVM、然後按一下* SVM設定*。
. 在「*原則*」窗格中、按一下「* QoS原則群組*」。
. 選取您要編輯的QoS原則群組、然後按一下*編輯*。
+
** 最小處理量限制和最大處理量限制必須為相同的單位類型。
** 如果未指定最小處理量限制、您可以設定IOPS和B/s、kb/s、MB/s等的最大處理量限制。
** 如果您未指定最大處理量限制、該值會設定為無限、而您指定的單位不會影響最大處理量。


. 在*編輯原則群組*對話方塊中、編輯QoS原則群組詳細資料、然後按一下*儲存*。

