---
permalink: online-help-96-97/task_enabling_storage_efficiency_on_volume.html 
sidebar: sidebar 
keywords: system, manager, enable, storage, efficiency, volume, deduplication, online, help 
summary: 您可以使用System Manager來啟用儲存效率、並在磁碟區上同時設定重複資料刪除與資料壓縮、或僅設定重複資料刪除、以節省儲存空間。如果您在建立磁碟區時尚未啟用儲存效率、您可以稍後編輯磁碟區來啟用儲存效率。 
---
= 利用System Manager ONTAP （系統管理程式）-更新版本的更新版本、在磁碟區上實現儲存效率
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用ONTAP 經典版的支援功能（ONTAP 以支援更新版本的版本供應）來提升儲存效率、並在磁碟區上同時設定重複資料刪除和資料壓縮、或僅設定重複資料刪除、以節省儲存空間。如果您在建立磁碟區時尚未啟用儲存效率、您可以稍後編輯磁碟區來啟用儲存效率。

.開始之前
* Volume必須處於線上狀態。
* 如果您想要使用原則型重複資料刪除排程、則必須建立效率原則。


.關於這項工作
* 只有啟用背景重複資料刪除、您才能啟用背景資料壓縮。
* 您可以啟用內嵌壓縮和內嵌重複資料刪除、無論是否啟用背景壓縮和背景重複資料刪除。
* 您只能在集合體所包含的磁碟區上啟用即時重複資料刪除功能、這些磁碟區具有「All Flash Optimized」（所有Flash最佳化）特性、以及Flash Pool Aggregate所包含的磁碟區。
* 從System Manager 9.6開始、FlexGroup 支援編輯儲存效率的功能、適用於SDP Volume。


.步驟
. 按一下「*儲存設備*>*磁碟區*」。
. 從「* SVM*」欄位的下拉式功能表中、選取「*所有SVM*」。
. 選取您要啟用儲存效率的磁碟區、然後按一下*編輯*。
. 在*編輯Volume *對話方塊中、按一下*儲存效率*。
. 選取「*背景重複資料刪除*」核取方塊。
. 選擇下列方法之一來執行重複資料刪除：
+
|===
| 如果您要執行重複資料刪除... | 然後... 


 a| 
以儲存效率原則為基礎
 a| 
.. 請確定已選取*原則型*選項。
.. 按一下*選擇*、然後選取儲存效率原則。
.. 按一下「*確定*」。




 a| 
必要時
 a| 
選擇*隨需*選項。

|===
. 選取「*背景壓縮*」核取方塊以啟用背景壓縮。
+
您無法針對由具有All Flash Optimized特性設定的Aggregate所包含的磁碟區啟用背景壓縮。

. 選取「*內嵌壓縮*」核取方塊、即可在資料寫入磁碟區時壓縮資料。
+
根據預設、內嵌壓縮會在集合體所包含的磁碟區上啟用、並具有All Flash Optimized特性設定。

. 選取「*內嵌重複資料刪除*」核取方塊、即可在資料寫入磁碟之前執行重複資料刪除。
+
根據預設、內嵌重複資料刪除功能會在集合體所包含的磁碟區上啟用、並具有All Flash Optimized特性設定。

. 按一下*儲存並關閉*。


*相關資訊*

xref:reference_volumes_window.adoc[Volume視窗]
