---
permalink: online-help-96-97/task_setting_up_cluster_using_template_file.html 
sidebar: sidebar 
keywords: set, up, cluster, template, file, system, manager, online, help, autosupport 
summary: 您可以使用System Manager中提供的範本檔案建立叢集、設定節點管理和叢集管理網路、然後設定事件通知、藉此設定叢集。（從ONTAP 《支援使用支援AutoSupport 功能的不支援功能》的《支援功能》（從《支援功能》9.6開始）。 您可以下載採用.xlsxxx,或是採用.csv.格式的範本檔案。 
---
= 使用System Manager ONTAP - NetApp 9.7及更早版本中的範本檔案來設定叢集
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用ONTAP 經典版《經典版》（ONTAP 適用於更新版本的版本）中提供的範本檔案、建立叢集、設定節點管理和叢集管理網路、然後設定事件通知、來設定叢集。（從 ONTAP 系統管理員 9.6 開始、不支援 AutoSupport 。） 您可以在中下載範本檔案 `.xlsx` 格式化或 `.csv` 格式。

.關於這項工作
* 如果叢集支援ONTAP 更新版本的版本、您只能新增執行ONTAP 更新版本的儲存系統。
* 上傳檔案時、不會自動填入所有欄位。
+
您必須手動輸入密碼和叢集管理連接埠等部分欄位的值。



.步驟
. 開啟 Web 瀏覽器、然後輸入您已設定的節點管理 IP 位址： `+https://node-management-IP+`
+
** 如果您已設定叢集的認證、則會顯示「Login」（登入）頁面。
+
您必須輸入認證資料才能登入。

** 如果您尚未設定叢集的認證、則會顯示引導式設定視窗。


. 下載 `.xlsx` 範本檔案或 `.csv` 範本檔案。
. 在範本檔案中提供所有必要的值、然後儲存檔案。
+
[NOTE]
====
** 請勿編輯範本中除「Value（值）」以外的任何其他欄位。
** 請勿變更範本檔案的版本。


====
. 按一下*瀏覽*、然後選取更新的範本檔案。
+
** 您只能在中上傳範本檔案 `.csv` 格式。如果您已在中下載範本檔案 `.xlsx` 格式化時、您必須將檔案另存為 `.csv` 檔案、然後上傳檔案。
** 您必須確定此檔案所使用的編碼是 `UTF8`。如果沒有、則不會讀取這些值。


. 按一下*上傳*。
+
您在範本檔案中提供的詳細資料可用來完成叢集設定程序。

. 按一下*引導式設定*圖示、即可檢視叢集的詳細資料。
. 驗證「*叢集*」視窗中的詳細資料、然後按一下「*提交並繼續*」。
+
如有需要、您可以編輯叢集詳細資料。

+
如果您第二次登入叢集視窗、則預設會啟用「*功能授權*」欄位。您可以新增功能授權金鑰、或保留預先填入的授權金鑰。

. 驗證*網路*視窗中的詳細資料、然後按一下*提交並繼續*。
+
如有需要、您可以編輯網路詳細資料。

. 確認「*支援*」視窗中的詳細資料、然後按一下「*提交並繼續*」。
+
如有需要、您可以編輯支援詳細資料。

. 驗證* Storage*視窗中的詳細資料、然後建立Aggregate或結束叢集設定：
+
|===
| 如果您想要... | 然後... 


 a| 
結束叢集設定、不需配置儲存設備和建立SVM
 a| 
按一下*跳過此步驟*。



 a| 
使用Aggregate配置儲存設備、並建立SVM
 a| 
按一下*提交並繼續*。

|===
+
如有需要、您可以編輯支援詳細資料。

. 驗證「*建立儲存虛擬機器（SVM）*」視窗中的詳細資料、然後按一下「*提交並繼續*」。
+
您可以編輯SVM名稱、選取不同的資料傳輸協定、並視需要修改網路介面和介面卡詳細資料。

. 如果您在* Storage *（儲存設備）視窗中按一下*跳過此步驟*、請在* Summary（摘要）*視窗中檢視詳細資料、然後按一下* Manage Your Clust*（管理叢集）以啟動System Manager（系統管理員）。
. 如果您在* Storage*（儲存設備）視窗中按一下*提交並繼續*、請確認SVM視窗中的詳細資料、然後按一下*提交並繼續*。
+
如有需要、您可以編輯SVM詳細資料。

. 驗證* Summary（摘要）*視窗中的所有詳細資料、然後按一下* Provision an Application*（*資源配置應用程式*）以配置應用程式的儲存設備、或按一下* Manage Your Clust*（管理叢集*）以完成叢集設定程序並啟動System Manager、或按一下* Export Configuration（匯出組態）*下載組態


*相關資訊*

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/System_Manager_Cluster_Guided_Setup_Templates["System Manager叢集引導式設定範本"]
