---
permalink: online-help-96-97/task_creating_snaplock_volumes.html 
sidebar: sidebar 
keywords: create, snaplock, volume, online, help, system, manager 
summary: 您可以使用System Manager來建立SnapLock 「不符合要求」的Volume或SnapLock 「不符合要求」的Enterprise Volume。建立磁碟區時、您也可以設定保留時間、並選擇是否要自動設定磁碟區中資料的WORM狀態。 
---
= 利用SnapLock System Manager建立包含ONTAP 更新版本的功能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用ONTAP 經典版的《經典版》（ONTAP 僅適用於更新版本的版本）來製作SnapLock 《不符合要求》（《不符合要求》）或SnapLock 《不符合要求》（《不符合要求》）。建立磁碟區時、您也可以設定保留時間、並選擇是否要自動設定磁碟區中資料的WORM狀態。

.開始之前
* 必須已安裝此功能。SnapLock
* 此資訊必須在線上。SnapLock
* 若要建立加密磁碟區、您必須使用System Manager安裝Volume加密授權、而且必須使用命令列介面（CLI）啟用「金鑰管理程式設定」。
+
啟用「key-manager setup」之後、您必須重新整理網頁瀏覽器。



.關於這項工作
* 您可以刪除SnapLock 完整的「企業版」Volume或SnapLock 「企業版」Volume中的檔案、但SnapLock 無法只刪除「企業版」Volume中檔案內的資料。
* 如果資料已提交至磁碟區、您將無法刪除SnapLock 「不符合要求」磁碟區。
* 您無法在Cloud Volumes ONTAP 不執行功能的情況下加密Volume。
* 如果在來源磁碟區上啟用加密功能、且目的地叢集執行ONTAP 的是版本低於ONTAP 版本的版本的更新、則預設會在目的地磁碟區上停用加密功能。


.步驟
. 按一下「*儲存設備*>*磁碟區*」。
. 按一下「*建立*」>「*建立FlexVol *」。
. 瀏覽並選取您要在其中建立磁碟區的儲存虛擬機器（SVM）。
. 如果您要變更磁碟區的預設名稱、請在「*建立磁碟區*」對話方塊中指定新名稱。
+
建立磁碟區後、您無法變更SnapLock 「更新法規遵循」磁碟區的名稱。

. 選取磁碟區的容器Aggregate。
+
您必須選取SnapLock 「不符合要求」的Aggregate或SnapLock 「不符合要求的企業」Aggregate、才能建立SnapLock 一個「不符合要求」的Volume會從SnapLock Aggregate繼承該類型的數據、SnapLock 而且建立Volume之後、無法變更該類型的數據；因此、您必須選取正確的Aggregate。

. 選取「* Volume Encryption*」（* Volume Encryption *）核取方塊、即可啟用磁碟區的加密功能。
+
此選項僅在您已啟用Volume Encryption授權、且對應的平台能夠支援加密時可用。

. 選取您要建立此磁碟區的儲存類型。
+
如果您要建立SnapMirror目的地Volume、則必須選取*資料保護*。您將獲得此Volume的唯讀存取權。

. 指定要保留給Snapshot複本的磁碟區大小、以及總磁碟區大小的百分比。
+
保留給Snapshot複本的預設空間為SAN磁碟區和VMware磁碟區的零百分比。NAS磁碟區的預設值為5%。

. *選用：*選取*精簡配置*以啟用磁碟區的精簡配置。
+
啟用精簡配置時、只有在資料寫入磁碟區時、才會從集合體將空間分配給磁碟區。

. *可選：*在「*儲存效率*」索引標籤中進行必要的變更、以在磁碟區上啟用重複資料刪除功能。
+
System Manager使用預設的重複資料刪除排程。如果指定的磁碟區大小超過執行重複資料刪除所需的限制、就會建立磁碟區、而且不會啟用重複資料刪除功能。

. 選取* SnapLock 《*》索引標籤、然後執行下列步驟：
+
.. *選用：*指定自動提交期間。
+
磁碟區中的檔案在您指定的期間內保持不變、檔案才會被提交至WORM狀態。若要手動將檔案設定為WORM狀態、您必須選取*未指定*作為自動提交設定。

+
這些值必須介於5分鐘到10年之間。

.. 指定最短保留期間和最長保留期間。
+
這些值必須介於1天到70年之間、或是「無限大」。

.. 選取預設保留期間。
+
預設保留期間必須在指定的最短保留期間和最長保留期間內。



. *可選：*在*服務品質*標籤中選取*管理儲存服務品質*核取方塊、以啟用FlexVol 適用於整個VMware Volume的儲存QoS、以管理工作負載效能。
. 建立儲存QoS原則群組、或選取現有的原則群組、以控制FlexVol 該磁碟區的輸入/輸出（I/O）效能。
+
|===
| 如果您想要... | 執行此動作... 


 a| 
建立儲存QoS原則群組
 a| 
.. 選擇*新原則群組*。
.. 指定原則群組名稱。
.. 指定最小處理量限制。
+
*** 在System Manager 9.5中、您只能針對效能型All Flash Optimized特性設定設定設定最低處理量限制。在System Manager 9.6中、您也可以設定ONTAP Select 適用於各種系統的最小處理量限制。
*** 您無法在啟用FabricPool的Aggregate上設定磁碟區的最小處理量限制。
*** 如果您未指定最小處理量值、或將最小處理量值設為0、系統會自動顯示「無」作為值。
+
此值區分大小寫。



.. 指定最大處理量限制、以確保原則群組中物件的工作負載不會超過指定的處理量限制。
+
*** 最小處理量限制和最大處理量限制必須為相同的單位類型。
*** 如果您未指定最小處理量限制、則可以設定IOPS、B/s、kb/s、MB/s等的最大處理量限制。
*** 如果您未指定最大處理量值、系統會自動顯示「'Unlimited'」作為值。
+
此值區分大小寫。您指定的單位不會影響最大處理量。







 a| 
選取現有的原則群組
 a| 
.. 選取*現有的原則群組*、然後按一下*選擇*、從「選取原則群組」對話方塊中選取現有的原則群組。
.. 指定最小處理量限制。
+
*** 在System Manager 9.5中、您只能針對效能型All Flash Optimized特性設定設定設定最低處理量限制。在System Manager 9.6中、您也可以設定ONTAP Select 適用於各種系統的最小處理量限制。
*** 您無法在啟用FabricPool的Aggregate上設定磁碟區的最小處理量限制。
*** 如果您未指定最小處理量值、或將最小處理量值設為0、系統會自動顯示「無」作為值。
+
此值區分大小寫。



.. 指定最大處理量限制、以確保原則群組中物件的工作負載不會超過指定的處理量限制。
+
*** 最小處理量限制和最大處理量限制必須為相同的單位類型。
*** 如果您未指定最小處理量限制、則可以設定IOPS、B/s、kb/s、MB/s等的最大處理量限制。
*** 如果您未指定最大處理量值、系統會自動顯示「'Unlimited'」作為值。
+
此值區分大小寫。您指定的單位不會影響最大處理量。



+
如果原則群組指派給多個物件、則您指定的最大處理量會在物件之間共用。



|===
. 在* Protection（保護）*選項卡中啟用* Volume Protection（磁碟區保護）*來保護磁碟區：
. 在* Protection（保護）*選項卡中，選擇* Replication（複製）*類型：
+
|===
| 如果您選取複寫類型為... | 執行此動作... 


 a| 
非同步
 a| 
.. *可選：*如果您不知道複寫類型和關聯類型、請按一下*「Help me choose」*、指定值、然後按一下「*套用*」。
.. 選取關係類型。
+
關係類型可以是鏡射、資料保險箱或鏡射及資料保險箱。

.. 為目的地Volume選取叢集和SVM。
+
如果所選叢集執行ONTAP 的是版本早於ONTAP 版本的更新版本、則只會列出已執行的SVM。如果選取的叢集執行ONTAP 的是Sfe9.3或更新版本、則會列出已執行的SVM和允許的SVM。

.. 如有需要、請修改Volume名稱後置字元。




 a| 
同步
 a| 
.. *可選：*如果您不知道複寫類型和關聯類型、請按一下*「Help me choose」*、指定值、然後按一下「*套用*」。
.. 選取同步原則。
+
同步原則可以是StrictSync或Sync。

.. 為目的地Volume選取叢集和SVM。
+
如果所選叢集執行ONTAP 的是版本早於ONTAP 版本的更新版本、則只會列出已執行的SVM。如果選取的叢集執行ONTAP 的是Sfe9.3或更新版本、則會列出已執行的SVM和允許的SVM。

.. 如有需要、請修改Volume名稱後置字元。


|===
. 按一下「 * 建立 * 」。
. 驗證您所建立的磁碟區是否包含在「* Volume *」視窗的磁碟區清單中。


.結果
此磁碟區是以UNIX型安全性和UNIX 700「讀寫執行」權限建立、以供擁有者使用。
