---
permalink: online-help-96-97/task_editing_mirror_vault_relationships.html 
sidebar: sidebar 
keywords: edit, mirror, vault, relationship, system, manager, online, help 
summary: 您可以修改選取的原則或排程、使用System Manager來編輯鏡射與資料保險箱關係。不過、您無法編輯現有原則或排程的參數。 
---
= 使用System Manager管理鏡射與保存資料的關係- ONTAP 不含更新版本的更新版本
:allow-uri-read: 


[role="lead"]
您可以使用ONTAP 經典版的《經典版》（ONTAP 僅適用於19、9.7及更早版本）來管理鏡射與保存關係。您可以編輯、刪除、初始化、更新、靜止、 恢復及中斷鏡射與資料保險箱的關係。除了從目的地 SVM 建立鏡射和資料保險箱關係之外、您也可以執行重新同步或反向重新同步作業。



== 編輯關係

您可以修改選取的原則或排程、使用System Manager來編輯鏡射與資料保險箱關係。不過、您無法編輯現有原則或排程的參數。

.開始之前
來源與目的地叢集必須處於健全的對等關係中。

.關於這項工作
您可以修改原則類型、以修改版本彈性鏡射關係、資料保險箱關係、或鏡射與資料保險箱關係的關係類型。

.步驟
. 按一下「*保護*>*磁碟區關係*」。
. 選取您要修改的鏡射與資料保險箱關係、然後按一下*編輯*。
. 在*編輯關係*對話方塊中、選取適當的動作：
+
|===
| 如果您想要... | 請執行下列動作... 


 a| 
選取現有原則
 a| 
按一下*瀏覽*、然後選取現有的原則。    您可以選取具有與來源Volume附加之Snapshot原則相符之標籤數目上限的原則。



 a| 
建立新原則
 a| 
.. 按一下「*建立原則*」。
.. 指定原則的名稱。
.. 設定排程傳輸的優先順序。
+
「低」表示傳輸的優先順序最低、通常是在正常優先順序傳輸之後排程。依預設、優先順序設為「正常」。

.. 選取「*啟用網路壓縮*」核取方塊以壓縮正在傳輸的資料。
.. 指定資料保存原則的SnapMirror標籤和目的地保留計數。
+
您必須確保在來源磁碟區上建立具有相同標籤的Snapshot複本、新的SnapMirror標籤才會生效。

.. 按一下「 * 建立 * 」。


|===
. 指定關係的排程：
+
|===
| 如果... | 請執行下列動作... 


 a| 
您想要指派現有的排程
 a| 
按一下*瀏覽*、然後選取現有的排程。



 a| 
您想要建立新的排程
 a| 
.. 按一下*建立排程*。
.. 指定排程的名稱。
.. 選取下列其中一個選項：
+
*** *基礎*
+
您可以選取此選項、只指定一週中的某天、時間和傳輸時間間隔。

*** *進階*
+
您可以選取此選項來指定cron樣式排程。



.. 按一下「 * 建立 * 」。




 a| 
您不想指派排程
 a| 
選擇*無*。

|===
. 按一下「*確定*」。




== 手動更新關係

您可以使用System Manager手動啟動非排程的遞增更新。您可能需要手動更新、以避免因即將停電、排程維護或資料移轉而導致資料遺失。

.開始之前
鏡射與資料保險箱關係必須初始化、且處於Snapmirror狀態。

.步驟
. 按一下「*保護*>*磁碟區關係*」。
. 選取您要更新資料的鏡射關係、然後按一下「*作業*」>「*更新*」。
. 請選擇下列其中一個選項：
+
** 選取*根據原則*以在來源與目的地磁碟區之間執行最近通用Snapshot複本的遞增傳輸。
** 選取*選取Snapshot COPU*並指定您要傳輸的Snapshot複本。


. 選取*限制傳輸頻寬至*以限制傳輸所用的網路頻寬、然後指定最大傳輸速度。
. 按一下 * 更新 * 。
. 在* Details（詳細資料）*選項卡中驗證傳輸狀態。




== 初始化關係

如果您在建立關聯時尚未初始化關係、可以使用System Manager來初始化鏡射和資料保險箱關係。當您初始化關係時、會從來源磁碟區執行資料的完整基準傳輸至目的地。

.開始之前
來源與目的地叢集必須處於健全的對等關係中。

.步驟
. 按一下「*保護*>*磁碟區關係*」。
. 選取您要初始化的鏡射與資料保險箱關係、然後按一下「*作業*」>「*初始化*」。
. 選取確認核取方塊、然後按一下*初始化*。
. 在* Protection（保護）*視窗中驗證關係狀態。


.結果
建立Snapshot複本並傳輸至目的地。

此Snapshot複本可作為後續遞增Snapshot複本的基礎。



== 從目的地SVM建立關係

您可以使用System Manager從目的地儲存虛擬機器（SVM）建立鏡射與資料保險箱關係。建立此關係可讓您定期將資料從來源磁碟區傳輸到目的地磁碟區、以更有效地保護資料。它也能讓您建立來源Volume的備份、以長期保留資料。

.開始之前
* 目的地叢集必須執行ONTAP 的是32個或更新版本。
* 必須在來源叢集和目的地叢集上啟用SnapMirror授權。
+
[NOTE]
====
對於某些平台而言、如果目的地叢集已啟用SnapMirror授權和資料保護最佳化（DPO）授權、則來源叢集並不一定要啟用SnapMirror授權。

====
* 來源叢集和目的地叢集必須處於健全的對等關係中。
* 目的地SVM必須有可用空間。
* 來源Aggregate和目的地Aggregate必須是64位元Aggregate。
* 讀寫（RW）類型的來源Volume必須已經存在。
* 此類資訊必須相同。SnapLock
* 如果您要從執行ONTAP 支援SAML驗證的叢集9.2或更早版本連線至遠端叢集、則必須在遠端叢集上啟用密碼型驗證。


.關於這項工作
* System Manager不支援串聯關係。
+
例如、關係中的目的地磁碟區不能是另一個關係中的來源磁碟區。

* 您無法在同步來源SVM和MetroCluster 同步目的地SVM之間建立鏡射與資料庫關係、以進行非同步組態。
* 您可以在MetroCluster 採用Sync-Source SVM之間建立鏡射與資料庫關係、以實現一套功能性的組態。
* 您可以從同步來源SVM上的磁碟區建立鏡射與資料保存關係、並建立與資料服務SVM的磁碟區之間的關係。
* 您可以從資料服務SVM上的磁碟區建立鏡射與資料保存關係、並在同步來源SVM上建立DP磁碟區。
* 一個選項最多可保護25個磁碟區。


.步驟
. 按一下「*保護*>*磁碟區關係*」。
. 在*關係*視窗中、按一下*建立*。
. 在「*瀏覽SVM*」對話方塊中、選取目的地Volume的SVM。
. 在「*建立保護關係*」對話方塊中、從「*關係類型*」下拉式清單中選取「*鏡射與資料庫*」。
. 指定叢集、SVM和來源Volume。
+
如果指定的叢集執行ONTAP 的是版本早於ONTAP 版本的更新版本、則只會列出已執行的SVM。如果指定的叢集執行ONTAP 的是Sfe9.3或更新版本、則會列出已執行的SVM和允許的SVM。

. 輸入Volume名稱字尾。
+
磁碟區名稱尾碼會附加至來源磁碟區名稱、以產生目的地磁碟區名稱。

. *選用：*按一下*瀏覽*、然後變更鏡射與資料保存原則。
+
您可以選取具有與來源磁碟區附加之Snapshot原則相符之標籤數目上限的原則。

. 從現有排程清單中選取關係的排程。
. *可選：*選擇*初始化關係*以初始化關係。
. 啟用啟用FabricPool的Aggregate、然後選取適當的分層原則。
. 按一下「*驗證*」以驗證所選磁碟區是否有相符的標籤。
. 按一下「 * 建立 * 」。




== 重新同步關係

您可以使用System Manager重新建立先前中斷的鏡射與資料保險箱關係。您可以執行重新同步作業、從停用來源Volume的災難中恢復。

.開始之前
來源與目的地叢集、以及來源與目的地儲存虛擬機器（SVM）必須處於對等關係中。

.關於這項工作
在執行重新同步作業之前、您應注意下列事項：

* 當您執行重新同步作業時、目的地磁碟區上的內容會被來源上的內容覆寫。
+
[NOTE]
====
重新同步作業可能會在建立基礎Snapshot複本之後、遺失寫入目的地Volume的新資料。

====
* 如果Protection（保護）窗口中的Last Transfer錯誤（上次傳輸錯誤）欄位建議重新同步作業、您必須先中斷關係、然後再執行重新同步作業。


.步驟
. 按一下「*保護*>*磁碟區關係*」。
. 選取您要重新同步的鏡射與資料庫關係、然後按一下*作業*>*重新同步*。
. 選取確認核取方塊、然後按一下*重新同步*。




== 反轉重新同步關係

您可以使用System Manager重新建立先前中斷的鏡射與資料保險箱關係。在反向重新同步作業中、來源與目的地磁碟區的功能會反轉。您可以在修復或更換來源、更新來源、以及重新建立系統的原始組態時、使用目的地磁碟區來提供資料。

.開始之前
來源Volume必須在線上。

.關於這項工作
* 當您執行反向重新同步時、來源磁碟區上的內容會被目的地磁碟區上的內容覆寫。
+
[NOTE]
====
反轉重新同步作業可能會導致來源磁碟區上的資料遺失。

====
* 當您執行反轉重新同步時、關係的原則會設定為MirrorAndVault、排程會設定為「無」。


.步驟
. 按一下「*保護*>*磁碟區關係*」。
. 選取您要反轉的鏡射與資料保險箱關係、然後按一下「*作業*」>「*反轉重新同步*」。
. 選取確認核取方塊、然後按一下*反轉重新同步*。




== 打破關係

如果來源磁碟區無法使用、而您想讓用戶端應用程式從目的地磁碟區存取資料、您可以使用System Manager來中斷鏡射與資料保存關係。您可以在修復或更換來源磁碟區、更新來源磁碟區、以及重新建立系統的原始組態時、使用目的地磁碟區來提供資料。

.開始之前
* 鏡射與資料保險箱關係必須處於靜止狀態或閒置狀態。
* 目的地Volume必須掛載到目的地儲存虛擬機器（SVM）命名空間。


.關於這項工作
您可以打破ONTAP 彼此之間的鏡射關係。SolidFire

.步驟
. 按一下「*保護*>*磁碟區關係*」。
. 選取您要中斷的鏡射與資料保險箱關係、然後按一下「*作業*」>「*中斷*」。
. 選取確認核取方塊、然後按一下*中斷*。


.結果
鏡射與資料保險箱的關係中斷。目的地Volume類型從資料保護（DP）唯讀變更為讀/寫。系統會儲存基礎Snapshot複本、以供鏡射和資料保險箱關係日後使用。



== 恢復關係

如果您有靜止的鏡射及資料保險箱關係、可以使用系統管理員來恢復關係。當您恢復關係時、會恢復正常資料傳輸至目的地Volume、並重新啟動所有保護活動。

.關於這項工作
如果您從命令列介面（CLI）中斷鏡射與資料保險箱關係、則無法從系統管理員恢復關係。您必須使用CLI恢復關係。

.步驟
. 按一下「*保護*>*磁碟區關係*」。
. 選取您要恢復的鏡射與資料保險箱關係、然後按一下「*作業*」>「*恢復*」。
. 選取確認核取方塊、然後按一下*恢復*。


.結果
恢復正常資料傳輸。如果關係有排程的傳輸、則會從下一個排程開始傳輸。



== 刪除關係

您可以使用System Manager結束來源與目的地Volume之間的鏡射與資料保存關係、然後從來源Volume發行Snapshot複本。

.關於這項工作
* 刪除關聯之前、最好先中斷鏡射與資料保險箱的關係。
* 若要重新建立關係、您必須使用命令列介面（CLI）從來源磁碟區執行重新同步作業。


.步驟
. 按一下「*保護*>*磁碟區關係*」。
. 選取您要刪除的鏡射與資料保險箱關係、然後按一下*刪除*。
. 選取確認核取方塊、然後按一下*刪除*。
+
您也可以選取「發行基礎Snapshot複本」核取方塊、刪除來源磁碟區上鏡射與資料保險箱關係所使用的基礎Snapshot複本。

+
如果關係尚未釋出、則您必須使用CLI在來源叢集上執行發行作業、以從來源磁碟區刪除為鏡射和資料保險箱關係所建立的基礎Snapshot複本。



.結果
此關係會刪除、且來源磁碟區上的基礎Snapshot複本會永久刪除。



== 靜止關係

您可以在建立Snapshot複本之前、使用System Manager來靜止目的地磁碟區、以穩定目的地。「靜止」作業可讓作用中資料傳輸完成、並停用鏡射與資料保險箱關係的未來傳輸。

.開始之前
鏡射與資料保險箱關係必須處於Snapmirror狀態。

.步驟
. 按一下「*保護*>*磁碟區關係*」。
. 選取您要靜止的鏡射與資料保險箱關係、然後按一下「*作業*」>「*靜止*」。
. 選取確認核取方塊、然後按一下*靜止*。


.結果
如果沒有傳輸進行中、傳輸狀態會顯示為 `Quiesced`。如果傳輸進行中、傳輸不會受到影響、傳輸狀態會顯示為 `Quiescing` 直到傳輸完成為止。
