---
permalink: online-help-96-97/task_editing_vault_relationships.html 
sidebar: sidebar 
keywords: edit, vault, relationships, system, manager, online, help, cluster, schedule 
summary: 您可以使用System Manager編輯資料保險箱關係、方法是選取叢集中的現有原則或排程、或建立新的原則或排程。不過、您無法編輯現有原則或排程的參數。 
---
= 使用ONTAP System Manager管理資料保存關係-更新版本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
除了ONTAP 從目的地SVM建立資料保存關係之外、您也可以使用經典版的《經典版》（ONTAP 僅適用於更新、恢復、靜止、初始化及刪除）功能來更新、恢復、靜止、初始化及刪除資料保存關係。



== 編輯關係

您可以使用System Manager編輯資料保險箱關係、方法是選取叢集中的現有原則或排程、或建立新的原則或排程。不過、您無法編輯現有原則或排程的參數。

.開始之前
來源與目的地叢集必須處於健全的對等關係中。

.步驟
. 按一下「*保護*>*磁碟區關係*」。
. 選取您要修改原則或排程的資料保存關係、然後按一下*編輯*。
. 在*編輯關係*對話方塊中、選取適當的動作：
+
|===
| 如果您想要... | 請執行下列動作... 


 a| 
選取現有原則
 a| 
按一下*瀏覽*、然後選取現有的原則。    您可以選取具有與來源Volume附加之Snapshot原則相符之標籤數目上限的原則。



 a| 
建立新原則
 a| 
.. 按一下「*建立原則*」。
.. 指定原則的名稱。
.. 設定排程傳輸的優先順序。
+
「低」表示傳輸的優先順序最低、通常是在正常優先順序傳輸之後排程。依預設、優先順序設為「正常」。

.. 選取「*啟用網路壓縮*」核取方塊以壓縮正在傳輸的資料。
.. 指定資料保存原則的SnapMirror標籤和目的地保留計數。
+
您必須確保在來源磁碟區上建立具有相同標籤的Snapshot複本、新的SnapMirror標籤才會生效。

.. 按一下「 * 建立 * 」。


|===
. 指定關係的排程：
+
|===
| 如果... | 請執行下列動作... 


 a| 
您想要指派現有的排程
 a| 
從清單中選取現有的排程。



 a| 
您想要建立新的排程
 a| 
.. 按一下*建立排程*。
.. 指定排程的名稱。
.. 選取下列其中一個選項：
+
*** *基礎*
+
您可以選取此選項、只指定一週中的某天、時間和傳輸時間間隔。

*** *進階*
+
您可以選取此選項來指定cron樣式的排程。



.. 按一下「 * 建立 * 」。




 a| 
您不想指派排程
 a| 
選擇*無*。

|===
. 按一下「*確定*」。


*相關資訊*

xref:reference_protection_window.adoc[保護所需時間]



== 初始化關係

如果您在建立關聯時尚未初始化資料保險箱關係、則可以使用System Manager來初始化資料保險箱關係。資料的基礎傳輸是從來源FlexVol 的來源供應區開始、並移至目的地FlexVol 的供應區。

.開始之前
來源與目的地叢集必須處於健全的對等關係中。

.步驟
. 按一下「*保護*>*磁碟區關係*」。
. 選取您要初始化的關係、然後按一下*作業*>*初始化*。
. 在*初始化*視窗中、按一下*初始化*。


.結果
建立Snapshot複本並傳輸至目的地。

此Snapshot複本可作為後續遞增Snapshot複本的基礎。

*相關資訊*

xref:reference_protection_window.adoc[保護所需時間]



== 從目的地SVM建立關係

您可以使用System Manager從目的地儲存虛擬機器（SVM）建立資料保險箱關係、並指派資料保險箱原則以建立備份資料庫。如果系統資料遺失或毀損、可從備份資料保存庫目的地還原備份資料。

.開始之前
* 來源叢集必須執行ONTAP 不含更新版本的版本。
* 來源叢集和目的地叢集上必須同時啟用支援或SnapMirror授權。SnapVault
+
[NOTE]
====
對於某些平台而言、如果SnapVault 目的地叢集已SnapVault 啟用了SnapMirror授權或SnapMirror授權、且已啟用DPO授權、則來源叢集並不一定要啟用該授權或SnapMirror授權。

====
* 來源叢集和目的地叢集必須處於健全的對等關係中。
* 目的地SVM必須有可用空間。
* 來源Aggregate和目的地Aggregate必須是64位元Aggregate。
* 必須存在讀寫（RW）類型的來源Volume。
* 資料保存（XDP）原則必須存在。
+
如果資料保險箱原則不存在,您必須建立資料保險箱原則或接受自動指派的預設資料保險箱原則(XDPDefault)。

* 必須在線上和讀取/寫入資料才能使用。FlexVol
* 此類資訊必須相同。SnapLock
* 如果您要從執行ONTAP 支援SAML驗證的叢集9.2或更早版本連線至遠端叢集、則必須在遠端叢集上啟用密碼型驗證。


.關於這項工作
* System Manager不支援串聯關係。
+
例如、關係中的目的地磁碟區不能是另一個關係中的來源磁碟區。

* 您無法在同步來源SVM與同步目的地SVM之間建立資料保存關係MetroCluster 、以供採用該組態。
* 您可以在MetroCluster 採用Sync-SVM的組態中、建立同步來源SVM之間的資料保存關係。
* 您可以從同步來源SVM上的磁碟區、建立與資料服務SVM上的磁碟區之間的資料保存關係。
* 您可以從資料服務SVM上的磁碟區建立資料保存關係、並在同步來源SVM上建立資料保護（DP）磁碟區。
* 您只能在非SnapLock（主要）Volume和SnapLock 一個目的地（次要）Volume之間建立保存關係。
* 一個選項最多可保護25個磁碟區。


.步驟
. 按一下「*保護*>*磁碟區關係*」。
. 在*關係*視窗中、按一下*建立*。
. 在「*瀏覽SVM*」對話方塊中、選取目的地Volume的SVM。
. 在「*建立保護關係*」對話方塊中、從「*關係類型*」下拉式清單中選取「* Vault *」。
. 指定叢集、SVM和來源Volume。
+
如果指定的叢集執行ONTAP 的是版本早於ONTAP 版本的更新版本、則只會列出已執行的SVM。如果指定的叢集執行ONTAP 的是Sfe9.3或更新版本、則會列出已執行的SVM和允許的SVM。

. 輸入Volume名稱字尾。
+
磁碟區名稱尾碼會附加至來源磁碟區名稱、以產生目的地磁碟區名稱。

. 如果您要建立SnapLock 一個現象區、請指定預設保留期間。
+
預設保留期間可設定為介於1天到70年之間的任何值、或「無限大」。

. *選用：*按一下*瀏覽*、然後變更資料保存原則。
. 從現有排程清單中選取關係的排程。
. *選用：*選取*初始化關係*以初始化資料保險箱關係。
. 啟用SnapLock 「支援整合」功能、然後選取SnapLock 「支援不一致」的集合體或SnapLock 「支援不一致」的「企業」集合體。
. 啟用啟用FabricPool的Aggregate、然後選取適當的分層原則。
. 按一下「*驗證*」以驗證所選磁碟區是否有相符的標籤。
. 按一下「 * 建立 * 」。


.結果
如果您選擇建立目的地Volume、會以下列預設設定建立類型為_DP_的Volume：

* 自動擴充已啟用。
* 根據使用者偏好或來源Volume重複資料刪除設定、會啟用或停用重複資料刪除。
* 壓縮已停用。
* 語言屬性設定為符合來源Volume的語言屬性。


會在目的地Volume與來源Volume之間建立資料保存關係。如果您選擇初始化關係、基礎Snapshot複本會傳輸到目的地Volume。



== 更新關係

您可以使用System Manager手動啟動非排程的遞增更新。您可能需要手動更新、以避免因即將停電、排程維護或資料移轉而導致資料遺失。

.開始之前
必須初始化資料保險箱關係。

.步驟
. 按一下「*保護*>*磁碟區關係*」。
. 選取您要更新資料的關係、然後按一下「*作業*」>「*更新*」。
. 請選擇下列其中一個選項：
+
** 選取*根據原則*以在來源與目的地磁碟區之間執行最近通用Snapshot複本的遞增傳輸。
** 選取*選取Snapshot COPU*並指定您要傳輸的Snapshot複本。


. *選用：*選取*限制傳輸頻寬至*、以限制傳輸所用的網路頻寬、並指定最大傳輸速度。
. 按一下 * 更新 * 。
. 在* Details（詳細資料）*選項卡中驗證傳輸狀態。




== 刪除關係

您可以使用System Manager結束來源與目的地Volume之間的資料保存關係、然後從來源釋出Snapshot複本。

.關於這項工作
釋出關係會永久移除來源磁碟區上資料保存關係所使用的基礎Snapshot複本。若要重新建立資料保險箱關係、您必須使用命令列介面（CLI）從來源磁碟區執行重新同步作業。

.步驟
. 按一下「*保護*>*磁碟區關係*」。
. 選取您要刪除資料保險箱關聯的磁碟區、然後按一下*刪除*。
. 選取確認核取方塊、然後按一下*刪除*。
+
您也可以選取「發行基礎Snapshot複本」核取方塊、以刪除來源磁碟區上資料保險箱關係所使用的基礎Snapshot複本。

+
如果關係尚未釋出、則您必須使用CLI在來源叢集上執行發行作業、以從來源Volume刪除為資料保險箱關係所建立的基礎Snapshot複本。





== 恢復關係

您可以使用System Manager來恢復靜止的資料保險箱關係。當您恢復關係時、系統FlexVol 會恢復正常資料傳輸至目的地的還原磁碟區、並重新啟動所有的保存活動。

.步驟
. 按一下「*保護*>*磁碟區關係*」。
. 選取您要恢復資料傳輸的關係、然後按一下「*作業*」>「*恢復*」。
. 在*恢復*視窗中、按一下*恢復*。


.結果
恢復正常資料傳輸。如果關係有排程的傳輸、則會從下一個排程開始傳輸。



== 靜止關係

您可以FlexVol 使用System Manager來停止資料傳輸至目的地的資料流通、方法是停止資料保存關係。

.步驟
. 按一下「*保護*>*磁碟區關係*」。
. 選取您要停止排程資料傳輸的關係、然後按一下「*作業*」>「*靜止*」。
. 在*靜止*視窗中、按一下*靜止*。


.結果
如果沒有正在進行的傳輸、傳輸狀態會顯示為「靜止」。如果傳輸進行中、傳輸不會受到影響、傳輸狀態會顯示為靜止、直到傳輸完成為止。

*相關資訊*

xref:reference_protection_window.adoc[保護所需時間]
